- cla-backend-go/swagger/cla.yaml
- Fix the issue reported by Nirupama regarding query param for companyName.
- Update the pattern for companyName query param.
> [#1130] Contributor Console API - Organization Service Support api bugfix

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/service.go
- Fixed check by leveragig existing cla managers for company and project service
> [#1107, LFX-2205] Bug/Check Signed Projects

- cla-backend-go/gerrits/service.go
- cla-backend-go/swagger/common/gerrit-repo.yaml
> Gerrit - Added Connected Flag in Response Model

- cla-backend-go/cmd/server.go
- cla-backend-go/project/service.go
- cla-backend-go/swagger/common/project.yaml
- Added Flag for checking claGroups signed at Foundation or Project Level
> Feature/ Check Level Signature (Project Service)

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/swagger/common/health-status.yaml
- cla-backend-go/swagger/common/health.yaml
- cla-backend-go/swagger/common/version.yaml
- cla-backend/cla/controllers/github.py
- cla-backend/cla/models/github_models.py
- Added logic to update the github status when previously needing to affiliate with company
- Updated debug logic
- Added description and examples to health and version swagger definitions
- Added logo to swagger spec
> [#1498] Update GitHub Status Check

- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/routes.py
- Add flag to check if cla is signed at project|foundation level
> Feature/ Python v2 Level Check

- cla-backend-go/company/handlers.go
- cla-backend-go/company/service.go
- cla-backend-go/go.mod
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/v2/organization-service/client.go
- leverage existing company search endpoint with website name query param.
**Validation Rules:**
1. Check to see if the website exists - if so, return an empty list to the user
2. Check to see if the organization name exists, if so, an empty list to the user
3. If the website and organization name (tuple) does not match, if so, an empty list to the user
> [#1499] V2 - Create Company - Company exists or any other server side validations are done after contributor logs into LF system

- cla-backend-go/project/handlers.go
- cla-backend-go/project/service.go
- cla-backend-go/serverless.yml
- cla-backend-go/v2/project/handlers.go
- cla-backend/serverless.yml
- Handled missign foundationID value in CLA Group record - used external ID
- Updated logger format for lambda
- Added additional debug
> [#1529] Resolve v1 Delete CLA Group

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Changed response with list of cla manager designees for SF projects associated with cla Group
- Changed email content to showcase the multiple SF Projects
- Added Validation for Invitee Name field
> [#1520, #1377] Bug/Invite Admin

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/project.yaml
- cla-backend-go/swagger/common/properties/cla-group-description.yaml
> [#1268] Added CLA Group Description Validation

- cla-backend-go/cmd/functional_tests/cla_group/cla_group.go
- cla-backend-go/cmd/functional_tests/company/company.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/swagger/common/org.yaml
- cla-backend-go/swagger/common/properties/company-name.yaml
- cla-backend-go/swagger/common/properties/email.yaml
- cla-backend-go/swagger/common/properties/website.yaml
- cla-backend-go/swagger/multi-file-swagger.py
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Added additional swagger validation for company name, email, CLA Group
Name and Description
> [#1268] Added Additional Validation

- dev.md
> Updated DEV Setup Notes

- cla-backend-go/swagger/multi-file-swagger.py
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/company/handlers.go
- fixes a condition where the nested lists also contain dicts so goes all the way down and does all the replacements.
> adding support for checking lists recursively as well

- cla-backend-go/go.mod
- cla-backend-go/go.sum
- New version of LFX-Kit incorporates the IAM update which "Dynamically
authorizes access to projects if user has foundation level permissions"
- Bumped library to v0.1.17
> LFX-Kit Library Update - Cascading Permissions

- cla-backend/cla/routes.py
- Resolved v2 endpoint that handles getting clagroups when checking for (non existent cla Group records)
> Bug/Get Project

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/cla_manager/service.go
- Added invite link in body for users with no LF login
> [#LFX-2188] Bug/User Invite - Add CLA Manager

- cla-backend-go/swagger/common/properties/cla-group-description.yaml
- cla-backend-go/swagger/common/properties/cla-group-name.yaml
- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts
- Expanded regex to allow for . , and _
> CLA Group Name and Description RegEx Updates

- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/project/service.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- cla-backend-go/v2/dynamo_events/service.go
- Fixed permissions set at initial signing at foundation level
- Exposed levelSigningCheck(project)
- Added project Service at dynamo_events Service layer
> [#1537, LFX2211] Bug/Acs Permissions Foundation

- cla-backend-go/signatures/projections.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/swagger/common/signature.yaml
- cla-backend-go/v2/signatures/handlers.go
- Added additional query filter to search by individual, employee and
corporate signatures.
> EasyCLA Signature Query Updates

- cla-backend-go/go.mod
- cla-backend-go/go.sum
> Updated to LFX-Kit v0.1.18

- cla-backend-go/gerrits/handlers.go
- cla-backend-go/gerrits/repository.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/go.mod
- cla-backend-go/go.sum
- cla-backend-go/swagger/common/add-gerrit-input.yaml
- cla-backend-go/v2/gerrits/handlers.go
1. Implement the swagger validation.
2. Bugfix reported by Nirupama.
3. Dynamically populated version filed in Gerrit API.
> [#1451] Project Console Gerrit API-Bug-Fix.

- cla-backend-go/company/service.go
> [#1499] V2 - Search org endpoint-bugfix-remove unwanted logs.

- cla-frontend-project-console/src/ionic/constants/general.ts
- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.html
- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.scss
- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts
> v1 Project Console - CLA Group Name / Description Validation

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/properties/project-name.yaml
- cla-backend-go/v2/cla_manager/service.go
- Updated API to rename project name to CLA Group name
- Added logic to add more user information to email, if available
- Added project name swagger common property
> CLA Manager Notification Email Updates

- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/routes.py
- Added conditional around signed at foundation flag logic
> [#1533] Resolved CORS API Issue - Signed at Foundation Flag

- cla-backend-go/project/service.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- Refactored foundation check args for claGroups that are signed
- Resolved claGroup table search by foundation_sfid index in case project is of foundation type
> [#1560] Bug/Foundation Level Add CLA Manager

- cla-backend-go/project/handlers.go
- cla-backend-go/project/repository.go
Fixed the page size issue which gives 500 response code.
> [#1001] V2 API (project/{{projectid}} API Endpoint): 500 response code is returned for valid user - Bugfix

- cla-backend/serverless.yml
> Added Dynamo Events Handler for Projects Table

- cla-backend-go/approval_list/repository.go
- cla-backend/serverless.yml
- infra/index.ts
> Updated Index and Deployment Config for DynamoDB Event Projects Lambda

- cla-backend-go/v2/dynamo_events/cla_groups_db_handler.go
- cla-backend-go/v2/dynamo_events/service.go
> DynamoDB Debug Handler

- cla-backend-go/approval_list/repository.go
- cla-backend-go/cla_manager/repository.go
- cla-backend-go/v2/dynamo_events/cla_groups_db_handler.go
- Updated Model Type to marshal - changed to DB Model
> Resolves Marshalling Issue of Projects Table Data

- cla-backend-go/approval_list/repository.go
- cla-backend-go/cla_manager/repository.go
> Resolved Index Query - LastEvaluatedKey

- cla-backend-go/approval_list/repository.go
- cla-backend-go/cla_manager/repository.go
> Resolved Update DynamoDB Syntax

- cla-backend-go/go.sum
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
1. Implement the invite-company-admin endpoint when contactAdmin flag is true change the status code 204 to 200 and update the response.
> [#1573] V2-invite-company-admin endoint response change

- cla-backend-go/v2/signatures/handlers.go
- Removed header parameter checks for username,email and acl
> [#1560] Bug/Update Approval

- cla-backend-go/check-headers.sh
- Added vendor-new and pytest-cache as exclude packages for header checks
> Feature/Lint Header Check

- cla-backend-go/projects_cla_groups/repository.go
- Fixed getting claGroups assocaited with salesforce projects for a company
> [LFX-2221] Bug/Get Cla Groups for External entities

- infra/index.ts
Alter the attribute type Bool to String.
> [#1594] Alter cla-stage-event attribute type

- .circleci/config.yml
- cla-backend-go/v2/cla_manager/service.go
- cla-backend/check-headers.sh
- cla-backend/cla/tests/__init__.py
- cla-backend/cla/tests/unit/__init__.py
- cla-backend/requirements.txt
- cla-backend/run-lint-file.sh
- cla-backend/run-lint.sh
- cla-backend/run-tests.sh
- Updated email text - added spacing
- Added license header check for python in cla-backend src folder
- Added license header for python, requirements and shell scripts in src cla-backend.
> Updated Email Text Email

- cla-backend-go/v2/cla_manager/service.go
- Added role to signature method for sending emails to user with No LFID
> [#1572] Bug/Role for users with no LFID

- cla-backend-go/v2/cla_manager/handlers.go
- Removed company/organization check to enable contributors with no company association get assigned
> [#1569] Bug/Cla Manager designee for contributors

- cla-backend-go/.gitignore
- Fixed ignoring vscode IDE files
> Bug/Ignore Vscode IDE

- cla-backend-go/swagger/common/add-gerrit-input.yaml
> Updated Gerrit Swagger Docs for Create Gerrit Instance

- cla-backend-go/check-headers.sh
- cla-backend-go/project/service.go
- cla-backend/check-headers.sh
- cla-backend/cla/models/dynamo_models.py
- Updated logic in go and python for foundation level CLA checks
- Updated license header - fixed file list
> Updated Foundation Level CLA Checks

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
Improve error logging and update the status code.
> [#1374] V2 - Appropriate error message is not displayed when trying to identify a user associated with another company as CLA manager

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
- infra/index.ts
> Added Gerrit Name Index

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Handled conflict raised for already existing cla manager designee role
- Removed organization scope check (allow contributors to get assigned)
> [#1569,#1571,#1574] Bug/Cla Manager Designee

- cla-backend-go/gerrits/handlers.go
- cla-backend-go/gerrits/repository.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/package.json
- cla-backend-go/serverless.yml
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/swagger/common/add-gerrit-input.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/gerrits/handlers.go
- cla-backend-go/yarn.lock
- cla-backend/serverless.yml
- infra/index.ts
1. Improve error logging.
2. Added validation while adding Gerrit.
> [#1451] Implement error logging and added validation for Gerrit endpoint.

- cla-backend-go/v2/cla_manager/service.go
- Updated email subject and header with appropriate contributor details
> [#1373] Bug/Email to admin

- cla-backend-go/v2/cla_manager/service.go
- Handled 404 when hitting ListOrgServiceScopes endpoint
> [#1571] Bug/Cla Manager Designee

- cla-backend-go/v2/company/service.go
- Enabled user to create company with no LFID tagged to user
> [#1018] Feature/Create Org no LFID

- cla-backend/cla/controllers/signature.py
- cla-backend/cla/controllers/user.py
- Fixed unintended new lines for email content (Python)
> [#1649] Bug/ Email Format Python

- cla-backend-go/swagger/common/properties/website.yaml
- cla-backend-go/tests/utils_regex_test.go
- cla-backend-go/utils/regex.go
- Updated regex
- Added helper function
- Added unit tests
> [#1018] Updated Website URL Regex - Resolves invalid website issue

- cla-backend-go/v2/cla_manager/service.go
- Fixed check with internal company ID other than SF company IDs
> [#1368] Bug/Already Signed

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
1. Fix the role assignment issue at the foundation level.
2. Clean up the code and fix the lint issue.
> [#1627] V2 - Company Not Found - Foundation Level - CLA Manager Designee role is assigned to sub projects instead of foundation

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
- Failed access to font dir: neither $XDG_CONFIG_HOME nor $HOME are defined
> Resolved Failed Access to Font Dir Issue

- cla-backend-go/events/event_data.go
- cla-backend-go/events/models.go
- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/package.json
- cla-backend-go/swagger/common/event.yaml
- cla-backend-go/yarn.lock
1. Update the event swagger model with Summary field
2. Added GetEventSummaryString and rename the interface with GetEventsString to GetEventDetailsString.
3. Updated the error message while creating Gerrit.
> [#1648] Event Log Message Simplification

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/service.go
- Resolved bug from UI part that requires organizationID in response
> Bug/Add Organization

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Resolved empty string for fullName in payload
- Return 400 for no LFID found for requested user
> [#1107] Regex CLA Manager Request

- .circleci/config.yml
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- Added foundation level CLA flag to CLA Group Create and Query for CLA Groups
> Added Foundation Level CLA Flag

- cla-backend-go/swagger/cla.v2.yaml
> Removed Unused Request Parameters For CLA Template Preview

- cla-backend-go/v2/cla_groups/service.go
- Updated validation logic to allow standalone projects to either have
no sub-projects as input or have the foundation SFID in the project list
> [#1677] Resolved Validation Issue for Standalone Projects

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/project/handlers.go
- cla-backend-go/project/repository.go
- cla-backend-go/project/service.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/repositories/models.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/service.go
- Resolved DB update syntax error
- Refactored repositories table API and db logic - renamed service and
db functions, added enabled/disabled options. Changed deleted to
disabled.  General API cleanup.
> [#1682] Resolved Repository Delete Regression - Updated API

- cla-backend-go/cmd/server.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
- Added unenroll project from CLA Group swagger spec
- Added unenroll service logic
- Added unenroll API call to project service to remove CLA Service
- Added enroll API call to project service to add CLA Service
> [#1668] Added Unenroll Service API Endpoint

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/cla_manager/service.go
- Altered scope from organization to project|organization scope when sending invite
> [#1664] Bug/Scope CLA Manager Request for Users with no LFID

- cla-backend-go/v2/company/service.go
- Created association for newly created salesforce org with user
> [#1683] Bug/User-Org association

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Addded EasyCLA endpoint for getting SF company Admins
> [#1679] Feature/ Admins SF Companies

- .circleci/config.yml
- cla-backend/package.json
- cla-backend/serverless.yml
- cla-backend/yarn.lock
- cleaned up and remove s3 and dynamodb local testing config
> Removed S3 and Dynamodb Local Test

- cla-backend-go/serverless.yml
- cla-backend/requirements.txt
- cla-backend/serverless.yml
- Added SETUPTOOLS_USE_DISTUTILS=stdlib environment variable to address
issue: https://github.com/pypa/setuptools/issues/2350 and
https://github.com/pypa/setuptools/issues/2232
> Resolved Python AWS Lambda Setup Utils Library Issue

- cla-backend/cla/controllers/company.py
- cla-backend/cla/controllers/github.py
- cla-backend/cla/controllers/project.py
- cla-backend/cla/controllers/signature.py
- cla-backend/cla/controllers/user.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/tests/unit/test_company_event.py
- cla-backend/cla/tests/unit/test_event.py
- cla-backend/cla/tests/unit/test_project_event.py
- cla-backend/cla/tests/unit/test_signature_event.py
- cla-backend/cla/tests/unit/test_user_event.py
- cla-backend/cla/utils.py
- Added events_summary attribute for Events model(Pynamo API)
- Added events_summary data to test events for signing, company and user events
> [#1648] Feature/Python events for Summary

- cla-backend-go/projects_cla_groups/models.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/template/repository.go
- cla-backend-go/v2/cla_groups/service.go
[#1677] Added Additional Create CLA Group Validation Logic
- Added checks when we have  new CLA Group request and there are
existing Foundation Level CLA Groups for the same foundation
- Added checks for new Foundation CLA Group under a foundation when
existing foundation sub-groups are already in another CLA Group
- Updated error handling for stand-alone projects
- Added debug log messages
- Added helper functions to cleanup the code
> [#1677] Added Additional Create CLA Group Validation Logic

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- Fixed issue for company owner not getting assigned at the right stage
- Set Company association for user not associated with any company
> [#1696] Bug/Contributor Company Owner

- cla-backend-go/v2/cla_manager/service.go
> [#LFX-2221] Bug/LF Login

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Altered response code (204) for Users with No LFID
> [#LFX-2375] Bug/ No LFID Request User

- cla-backend-go/v2/cla_manager/service.go
- Removed designee in response error for users already assigned cla-manager-designee role
> [#1570] Bug/Response CLA Manager Designee

- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
> Project Console - remove duplicate "View Companies" button

- cla-backend/cla/models/docusign_models.py
- Fixed issue caused by invalid syntax for request corporate signature endpoint (v1/Python)
> Bug/Request Corporate Signature

- cla-backend-go/gerrits/handlers.go
- cla-backend-go/gerrits/repository.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/go.mod
- cla-backend-go/v2/gerrits/handlers.go
Added groupID ICLA and CCLA validation.
> [#1451] Added validation on gerrit flow

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- Added swagger definition for 202 response - when no LF Logins exist for user
- Updated invite company admin for both contributor and corporate console
> [#2375] Bug/ No LF Login

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/swagger/common/create-github-organization.yaml
- cla-backend-go/swagger/common/update-github-organization.yaml
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/github_organizations/service.go
> Added API to Enable/Disable AutoEnabled Feature for GitHub Organization

- cla-backend-go/go.mod
- cla-backend-go/go.sum
- cla-backend-go/template/service.go
- cla-backend-go/v2/github_organizations/handlers.go
> PDF Generation Speed Up

- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/github_organizations/handlers.go
- Fixed issue of association by removing project signed check
> [#1357] Bug/Contributor Association

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
> Fixed Swagger Documentation for GitHub Organization Config Update

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/github_organizations/handlers.go
- Added check for project signed at foundation level while adding cla-manager role
> [#1597] Bug/Foundation Level Add Manager

- cla-backend-go/v2/cla_groups/service.go
- Optimized queries
- Removed duplicates
> Updated CLA Groups API to Remove Duplicates

- cla-frontend-contributor-console/package.json
- cla-frontend-contributor-console/yarn.lock
- Resolves CVE-2020-8244 issue for bl library
> Dependabot BL Library Update

- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.html
As per comment on ticket #1023 disabled ICLA, CCLA, and ICLA + CCLA checkbox on edit CLA group.
> Project Console - Not able to update Project(CLA Group) configuration

- cla-backend-go/company/service.go
- Altered response to make it user friendly when no company admins are found for SF org
> [#1680] Feature/EasyCLA Company Create

- cla-backend-go/utils/constants.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/dynamo_events/github_repository.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/repositories/service.go
- cla-backend-go/v2/sign/service.go
> Added The Linux Foundation Super Group support

- cla-backend-go/v2/cla_manager/service.go
- Added company owner role on the invite admin flow after designee has been set
> [#1694] Bug/Invite Admin Flow (Contributor Console)

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_groups/service.go
- Resolved duplicate CLA Groups issue
- Resolved Foundation Level CLA Groups GET issue
- Sorted Project List
> CLA Group Create and Get Updates

- cla-backend-go/package.json
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/yarn.lock
1. Added goroutine to enroll project function to improve the performance.
2. Fix the duplicate cla-group response issue while GET calls using foundation ID.
> [#1510] V2 - Project Console - Observed performance issues with enabling or disabling of CLA service for projects in project service

- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
- Updated unenroll logic, updated validation, resolved unenroll issue
- Updated Create CLA Group error response status code
- Resolved foundation ID/Name issue with list projects
> [#1623,#1716,#1693,#1668] Create/Enroll/Unenroll/Get CLA Group Updates

- cla-backend-go/v2/cla_groups/service.go
> Added Check to Prevent Unenroll of Foundation

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/service.go
- Changed response to 'Accepted' for users with no LF login in the contributor console
> [#1625,#1743] Bug/Contributor Console

- cla-backend-go/package.json
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/yarn.lock
1. Fixed the enrolled project list issue in GET cla-group under foundation\Project API.
> [#1623] V2 - Cla-group enroll project list incorrect-bugfix

- cla-backend-go/v2/cla_manager/service.go
- Fixed issue raised when assigning company owner role for cla manager designee workflow
- Assign company owner role to users who have no company
> [#1770, #1740, #1738, #1769, #1766, #1764, #1766, #1754] Bug/Designee

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/organization-service/client.go
- Fixed assigning company owner in the invite flow
> [#1773] Bug/Company Owner (Contributor console)

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/organization-service/client.go
- Fixed check for user having company-owner role
> [#1773] Bug/Company Owner

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/models.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/user-service/client.go
- Updated API call to the user service - descreased the latency for this
set of API calls from 24-29 seconds down to 3-4 seconds
- Updated API calls to fetch existing CCLA records for a given project
SFID - confirmed querying using approved and signed
- Added additional debug logging/metrics for cataloging performance
> Performance Updates

- cla-backend-go/utils/constants.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/organization-service/client.go
- Refactored CLA Group delete logic to specify the correct Project SFID
when removing roles
- Added go routines to do a number of cleanup activities concurrently
> [#1503] CLA Group Delete Updates

- cla-backend-go/v2/sign/service.go
Fixed the issue related to the cla-signatory role assignment.
> [#1732] V2 - Corporate Console - CLA Signatory role is not assigned when cla manager designee himself/herself proceeds with signing CLA

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Added concurrency during assign process for multiple project|org scopes
> [#1774] Bug/Cla Manager Designee Assignment

- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/organization-service/client.go
- Updated error response
- Updated delete role event log data
> Updated Delete CLA Group Response/Error Handling

- cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts
> Gerrit Contributor email does not populate in form to send to CLA Manager (Approved List request)

- cla-backend-go/swagger/cla.yaml
- Resolves upper case search issue
> Updated WebSite Name Regex

- cla-backend-go/package.json
- cla-backend-go/v2/sign/service.go
- cla-backend-go/yarn.lock
Fixed conflict issue while the same request happened multiple times.
> [#1790] [Regression] V2 - Corporate Console - When duplicate signatory requests are made 409 is returned and UI is impacted by this

- cla-backend-go/cmd/functional_tests/main.go
- cla-backend-go/cmd/repositories/repositories.go
colorio
Signed-off-by: makkalot <makkalot@gmail.com>
> guard for nil value and change the auth user to cla manger of

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/signatures.go
- cla-backend/cla/models/docusign_models.py
- Added hooks for querying and removing CLA Group permissions for
assigned roles (cla-manager, cla-manager-designee, and cla-signatory).
Waiting on feedback to determine API for this.
> [#1762] Added Phase 1 of CLA Permissions Cleanup

- cla-backend-go/v2/company/service.go
- Fixed bug raised when converting to lead during the association process
> [#1478] Bug/Contributor Association

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- Assign company owner role with no authentication required
> Feature/Company Owner

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/tests/utils_requests_test.go
- cla-backend-go/utils/requests.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/health/handlers.go
- cla-backend-go/v2/metrics/handlers.go
- Resolved delete Project CLA Group Entries
- Updated API to return 404 when cla-groups query is made
- Added request-id header and response
> [#1716] Resolved Issues with Create and Delete CLA Group

- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/organization-service/client.go
- Refactored check for user in different org
- Changed response on assignment fail to 200
> [#1789] Bug/Company Owner

- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Added Email Notification on successful user assignment with company-owner role
> [#1812] Feature/Email Notification

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
- infra/index.ts
- Updated infra script to include the index defintion
- Updated the serverless config to grant the lambda permissions to use
the new index
> Added GitHub Organization Name Lower Search Index

- cla-backend-go/v2/cla_manager/service.go
- Added conversion ,if user is lead, to contact
> [#1806] Feature/Convert to Contact

- cla-backend-go/cmd/server.go
- cla-backend-go/signatures/handlers.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/signatures.go
- cla-backend/cla/controllers/signing.py
- cla-backend/cla/models/docusign_models.py
- Added x-request-id to /v3 APIs/swagger
- Added http request filter to add x-request-id, when missing
- Updated logic to remove cla-designee role
> [#1792] Review/Update CLA Role Assignment/Cleanup

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- Added handling for users with no LFID (sending user invite)
> [#1789] Feature/ Assign Company owner no LFID

- cla-backend-go/github/github_repository.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/service.go
1. Fixed the error handling issue.
2. Added the validation while adding githib org and repo APIs.
3. Implement indexing for orgname case issue.
> [#1390] Update github repository and github organization api to support project-console github organization manager view

- cla-backend-go/package.json
- cla-backend-go/users/service.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/yarn.lock
1. Fixed the invite user flow and improve error logging.
> [#1733] V2 - Corporate Console - Not able to add a user without LFID as CLA Manager 

- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/cla_manager/service.go
- cla-backend-go/gerrits/handlers.go
- cla-backend-go/project/handlers.go
- cla-backend-go/project/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- cla-backend-go/v2/dynamo_events/signatures.go
- cla-backend-go/v2/gerrits/handlers.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/project/service.go
- cla-backend-go/v2/signatures/handlers.go
- Added debuggin
- Added context/request ID
> Added additional debugging

- cla-backend-go/v2/cla_manager/service.go
- Added check for claGroup level signage
> [#1735] Bug/Invite Company Admin

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend-go/v2/dynamo_events/signatures.go
- Removed verbose event logging
- Resolved object_id type marshalling issue - changed string to int
- Resolved remove CLA designee role permissions filter (now filters on roleName)
- Updated go routine loop logic and error handling
> [#1792] Resolved API and Logic Errors

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- Resolved response model issue
> [#1792] Resolved GetObjectTypeIDByName Issue

- cla-backend-go/tests/acs_test.go
- cla-backend-go/v2/acs-service/client.go
- Replaced manual http requests with swagger client stub calls
> Updated ACS API Calls

- cla-backend-go/v2/company/handlers.go
- Altered scope check by project
> Feature/ CompanyProject Contributors auth

- cla-backend-go/company/handlers.go
- Refactored company search by external ID
> [#1685] Feature/ Search Company response

- cla-backend-go/cmd/server.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/repositories/service.go
- cla-backend-go/swagger/cla.yaml
1. Added Validation for Add Github repo API.
2. Fixed the error logging and improve error code.
> [#798] migrate repositories api to golang

- cla-backend-go/v2/company/handlers.go
- Allow PM to access project company contributors with appropriate Project Scope
- Allow CLA manager to access project company contributors with appropriate Project|Org scope
> Adjusted Project Company Contributors Permissions

- cla-backend-go/v2/cla_manager/service.go
- Added user conversion to contact in the invite flow
> [#1806] Feature/ User Conversion

- cla-frontend-corporate-console/src/ionic/constant/general.ts
- cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html
- cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.ts
- cla-frontend-project-console/src/ionic/constants/general.ts
- cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html
- cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.ts
> Link to documentation on all Landing pages

- cla-backend-go/approval_list/service.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/signatures/converters.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Added missing CCLA CSV Download Function implementation
- Move constants to constants.go
- Removed verbose queryInput output
> Added CCLA CSV Download Function

- cla-backend-go/tests/pmm_test.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/project-service/client.go
- Added lookup for The Linux Foundation parent project
- Added temp work around for project service search - doesn't seem to be working without auth
> Resolved The Linux Foundation Parent Issue

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- Fixed issue for multiple invites by checking username attribute
> [#1789] Bug/Contributor console user invites

- cla-backend-go/project/repository.go
- cla-backend-go/v2/cla_groups/handlers.go
> Cleaned up Response Error Codes

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/properties/email.yaml
- cla-backend-go/v2/cla_manager/service.go
- Fixed error thrown when a user has not created lf account
- Added swagger regex for email used in payload for add cla manager
> [#1618] Bug/Add CLA Manager no LFID

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/properties/email.yaml
- cla-backend-go/v2/cla_manager/service.go
- Updated email content sent to company admin with no reference to contributors
> [#1666] Bug/Email Contact for admin

- cla-backend-go/v2/cla_manager/service.go
- Changed contributor to user in email content send to company admins
> [#1666] Bug/Admin Email

- cla-backend/cla/controllers/github.py
- Updated format of email by removing <br> tag
> [#1868,#1390] Bug/ Email content CLA Group

- cla-backend-go/v2/cla_manager/service.go
- Convert GH user if LFID exists with username/email searches
> [#1806] Bug/ GH Conversion to Contact

- cla-backend-go/docraptor/client.go
- cla-backend-go/template/repository.go
- cla-backend-go/template/service.go
- cla-backend-go/utils/utils.go
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- Resolved issue where additional template generation was overwriting
existing CCLA templates in the database and S3. Code now appends a
new record and generates a time-based filename, instead of icla.pdf,
it generates icla-YYYY-MM-DDTHH-MM-SSZ.pdf.
> [#1873,#1871] Resolved CCLA Template Update Issue

- cla-backend-go/template/repository.go
- Updated address field alignment of the Apache Style template
> [#1875] Apache-Style CCLA and ICLA Template Address Alignment

- cla-backend-go/events/event_data.go
- cla-backend/cla/models/docusign_models.py
- Removed IDs from the event summary fields
> [#1880] Cleaned Up Activity Log Summary

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Added swagger required validation for fullName in payload
> [#1107] Bug/Corporate Console invite manager

- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Updated API permissions to allow both Project scope and
Project|Organization scope for get project org signatures
- Added additional debug and error handling
> [#1878] Updated Permissions Logic

- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/serverless.yml
- cla-backend-go/v2/dynamo_events/github_organization.go
- cla-backend-go/v2/dynamo_events/github_repository.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend/serverless.yml
- infra/index.ts
- Handled use case where branch protection is added after repos are
added to the DB
> Added Additional Enable Branch Protection Logic

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Removed user invite sent to users with no LF Login for CLA Manager assignment
> [#1882] Feature/Disable user invites

- cla-backend-go/package.json
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/yarn.lock
Fixed the response and status code.
> [#1888] V2 - Project Console - When there is no data getProjectSignatures should return 200 with empty list

- cla-backend/serverless.yml
> Added Additional DB Trigger for GitHub Orgs Table

- cla-backend-go/v2/cla_manager/service.go
- Refactored email sent to invited cla manager
> [#1866] Feature/Invite Email

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/github_organizations/service.go
> Added Branch Protection to Get GitHub Orgs Response

- cla-backend-go/v2/cla_manager/service.go
- Refactored by checking contactAdmin flag during invite-company-admin flow
> [#1866] Bug/Contact Company Admin

- cla-backend-go/template/service.go
- cla-backend-go/tests/utils_test.go
- cla-backend-go/utils/url.go
> Updated S3 Template URL Download Logic

- cla-backend-go/v2/dynamo_events/github_organization.go
- cla-backend-go/v2/dynamo_events/service.go
- infra/index.ts
> Resolved SegFault in Repo reference

- cla-backend-go/go.mod
- cla-backend-go/userSubscribeLambda/cmd/serve_lambda.go
- cla-backend-go/userSubscribeLambda/cmd/serve_local.go
- cla-backend-go/userSubscribeLambda/main.go
Change SQS to SNS event subscribe.
> [#1364] Implement sns event

- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/swagger/cla.yaml
Fixed the GitHub org endpoint issue.
Added validation for the project and org name.
Fix the status code issue.
@dealako help me with 500 status code issues for the v3 endpoint.=> **(Blocked ticket for the same issue #781 #798)**
> [#781] migrate github organization api to golang v3 endpoints

- cla-backend-go/v2/cla_manager/service.go
- Fixed issue of assigning cla manager depending on the level of CLA signature
> [#1763] Bug/Add CLA Manager Level

- cla-backend-go/v2/cla_manager/service.go
- Fixed role assignment at the right level (foundation or project)
> [#1735, #1740] Bug/Invite Flow

- cla-backend-go/github_organizations/helpers.go
- cla-backend-go/github_organizations/models.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/project-service/client.go
- Updated query/get logic to first look at the projectSFID then try the parent
> Resolved Issue with Fetching GitHub Organization Repos By ProjectSFID

- cla-backend-go/auth/authorizer.go
fixes #781 and #798 token expired issues
> return 401 when the token is expired instead of 500

- cla-backend-go/cla_manager/service.go
- cla-backend-go/v2/user-service/client.go
- Added email check from user service for cla managers
> [1734] Feature/Email

- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- Refactored designee and company owner emails for users with no LFIDs
> [#1879] Feature/Invite Emails

- cla-backend-go/v2/cla_groups/handlers.go
- Added additional validation logic for missing body/payload, duplicate name/description
> [#1622] CLA Group Update - Added Additional Validation Logic

- cla-backend/cla/models/docusign_models.py
- Added log entry for use case of private GH email
> [#1244] Bug/Docusign ICLA callback

- cla-backend-go/auth/authorizer.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/v2/events/handlers.go
- Updated logic to return 200 empty list when no event log entries are
found or if the project mapping does not exist.
> [#1922] Get Project Events Response Code Updates

- cla-backend-go/v2/events/handlers.go
- Avoid 400 errors on empty response
> [#1922] Updated Events Query Responses

- .circleci/config.yml
- cla-backend-go/package.json
- cla-backend-go/serverless.yml
- cla-backend-go/yarn.lock
Update server-less file and circle ci file.
> [#1363] Update user-subscribe-lambda

- cla-backend-go/v2/events/converters.go
- cla-backend-go/v2/events/handlers.go
- Updated logic to set the next key if provided from service layer
> [#1922] Updated NextKey Response Value for Event Pagination

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/tests/unit/test_dynamo_models.py
- cla-backend/cla/utils.py
- Filter getting user email excluding private instances
- Added unit tests for getting user email
> [#1244] Bug/Send Email - ICLA callback

- cla-backend-go/utils/errors.go
- cla-backend-go/v2/cla_groups/handlers.go
- Leveraged errors.As errors.Is functions to test for certain errors
- Addd Unwrap function on custom error types
> [#1622] Updated CLA Group Update Error Handling

- cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.html
- cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.scss
- cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
- cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.html
- cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.scss
- cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.ts
- cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.ts
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
- cla-frontend-project-console/src/ionic/services/cla.service.ts
> Migrate GitHub organisation API to golang

- cla-frontend-corporate-console/src/ionic/decorators/restricted.ts
- cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
- cla-frontend-corporate-console/src/ionic/services/auth.service.ts
> Updated SSM param landing-page key.

- cla-backend/cla/controllers/user.py
- cla-backend/cla/tests/unit/test_user_event.py
- Fixed bug caused by typo in event call
- Refactored unit test for this use case
> [#1948] Bug/Invite Company Admin

- cla-backend/cla/models/docusign_models.py
- Altered return url for gerrit instances
> [#1431] Feature/Gerrit Return Url

- cla-frontend-corporate-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-corporate-console/src/config/scripts/read-local.js
- infra/get-ssm-parameters.ts
> Added SSM LFX Header Feature Flag

- cla-backend-go/userSubscribeLambda/main.go
> [#1364] Update user-subscribe-lambda

- cla-backend-go/gerrits/handlers.go
- cla-backend-go/swagger/cla.yaml
> [#899] Migrate gerrit api to golang

- cla-backend-go/v2/cla_manager/service.go
- Fixed removal of CLA Manager at foundation level by checking the signed level
> [#1921] Bug/Remove CLA Manager - Foundation Level

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/infra_update_request.md
- cla-backend-go/.gitignore
- cla-backend-go/Makefile
- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- Updated Issue templates
- Updated serverless lib and support libraries for backend
- Updated Makefile output formatting, cleanup
> Housekeeping

- cla-backend-go/serverless.yml
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend/serverless.yml
- Serverless - added docraptor test mode flag based on the environment
- Serverless - set framework version
- Added debuging to cla-group handler functions
> Infra Updates

- cla-backend-go/v2/dynamo_events/signatures.go
- Catered for foundation level cla groups when removing cla manager designee role on signing
> [#1762] Bug/Update Role on signing

- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
> Updated Serverless Version

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
> Removed Docraptor Test Mode Env

- cla-backend-go/v2/metrics/repository.go
Improve the project-service helper.
Reduce the call to project-service call and internally manage with dynamo DB call.
> [#1939] Investigate and Resolve Project Service High Usage

- cla-backend-go/serverless.yml
- cla-backend/cla/config.py
- cla-backend/cla/controllers/github_application.py
- cla-backend/cla/utils.py
- cla-backend/serverless.yml
- Added config for GH private key that was causing the lambda 4k size limit
> Bug/Limit loading env variables Python Lambda

- .circleci/config.yml
- cla-backend/cla/client.py
- cla-backend/cla/config.py
- cla-backend/cla/utils.py
- Factored out get_ssm function from utils
> Bug/Cyclic Dependency

- .circleci/config.yml
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/tests/utils_test.go
- cla-backend-go/utils/responses.go
- cla-backend-go/utils/utils.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/events/converters.go
- cla-backend-go/v2/events/handlers.go
- cla-backend-go/v2/gerrits/handlers.go
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/metrics/handlers.go
- cla-backend-go/v2/project/errors.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/sign/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/validators.go
- cla-backend-go/v2/template/handlers.go
- Added reqID from the request to the JSON resposne model for v2 APIs
- Added IsUUIDv4 utility method to detect if the client provided a UUIDv4 or SFID
- Added IsUUIDv4 unit test method
- Added logic on employee signature to lookup the company ID via internal or external ID
- Refactored AWS setup in CircleCI config
> Added X-Request-ID to error response model

- cla-backend-go/v2/dynamo_events/github_organization.go
- cla-backend-go/v2/dynamo_events/service.go
> github org added event handler

- cla-backend-go/v2/cla_manager/service.go
- Refactored email content for email sent to invite cla manager - v2 coporate console
> [#1866] Feature/Email CLA Manager Invite

- cla-backend-go/repositories/service.go
- Used project service to check validity of the external ProjectIDs
> Bug/v1 Add GH Repo

- cla-backend-go/v2/cla_manager/handlers.go
- Changed Response when adding CLA Manager for users with no LFID
> [#1882] Feature/ Add CLA Manager Response

- cla-backend/cla/controllers/github.py
- Fixed GH PR email format by changing wrong end tag
> [#1868] Feature/Email Format

- cla-backend-go/events/event_data.go
- cla-backend-go/project/handlers.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- Updated Name and Description update logic - only reject when both are not set
- Updated event logging messages for CLA Group Update
> Updated CLA Group Update Validation Logic

- cla-backend-go/v2/cla_groups/service.go
- Added logic to only set the template URL for ICLA and CCLA in the
response model only when it is configured
> CLA Group Update - Set Template when Enabled

- cla-backend/cla/controllers/project.py
- Added enabled flag for organization repos returned for proper UI experience
> [#1898] Bug/Prject Console Repos

- cla-backend-go/v2/company/handlers.go
Added new conditions to check org scope.
> [#1975] V2 - Corporate Console - Permissions issues with few endpoints

- cla-backend-go/github/client.go
- cla-backend-go/github/github_installation.go
- cla-backend-go/github/github_org.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/github/github_user.go
- cla-backend-go/github/handlers.go
- cla-backend-go/github/mock.go
- cla-backend-go/github/protected_branch.go
- cla-backend-go/github/protected_branch_test.go
- cla-backend-go/go.mod
- cla-backend-go/go.sum
- cla-backend-go/signatures/service.go
- cla-backend-go/v2/repositories/service.go
* update the go-github library to add the latest struct changes
* add logic for the missing fields that were overriding the admin
settings
addresses issue in #1667
> preserve existing admin settings

- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend-go/v2/organization-service/client.go
- Added logic to set cla-manager role for existing CLA managers when a
project is added to the CLA Group
> Added Add CLA Permissions Handler

- cla-backend-go/events/event_data.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend/cla/config.py
- cla-backend/cla/controllers/github.py
- cla-backend/cla/routes.py
- cla-backend/cla/utils.py
- infra/get-ssm-parameters.ts
- Updated event handling logic to run mutliple events as a separate go routine
- Updated Logging
- Added Maintainer list as SSM parameter - verify maintainer list before attempting to send email
> Updated DB Trigger Event Handling Logic and Maintainer List

- cla-backend-go/v2/dynamo_events/service.go
> Added Additional Debug for DB Event Triggers

- cla-backend-go/project/repository.go
- cla-backend-go/utils/errors.go
- cla-backend-go/v2/cla_groups/service.go
- Updated CLA Group name conflict checks - check for existing cla group names
- Added new CLA Group Name conflict error object
> [#1622] CLA Group Name Conflict Checks

- cla-backend-go/v2/dynamo_events/github_organization.go
- cla-backend-go/v2/dynamo_events/service.go
> GitHub Delete Org Event - Resolved Merge Issue

- cla-backend-go/v2/dynamo_events/github_organization.go
- cla-backend-go/v2/dynamo_events/service.go
- infra/ssm/.gitignore
- infra/ssm/.golangci.yaml
- infra/ssm/Makefile
- infra/ssm/go.mod
- Added delete GitHub organization event handler - logic disables the child repos
> [#1995] Added GitHub Org Delete Event Handler

- cla-backend/cla/controllers/signing.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/models/signing_service_interface.py
- cla-backend/cla/routes.py
- cla-backend/cla/tests/unit/test_user_event.py
- cla-backend/cla/tests/unit/test_user_models.py
github primary email is the default preferred email
> adding github preferred email functionality to user model where the

- cla-backend-go/utils/utils_user_auth.go
- cla-backend-go/v2/signatures/handlers.go
- Added helper function to check permissions for a list of projects under a CLA Group - if user has access to any projects, then allow the user to access the signatures
- Updated error handlers logger output and response models with additional details
> Updated Permissions Check for ICLA Signatures

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/yarn.lock
- cla-backend/yarn.lock
- package.json
- yarn.lock
> Reviewed and Updated Signature Checks

- .circleci/config.yml
> Updated serverless invokation

- cla-backend-go/approval_list/handlers.go
- cla-backend-go/approval_list/service.go
- cla-backend-go/approval_list/service_test.go
> fix for Wrong email sent when user is approved access to company

- cla-backend/cla/controllers/github.py
- cla-backend/cla/controllers/signature.py
- cla-backend/cla/controllers/user.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/tests/unit/test_utils.py
- cla-backend/cla/utils.py
* making sure help and sign off is added at the end of the email body
processing
> * adding helper function to add the help and sign off content to emails

- cla-backend-go/utils/utils_user_auth.go
- cla-backend-go/v2/signatures/handlers.go
- Created helper functions to clean up all the logic surrounding
permissions.
> Cleaned Up Signature Access Control

- cla-backend-go/utils/constants.go
- cla-backend-go/v2/company/handlers.go
- Updated permission logic to query project orgs
> [#2014] Updated Company Project Contributors Permissions Check

- cla-backend-go/v2/signatures/handlers.go
> Resolved Type in Permissions

- cla-landing-page/serverless.yml
> Resolved Landing Page Packaging

- cla-backend/cla/models/docusign_models.py
Update the event summary from python code.
> [#1923] V2 - Project Console - In UserAssociatedWithCompany event type event summary has userid and github id

- cla-frontend-project-console/edge/security-headers.js
> Testing Edge Config to Allow LFX-Header

- .circleci/config.yml
- cla-frontend-contributor-console/edge/security-headers.js
- cla-frontend-contributor-console/serverless.yml
- cla-frontend-corporate-console/edge/security-headers.js
- cla-frontend-corporate-console/serverless.yml
- cla-frontend-project-console/edge/security-headers.js
- cla-frontend-project-console/package.json
- cla-frontend-project-console/serverless.yml
- cla-frontend-project-console/src/ionic/app/app.component.ts
- cla-frontend-project-console/src/ionic/services/auth.service.ts
- Added/resolved cloudfront cors/edge issues
- Added Auth0 lib updates to support new LFX-Headers
> CloudFront CORS Updates + Project Console Auth Updates

- cla-landing-page/angular.json
- cla-landing-page/package.json
- cla-landing-page/serverless.yml
- cla-landing-page/src/index.html
- Updated package/deployment
- Updated favion
- Updated SEO meta-data tags
- Updated title and description
- Updated package.json - added deploy:dev target
> Updated Landing Page Deployment

- cla-backend-go/go.mod
- cla-frontend-contributor-console/src/ionic/index.html
- cla-frontend-corporate-console/src/ionic/index.html
- cla-frontend-project-console/src/ionic/index.html
- infra/Pulumi.dev.yaml
- infra/Pulumi.prod.yaml
- infra/Pulumi.staging.yaml
- infra/Pulumi.yaml
- infra/ssm/.gitignore
- infra/ssm/go.mod
> Updated HTML Header Meta-data for Consoles

- cla-backend/cla/controllers/user.py
- cla-backend/cla/tests/unit/test_user_event.py
- Added logic to create a new CCLA Approval request entry in the database
> [#807] Added Logic to Create CCLA Approval Request Entry

- cla-backend-go/v2/organization-service/client.go
Removed v1 basepath from organization service client.
> Removed v1 basepath from organization service client

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
Fixed the 500 issues while invalid cla-group id.
Fixed the panic issue when the company ID is not valid.
Added validation for payload.
Validate user model is empty or not.
> [#1198] Individual Contributor Console Flow Integration - CCLA - With No Signed CLA

- cla-backend-go/cmd/server.go
- cla-backend-go/v2/cla_groups/handlers.go
- Updated CLA Group permission logic
> Updated CLA Group permissions and logging

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/metrics/repository.go
- Updated metrics response model
- Updated API response logic to only include desired metrics
> [#2038] Remove Extra V2 Metrics

- cla-frontend-project-console/src/ionic/app/app.component.ts
- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
> Solved Project Console redirection issue

- cla-frontend-project-console/src/ionic/app/app.component.ts
- cla-frontend-project-console/src/ionic/app/app.module.ts
- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-frontend-project-console/src/ionic/pages/login/login.ts
- cla-frontend-project-console/src/ionic/services/auth.service.ts
- cla-frontend-project-console/src/ionic/services/lfx-header.service.ts
- cla-frontend-project-console/src/package.json
- cla-frontend-project-console/src/yarn.lock
> Project console redirection issue

- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-frontend-project-console/src/ionic/services/auth.service.ts
> Project console loading issue

- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
> removed auth0 check for testing

- cla-backend-go/v2/events/handlers.go
> Updated Event Handler Logging

- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-frontend-project-console/src/ionic/services/auth.service.ts
- cla-landing-page/src/app/components/page-not-found/page-not-found.component.ts
- cla-landing-page/src/app/core/services/auth.service.ts
> Changed redirection from landing page

- cla-frontend-project-console/src/ionic/app/app.module.ts
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
- cla-frontend-project-console/src/ionic/pages/auth/auth.html
- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-frontend-project-console/src/ionic/pages/authorize/authorize.html
- cla-frontend-project-console/src/ionic/pages/authorize/authorize.module.ts
- cla-frontend-project-console/src/ionic/pages/authorize/authorize.ts
- cla-frontend-project-console/src/ionic/services/auth.service.ts
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/app/core/services/auth.service.ts
> Seperate login from landing page

- cla-frontend-project-console/src/ionic/decorators/restricted.ts
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-frontend-project-console/src/ionic/pages/login/login.ts
> Solved logout issue from LFX header

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
Fix the regression issue for the name and email field.
> [#2045] [Regression] - V2 - Contributor Console - Not able to contact company admin

- cla-backend-go/events/repository.go
- Return empty event list when no events are present
- Do not return Nextkey if empty event list
> Updated Events Repository Response

- cla-frontend-contributor-console/edge/security-headers.js
- cla-frontend-corporate-console/edge/security-headers.js
- cla-frontend-corporate-console/src/ionic/app/app.component.ts
- cla-frontend-corporate-console/src/ionic/app/app.module.ts
- cla-frontend-corporate-console/src/ionic/pages/auth/auth.html
- cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
- cla-frontend-corporate-console/src/ionic/pages/authorize/authorize.html
- cla-frontend-corporate-console/src/ionic/pages/authorize/authorize.module.ts
- cla-frontend-corporate-console/src/ionic/pages/authorize/authorize.ts
- cla-frontend-corporate-console/src/ionic/services/auth.service.ts
- cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- cla-frontend-corporate-console/src/ionic/services/lfx-header.service.ts
- cla-frontend-corporate-console/src/package.json
- cla-frontend-corporate-console/src/yarn.lock
- cla-frontend-project-console/edge/security-headers.js
- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-landing-page/src/app/app-routing.module.ts
> Completed auth0 implementation for corporate console ans solved minor issues

- cla-frontend-contributor-console/src/ionic/app/app.component.ts
- cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.html
- cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.ts
- cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
- cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html
- cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.scss
- cla-frontend-corporate-console/src/ionic/services/auth.service.ts
- cla-frontend-project-console/src/ionic/pages/auth/auth.ts
- cla-frontend-project-console/src/ionic/services/auth.service.ts
- cla-landing-page/src/app/core/services/auth.service.ts
- cla-landing-page/src/environments/environment.ts
> Completed Corporate Console Auth0 implementation and solved minor issues

- cla-backend-go/cmd/server.go
- cla-backend-go/init/init.go
- cla-backend-go/main.go
- cla-backend-go/token/token.go
Added new init function for setting global token values.
> [#1510] Added global init function. 

- cla-backend-go/events/repository.go
Fix the next key issue for getting events.
> Fix next key issue for get events

- cla-backend-go/v2/signatures/handlers.go
- Return empty list for signature array
- Return header only for CSV export (no records)
> Signature Return 200 Empty List for Bad Requests

- cla-frontend-contributor-console/edge/security-headers.js
- cla-frontend-corporate-console/edge/security-headers.js
- cla-frontend-project-console/edge/security-headers.js
> Added gravatar to approved image source list

- cla-landing-page/angular.json
> Solved issue of environment not loaded properly

- cla-backend-go/v2/cla_manager/service.go
Added new logic to go-routine.
Refer ticket issue [LFX-2507 ,LFX-2605]
> Added new logic to go-routine

- cla-backend/cla/controllers/github.py
- Added enabled flag, set to True, during the added event for repos
> [#1898] Feature/Add Repository

- cla-backend-go/cla_manager/service.go
- Updated email content sent to cla managers with email of deleted manager
> [#1734] Feature/Email - Delete Manager

- cla-frontend-contributor-console/src/ionic/constants/general.ts
- cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html
- cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.ts
- cla-frontend-contributor-console/src/ionic/layout/cla-header/cla-header.html
- cla-frontend-corporate-console/src/ionic/constant/general.ts
- cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html
- cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.html
- cla-frontend-project-console/src/ionic/constants/general.ts
- cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html
- cla-frontend-project-console/src/ionic/layout/cla-header/cla-header.html
> V1 - Corporate Console - There are duplicate links for Get Help and EasyCLA Documentation

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/github_models.py
- Handled KeyError thrown when getting GH user primary email
> [#LFX2727] Bug/Individual Signature

- cla-backend-go/v2/signatures/handlers.go
Improve error handling and update the status code issue.
> [#1442] api to get cla-group corporate signatures

- cla-backend-go/v2/signatures/handlers.go
Improve error handling and update the status code issue.
> [#1229] Download all Individual Signatures for this CLA Group as CSV

- cla-backend-go/v2/dynamo_events/cla_manager.go
- Refactored goroutine for assigning cla-manager role at project level
> Bug/CLA Manager initial

- cla-backend/cla/models/github_models.py
- Added additional debug output to troubleshoot auth session problem
> Added GitHub Python HUG Debug

- cla-frontend-contributor-console/edge/security-headers.js
- cla-frontend-contributor-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-corporate-console/edge/security-headers.js
- cla-frontend-corporate-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-project-console/edge/security-headers.js
- cla-frontend-project-console/src/config/scripts/prefetch-ssm.js
- infra/get-ssm-parameters.ts
- Added LFX Footer SSM parameters to SSM config
- Added LFX Footer SSM parameters get parameters for infra scripts
- Added LFX Footer to config keys
- Added LFX Footer CDN to script sources
> Added LFX Footer SSM and Edge Config

- cla-backend/cla/controllers/github_application.py
> Resolved GitHubInstallation issue

- cla-frontend-contributor-console/edge/security-headers.js
- cla-frontend-corporate-console/edge/security-headers.js
- cla-frontend-project-console/edge/security-headers.js
> Updated Script Sources for lfx-footer-no-zone.js

- cla-frontend-contributor-console/src/ionic/index.html
- cla-frontend-corporate-console/src/ionic/index.html
- cla-frontend-project-console/src/ionic/index.html
> Updated Product HTML Title

- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
- Skip conflict check if old == new CLA Group
> Added Additional Validation to Update CLA Group

- cla-backend-go/v2/cla_groups/handlers.go
> [#2113] [Regression] - V2 - Project Console - 403 is returned when CLA Group does not exist for child projects

- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
- cla-frontend-project-console/src/ionic/services/cla.service.ts
> V1 - Rebranding - "Your session may have expired or you don't have permissions to see any projects" message is displayed when trying to logout

- cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.scss
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.scss
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.scss
> V1 - Contributor Console - Send button overlaps on X(close) icon

- cla-backend-go/utils/constants.go
- cla-backend-go/v2/company/service.go
- During add organisation introduced company-admin assignment for given user
> [#2071] Feature/Add Company Admin

- cla-backend-go/cmd/server.go
- cla-backend-go/token/token.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
- Added logic to enable and disable the CLA service attribute in the
project service when a given CLA group is created or deleted.
> Added Logic to Set CLA Service on CLA Group Creation

- cla-backend-go/v2/cla_groups/handlers.go
> Resolved debug issue

- cla-backend-go/v2/cla_groups/handlers.go
> [#2137] [Regression] - V2 - Project Console - 500 Internal Server Error is returned while fetching CLA Groups and 403 error.

- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.scss
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
V1 - Project Console - Scroll bar is hidden behind the header until user scroll downs a bit.
[2060](https://app.zenhub.com/workspaces/easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2060)
Signed-off-by: tejas <tejas.adgaonkar@proximabiz.com>
> Scroll bar is hidden behind the header

- cla-backend/cla/utils.py
- Refactored email signoff and eliminated spacing in email format
> [#1721] Feature/Email Format

- cla-backend-go/v2/organization-service/client.go
- Updated org params for companyType with "customer"
> [#2178] Bug/Add-Org

- cla-backend-go/repositories/mock/mock_repository.go
- cla-backend-go/repositories/mock/mock_service.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/project-service/client.go
- Return 200 empty list when no mappins are found
- Resolved Project Service API update issue (auth update)
> Updated List CLA Groups Under Foundation Response

- cla-backend-go/v2/events/handlers.go
> Admin Console OpenColorIO 400-badRequest issue.

- cla-landing-page/src/app/app.component.html
- cla-landing-page/src/app/core/services/auth.service.ts
- cla-landing-page/src/app/core/services/lfx-header.service.ts
> V1 - Rebranding - SignIn button is displayed for logged in user when user navigates back to landing page

- infra/index.ts
> Migrated billing/capacity to pay-per-request for session store table.

- cla-landing-page/src/app/app.component.ts
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/app/config/app-settings.ts
> Updated Developers Learn More Link

- cla-backend/cla/models/github_models.py
> Updated landing page link

- cla-backend-go/approval_list/service.go
- cla-backend-go/approval_list/service_test.go
- Changed email content for approval list requests (Accept/Deny)
> [#2162]Feature/Approval Email

- cla-backend-go/v2/github_activity/handlers.go
- cla-backend/cla/routes.py
make sure we don't return error http codes on regular failures on golang side and if any handle them gracefully on Python side of `/github/activity`
> handle errors more gracefully on /github/activity

- cla-backend/cla/controllers/user.py
- Refactored 'Allow' to Approved
> [#2163]Feature/Request Company Whitelist

- cla-frontend-contributor-console/src/ionic/index.html
- cla-frontend-corporate-console/src/ionic/index.html
- cla-frontend-project-console/src/ionic/index.html
- cla-landing-page/src/index.html
- Updatd the HTML product description text
> Updated Product Description

- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/go.sum
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend-go/v2/dynamo_events/signatures.go
- Add contributor association for newly signed projects (factoring CCLA , ICLA)
> [#1808]Feature/Signature Trigger event

- cla-backend-go/utils/email.go
- cla-backend/cla/utils.py
- Changed from 'EasyCLA support team' to 'The LF Engineering Team' per stakeholder direction
> Updated Email Signoff Line:

- cla-frontend-project-console/src/ionic/assets/img/pdf_file_icon.svg
- cla-frontend-project-console/src/ionic/modals/cla-contract-version-modal/cla-contract-version-modal.html
- cla-frontend-project-console/src/ionic/modals/cla-contract-version-modal/cla-contract-version-modal.scss
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
- cla-frontend-project-console/src/package.json
> Updated PDF Icon on Project Console

- cla-frontend-contributor-console/src/ionic/app/app.scss
- cla-frontend-corporate-console/src/ionic/app/app.scss
- cla-frontend-project-console/src/ionic/app/app.scss
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
> V1 - Project Console - Page keeps loading forever when user does not have access to any projects

- cla-backend-go/v2/cla_manager/service.go
Checking project and org are signed cla first.
Fixed the cyclomatic complexity issue.
> [#2043] V2 - API - Contributor Console - Able to send cla manager request to user without LFID when CLA is already signed

- cla-backend/serverless.yml
> Updated API-GW Domains

- cla-backend/serverless.yml
> Infra - Updated Custom Domain for API GW

- cla-backend/serverless.yml
> Resolved Custom Domain API Type Issue

- cla-backend-go/Makefile
- cla-backend-go/cmd/metrics_report_lambda/main.go
- cla-backend-go/config/config.go
- cla-backend-go/config/ssm.go
- cla-backend-go/go.mod
- cla-backend-go/go.sum
- cla-backend-go/v2/metrics/models.go
- cla-backend-go/v2/metrics/repository.go
- cla-backend/serverless.yml
* adds new fields to totalCountMetrics
* adds a new lambda to send metrics report to sqs queue
PR needs 2 new ssm values (sqs parameter) added to work properly
- `cla-lfx-metrics-report-sqs-region-{stage}`
- `cla-lfx-metrics-report-sqs-url-{stage}`
> [#406] metrics report lambda

- cla-backend/cla/controllers/user.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/tests/unit/data.py
- cla-backend/cla/tests/unit/test_dynamo_models.py
- cla-backend/cla/tests/unit/test_user_event.py
- Add company and company_invite instances for invite_cla_manager controller
- Refactored unit tests for invite manager
> [#2075] Feature/User Company invites

- cla-backend-go/utils/utils.go
- Added hyphen to regex for GH user getting added/updated to approval list
> [#2154] Feature/GH Username Approval List

- cla-backend-go/v2/cla_manager/service.go
> Fixed error handling on invite company admin endpoint.

- cla-backend-go/cmd/metrics_report_lambda/main.go
- cla-backend-go/config/config.go
- cla-backend-go/config/ssm.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/utils/utils_user_auth_lambda.go
- cla-backend-go/utils/utils_user_auth_standalone.go
- cla-backend/serverless.yml
- infra/get-ssm-parameters.ts
- Resolved serverless syntax error
- Updated logging
- Added new configuration parameter for metric report
> Added Configuration Conditional For Metrics Report

- cla-frontend-contributor-console/src/ionic/pages/auth/auth.ts
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.html
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.module.ts
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.ts
- cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
> Gerrit Flow Cleanup - For v1 Use Project ID Instead of Gerrit ID

- cla-backend-go/company/service.go
> [#2184] Feature/Email -> CLA Manager Request

- cla-backend-go/github/github_org.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/v2/repositories/service.go
- infra/get-ssm-parameters.ts
- Updated logic to return all public repos for each organization
> GitHub Organization Response Model Returns All Repos

- cla-backend-go/v2/dynamo_events/signatures.go
- Assign contributor role upon employee acknowledgement
> [#1837] Feature/Sign Emp Acknowldgement

- cla-backend-go/cmd/response_metrics.go
- cla-backend-go/cmd/server.go
- cla-backend-go/config/ssm.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/github_organizations/helpers.go
- cla-backend-go/logging/logger.go
- cla-backend-go/v2/repositories/service.go
- Updated GH organzation and repository query logic - removed duplicate code
- Updated startup logging
- Added elapsed time to responses
> GitHub Organization and Repository Query Logic

- cla-backend-go/v2/company/service.go
- Validated user that adds company(ensure username exists)
> [#2157] Bug/Create Company

- cla-backend-go/repositories/mock/mock_service.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend/cla/models/github_models.py
- cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
- Added check for enabled when testing GH repo status in the project console
- Added additional Github repo enabled logic to update the CLA Group when setting enabled status
> Updated GitHub Repository Enabled Logic

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/utils.py
- Removed html tag for pydocusign Email
- Added utility function for plain footer
> [#2183] Feature/Email Format for Signatory

- cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.html
- cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts
- cla-landing-page/src/app/app.component.scss
Solved below minor issues
[#1065] Corporate Console - Empty table with no data is displayed when all the Pending CLA Manager requests are accepted/declined
[#2124] Description should not be mandatory to create/edit CLA Group
> Solved minor issues

- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/project_service.py
- cla-backend/cla/utils.py
- Added project service module (python)
- Check for project stand alone status
> [#2142] Feature/Check SF Project (Standalone)

- cla-backend-go/.gitignore
- cla-backend-go/Makefile
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend/.gitignore
- Removed company owner API endpoint
- Updated Makefile clean target
- Updated .gitignore rules
> Removed Add Company Owner API

- cla-backend-go/v2/cla_groups/service.go
Implement the total signature count issue.
> [2034] V2 - Project Console - Incorrect signatures count is fetched for cla group

- .circleci/config.yml
- cla-backend-go/.gitignore
- cla-backend-go/Makefile
- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github.py
- cla-backend/cla/utils.py
- Updated comment check logic
- Updated success formatting - added break
- Updated CI/CD for metrics report lambda
> Updated GitHub Comment Logic

- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.html
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.scss
- cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
> Contributor Console - User is not able to search for companies when navigated to console from gerrit

- cla-backend/cla/controllers/gerrit.py
- cla-backend/cla/routes.py
Updated redirect paraemter for gerrit v1 contributor console
> [#2223] Resolved Gerrit Redirect Issue

- cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
> Resolved Corporate Console Trim Issue

- cla-backend-go/go.sum
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend-go/v2/dynamo_events/signatures.go
- Added event handler for adding and deleting CLA Manager
- Removed assignment for endpoints
> Feature/ Add-Delete Dynamo Trigger

- cla-backend-go/v2/cla_groups/handlers.go
Added validation to restrict the foundation project to enroll in cla-group.
> [#2150] V2 - Project Console - Able to enroll foundation for a project level CLA Group

- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- Resolved iteration for assigning CLA permissions upon project cla groups trigger event
> [#2151] Bug/Assign|Remove CLA permissions

- cla-backend-go/company/service.go
Fixed nil pointer panic issue while calling user-service.
> [#2229] Company is being created from Contributor Console.

- cla-backend-go/go.mod
- cla-backend-go/go.sum
- cla-backend-go/template/repository.go
- cla-backend-go/template/service.go
> [#2219]adding aswf v2.1 template id

- cla-backend-go/events/event_data.go
> [#804] API - GH Org/Repos - Audit Log

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Added corporate link in the approval request email sent to CLA Mgr
> [#2225] Feature/Approval Request with corporate link

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/organization-service/client.go
Added new endpoint for contributor console for sending email to cla-manager regarding the new company.
> [#2241] Create a new go lang endpoint for send a email to CLA manager regarding new company.

- cla-backend/cla/models/docusign_models.py
- Updated user account in case user_name attribute is null
> [LFX-2845] Feature/ICLA Sign full name update

- cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
- cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
> V1 - Not able to navigate back to previous page from browser back navigation in V1 consoles

- cla-frontend-contributor-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-contributor-console/src/ionic/app/app.component.ts
- cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.ts
- cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-yesno-modal/cla-company-admin-yesno-modal.ts
- cla-frontend-contributor-console/src/ionic/services/cla.service.ts
> Company is being created from Contributor Console

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
- cla-frontend-contributor-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-corporate-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-project-console/src/config/scripts/prefetch-ssm.js
- cla-frontend-project-console/src/config/webpack.config.js
- cla-frontend-project-console/src/ionic/app/app.component.ts
- infra/get-ssm-parameters.ts
- infra/migrate-ssm-parameters.ts
- release_notes/20190111_initial_release/env_vars.txt
- scripts/credential-updates/cla-credentials.sh
- Renamed from cla-cla-logo-s3-url to cla-logo-url
> Renamed SSM Parameter for CLA Logo URL

- cla-backend-go/v2/cla_groups/service.go
Fixed the project level cla group issue.
> [Blocker] Project level cla group issue.

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/create-cla-group-template.yaml
- cla-backend-go/swagger/common/meta-field.yaml
> Updated Swagger Documentation for Template Generation/Preview

- cla-frontend-project-console/edge/security-headers.js
> Project Console >>View CLA PDF : CLA PDF should get open after user click on PDF icon

- cla-backend-go/go.sum
- cla-backend-go/project/repository.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/dynamo_events/github_repository.go
- cla-backend-go/v2/dynamo_events/service.go
- Resolved repository count by resetting values upon add/delete/modify cla-{stage}-repository table
- Added reset flag for update repo count functions
> [#LFX2818] Bug/Repository Count

- cla-backend-go/config/ssm.go
- infra/get-ssm-parameters.ts
- set test flag to false for DEV to evaluate various templates
> Docraptor Test Mode Update

- cla-backend-go/project/repository.go
- cla-backend-go/v2/dynamo_events/github_repository.go
> Updated Repository Repo Count Database Update Logic

- cla-backend-go/utils/constants.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
- Updated repositories count logic for icla
- Removed employee acknowledgement count while factoring only icla + ccla
> [#LFX2818] Bug/Repositories Count

- cla-backend-go/project/repository.go
- Resolved updating CLA group with no description
> [#LFX2729] Bug/Update CLA Group Description

- cla-backend/cla/models/docusign_models.py
- Resolved bug caused by user with no username getting updated
> [#2260, LFX 2870, LFX 2845] Bug/ICLA generation

- cla-backend-go/signatures/repository.go
Fixed search by user and email.
> [#1387] V1 - Project Console - Search by Manager is not working

- cla-backend-go/v2/repositories/handlers.go
> Added Additional Repository Logging

- cla-backend-go/template/repository.go
- cla-backend-go/template/service.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/template/handlers.go
> Sorted Templates

- cla-backend-go/repositories/repository.go
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/dynamo_events/github_repository.go
- Resolved repo count for no records when getting repositories
> Bug/Dynamo Event GH Repo

- cla-backend/cla/models/docusign_models.py
- Resolved issue due to getting full name (when updating gh user details)
> [LFX-2845] Bug/Docusign Full Name

- cla-backend-go/go.sum
- cla-backend-go/v2/github_organizations/service.go
- cla-backend/cla/config.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
- cla-backend/deploy-staging.sh
> Added GitHub authorization Debugging

- cla-backend-go/v2/dynamo_events/github_repository.go
- Update count to 0 upon repo query failure
> [LFX-2818] Bug/Repo Count

- cla-backend-go/events/mockrepo.go
- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/serverless.yml
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend/serverless.yml
* added_on field added to cla manager list
* filled the missing organization fields inside cla manager list
addressed point 1 and 3 at #1172 
Signed-off-by: makkalot <makkalot@gmail.com>
> [#1172] fixes for cla-manager list endpoint

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/user_service.py
> Added logic to add CLA users from user service

- cla-backend-go/cmd/server.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/github_organizations/service.go
> Added Additional Fields for GitHub organization summary

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/sf-project-summary.yaml
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/project/handlers.go
- Added endpoint to support v2 contributor console to determine which
URL to use for the v2 contributor console
> Added SF Project Summary API Endpoint

- cla-backend-go/v2/project/handlers.go
> Added and Resolved SF Project Summary Response Model

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/user_service.py
- Updated python routine to lookup the user by username (not salesforce ID)
- Renamed user service helper functions - used better names, renamed parameters to be explicit
> Resolved Issue with User Service Username Lookup

- cla-backend/cla/models/docusign_models.py
- Updated GH user with lf_username thats used in searching user
> Bug/Request Corp Signature / New CLA User

- cla-backend-go/swagger/common/sf-project-summary.yaml
- cla-backend-go/v2/project/handlers.go
> Feature/Project Standalone status

- cla-backend-go/v2/dynamo_events/signatures.go
- modified helper func to check for ACL differences
> Bug/Signature ACL modified

- cla-backend/cla/config.py
- cla-backend/cla/controllers/project_cla_group.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/project_service.py
- cla-backend/cla/routes.py
> Updated v2/project/{cla_group_id} response model

- cla-backend/cla/models/docusign_models.py
- Resolved this issue by updating name and email for cla_manager based on the platform_service user
> Bug/ Request Corporate Signature for User with no name and email

- cla-backend-go/v2/cla_manager/handlers.go
- Updated Response code from 202 to 400 for users that dont have LFID
> [#LFX-2225] Feature/ Add CLA Manager Response for No LFID

- cla-backend/cla/config.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/project_service.py
- cla-backend/cla/routes.py
- cla-backend/cla/user_service.py
- Updated config key - resolves token access problem
- Added cache to avoid unnecessary trips to the token service
- Updatd project service gateway API config (resolved wrong config problem)
> Resolved Project Service Token Issue

- cla-backend-go/utils/constants.go
- cla-backend-go/v2/cla_manager/service.go
- Refactored org association(for contributors not associated) due to core services change
> Bug/Org Association

- cla-backend/cla/controllers/company.py
- cla-backend/cla/controllers/signature.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/routes.py
- cla-backend/cla/tests/unit/test_company_event.py
- cla-backend/cla/tests/unit/test_signature_controller.py
- cla-frontend-project-console/package.json
- cla-frontend-project-console/src/package.json
- cla-frontend-project-console/src/yarn.lock
- cla-frontend-project-console/yarn.lock
- Added python logging and type hints
- Updated event log messages
- Resolved ini lib issue, bumped from 1.3.5 to 1.3.7 to address a vulnerability
> Python Logging and Type Hints

- cla-backend-go/v2/github_organizations/service.go
Fix the nill pointer dereference error issue.
>  Blocker GitHub Org auto-enabled cla group name having error.

- cla-backend-go/github/github_installation.go
- cla-backend-go/github_organizations/helpers.go
- Added logic to fetch all repos using github api pagination
> [#2319] Added GitHub List Repos Pagination

- cla-backend-go/repositories/repository.go
Remove builder and added condition and filter.
> Blocker for Manish Github API issue

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Changed status and response code for add CLA Manager to 400
> [#LFX 2225] Feature/Response No LF login

- cla-backend/cla/controllers/signing.py
- cla-backend/cla/routes.py
- cla-backend/cla/tests/unit/test_signature_controller.py
- cla-backend/requirements.txt
handle cancel/finish later for docusign
addresses ~ #1430
> handle cancel/finish later for docusign and return proper html when

- cla-backend-go/project/repository.go
- cla-backend-go/swagger/common/template.yaml
- cla-backend-go/template/repository.go
- Added major and minor versions to the template - set values in the document
- Updated ICLA template address 2 and 3 verticle placement on DocuSign
> Added Template Major/Minor Version + ASWF Template Alignment Updates

- cla-landing-page/src/app/app.component.ts
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/app/config/app-settings.ts
> V2 Contributor is navigated to V1 landing page when clicked "covered" on GitHub

- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_utils.py
- cla-backend/cla/utils.py
> adding project version param to PR sign url

- cla-backend-go/v2/signatures/handlers.go
Fixed to support for project-level permission check.
> [#2326] Staging - After un-enrolling the project from CLA Group, Admin is unable to view the Signatures of un-enrolled project.

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/models/model_interfaces.py
- cla-backend/cla/tests/unit/test_email_approval_list.py
- cla-backend/cla/tests/unit/test_github_models.py
- cla-backend/cla/tests/unit/test_utils.py
- cla-backend/cla/utils.py
- Added additional logging with function name
- Renamed white list to approval list
> Logging Update - Added Additional CCLA Processing Log Messages

- cla-backend/cla/controllers/signing.py
- cla-backend/cla/user_service.py
- Added await for users checking cla-manager role for signed for company
> [LFX 2866] Feature/Redirect After Signing Wait

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/utils.py
- Added additional logging for GH Org checks for CCLA
> Added Additional Logging for GitHub Organization Checks

- cla-backend-go/projects_cla_groups/repository.go
- Discovered and resolved issue when enrolling then unenrolling a
project. Problem was that when the Project Group is deleted followed by
a repo disable, the repo disable triggers a recount of the number of
repos for a given CLA Group. As a result of this activity, the Project
CLA Group table is updated as well. Resolved issue by trapping for
missing table entry.
> [#2337] Resolved Unenroll Issue

- cla-backend/cla/tests/unit/test_user_service.py
- cla-backend/cla/user_service.py
- Resolved issue caused by checking ProjectCLAGroup signed level
- Added unit test
> [LFX-2866] Bug/Docusign Signed Event

- cla-backend/cla/controllers/signing.py
- Updated increment counter that caused timeout issues
> [LFX 2866] Bug/Redirect Docusign Count

- cla-backend/cla/controllers/signing.py
- cla-backend/cla/user_service.py
- Added logging for docusign signed completion event and user_service
> [#LFX-2866] Feature/Logging Docusign Event

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/cla_manager/service.go
- Added additional logging, added debug fields
> Added Additional Logging for ACS API Interactions

- cla-backend-go/approval_list/service.go
- Updated email content for authorized contributors
> [#2162] Updated email content

- cla-backend/cla/models/docusign_models.py
- Fixed None value for CCLA signatory
> [#2296] Bug/Docusign signatory name

- cla-backend/cla/utils.py
> Updated Variable Names - Removed whitlelist

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
> Added log to test version issue

- cla-landing-page/src/app/config/scripts/prefetch-ssm.js
> Added ssm parameters

- cla-backend/cla/models/docusign_models.py
- Handled Unknown name for users with no name attribute with email details
> [#2361] Feature/Name ICLA sign

- cla-backend-go/utils/email.go
- Updated ssm for V2 Corporate Console
> Feature/Corporate URL

- cla-backend-go/events/event_data.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/project/handlers.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/signatures/handlers.go
- cla-backend-go/tests/events_test.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend/cla/models/docusign_models.py
- Handled Unknown name for users with no name attribute with email details
> [#2369] Updated Event Log Data

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/organization-service/client.go
Added new endpoint for company lookup using clear-bit.
> [#2351] Clear-bit Organisation Name Validation

- cla-backend/cla/models/docusign_models.py
- Updated name in the sign template based on company or user
> [#2296]Feature/Sign Name

- cla-backend-go/cmd/server.go
- cla-backend-go/go.sum
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Updated link in email sent to proposed CLA Manager that is redirected accordingly
> [#2352] Bug/Corporate Link in request Admin flow

- cla-backend/cla/utils.py
- Updated SVG image name after adding the images to S3 via terraform
> [#2347] Updated SVG Image Name

- cla-frontend-project-console/src/ionic/constants/general.ts
- cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.html
- cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.ts
> Changes for Gerrit Name regex pattern in v1 Project Console 

- cla-backend-go/swagger/common/add-gerrit-input.yaml
- Resolved regex check for gerrit name on adding gerrit instance
> [#2393, LFX 2987] Bug/Gerrit Name Regex

- cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.ts
> Fix Link in Email to potential CLA Manager v1

- cla-backend-go/v2/cla_manager/service.go
- Added email send to suggested CLA Manager with no LFID
> [#1806] Feature/Send Email to Designed Manager with no LFID

- cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts
- resolved null signatureCreated issue which prevents all signature from being displayed
> Resolved [#2402] v1 Project Console Signature View Issue

- cla-backend-go/cla_manager/service.go
- Updated email content for cla manager list with emails
> [#1734] Feature/Delete CLA Manager

- cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts
> v1 Project Console Signature View Issue

- cla-backend/cla/models/docusign_models.py
- Updated event summary for docusign (CCLA, ICLA)
> [#2275] Feature/Event Log convention

- cla-backend/cla/models/dynamo_models.py
> Python - Added GitHub Organization Table Column for Note

- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
> Added Placeholder for Setting CLA Manager Designee for Enrolled Projects

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- Modified DB trigger for CLA Manager Designee upon Project enrollment
> [#1937] Feature/ CLA Manager Designee on Project enrollment

- cla-backend-go/v2/acs-service/client.go
- Resolved issue when querying object type list with projectID filtered as project|org scope
> [#1937] Bug/Get Object Type Role List

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- Added error message in log message when getting object role user scopes
> [#1937] Feature/Logging for Getting Object role scopes

- cla-backend-go/approval_list/service.go
- Refactored email content from 'Allow List' to 'Approved List'
> [#2163] Feature/Email Content CLA Manager Request

- cla-backend-go/events/models.go
- Fixed response for individual signed event disregarding company details
> [#1237] Bug/Foundation Events - ICLA

- cla-backend-go/tests/utils_regex_test.go
> Updated URL Unit Tests

- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- Improved log handling
- Initialized userscope array that handles existsing scopes for cla-manager-designee role
> [#1987] Bug/CLA Manager Designee Upon enrollment

- cla-backend-go/config/ssm.go
- Resolves issue with using old API DNS name/Old Config
> Resolved CLA API v1 Config Issue in Prod

- cla-backend-go/v2/sign/service.go
- Resolved signatory conflict issue raised upon role assignment
> [#2426] Feature/Signatory assignment

- cla-backend-go/config/ssm.go
- Resolved issue raised by empty config key for v1 api base url
> [#2443] Bug/Sign Coporate signature

- cla-backend-go/swagger/cla.v2.yaml
> Updated Swagger Summaries

- cla-backend-go/company/handlers.go
- cla-backend-go/company/repository.go
- cla-backend-go/company/service.go
- cla-backend-go/swagger/cla.yaml
- cla-backend-go/utils/errors.go
- Added/Updated company with signing entity name endpoint logic
- Updated Swagger Docs
> Added Create Company with Signing Entity Name Endpoint

- cla-backend-go/cmd/functional_tests/org_service/org_service.go
- cla-backend-go/company/handlers.go
- cla-backend-go/company/service.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/signatures.go
- cla-backend-go/v2/organization-service/client.go
- cla-backend-go/v2/sign/service.go
- Added context to additional functions, updated debugging fields
> Added Context to Additional Functions

- cla-backend/cla/models/docusign_models.py
> Updated Event Log Text

- cla-backend-go/tests/utils_conversion_test.go
- cla-backend-go/utils/errors.go
- cla-backend/cla/controllers/github.py
- cla-backend/cla/routes.py
> Added Additional Python Route Logging

- cla-backend-go/package.json
- cla-backend-go/tests/utils_conversion_test.go
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- Resolved missing license header, removed tmp file
- Updated serverless to v2.19.0
> Resolved license header issue

- cla-landing-page/package.json
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.html
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.scss
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/polyfills.ts
- package.json
- yarn.lock
> Landing page changes for V1 to V2 migration

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Added endpoint verifying user role status(cla-manager-designee)
- Updated designee endpoint that used claGroupID rather than foundationSFID
> [#2463] Feature/ CLA Manager Designee check

- cla-backend-go/v2/cla_manager/service.go
> Resolved Function Arg Issue for IsUserorgClient.IsUserHaveRoleScope()

- cla-backend-go/go.sum
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Resolved check for users that have no role found
- Updated response payload for bad requests
> [#2063] Bug/check cla-manager-designee role

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/routes.py
> Resolved Positional Argument Issue

- cla-frontend-contributor-console/edge/security-headers.js
- cla-frontend-corporate-console/edge/security-headers.js
- cla-frontend-project-console/edge/security-headers.js
> v1 PROD Cannot add new company in the Corporate console

- cla-backend/cla/models/docusign_models.py
- Resolves issue of crashing on the docusign form processing
> Added defensive code around docusign form processing

- cla-backend/cla/models/dynamo_models.py
- Added printouts when fetching the latest CLA documents for ICLA or CCLA
> Added CLA Group Document Debug Logic

- cla-backend-go/v2/cla_manager/service.go
- removed second email sent to invited cla manager
- edited email content for invited user with no LFID
> [#2427] Feature/Invite Company Admin Email flow

- cla-backend/cla/controllers/signing.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/routes.py
> Resolved Python Function Parameters Issue

- cla-backend/cla/controllers/signing.py
> Resolved Python Type Arg for Signing Request Corp Signature

- cla-backend-go/company/repository.go
- cla-backend-go/events/event_types.go
- cla-backend-go/github/handlers.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/github_organizations/helpers.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/signatures/handlers.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/tests/events_test.go
- cla-backend-go/users/handlers.go
- cla-backend-go/users/repository.go
- cla-backend-go/utils/responses.go
- cla-backend-go/v2/dynamo_events/github_repository.go
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/service.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend/cla/controllers/signing.py
- cla-backend/cla/tests/unit/test_gh_org_models.py
> Renamed Github to GitHub for logs, events, and constants

- cla-backend/cla/controllers/github.py
> Removed GitHub Secret Failure Email Debug Output

- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_utils.py
- cla-backend/cla/utils.py
- cla-backend/requirements.txt
adding util function to append version to given urls, apply that to covered links in github PR since it was missing
> fix covered pr links version parameter

- cla-backend-go/signatures/service.go
- Edited email content sent to CLA Managers upon approval
> [#1C(10)] Feature/ Approval email content

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.html
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/app/service/landing-page.service.spec.ts
- cla-landing-page/src/app/service/landing-page.service.ts
> Landing page changes for V1 to V2 migration - changes for Project Login & CLA Manager Login links on LFX Header

- cla-backend/cla/controllers/company.py
- cla-backend/cla/controllers/signing.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/routes.py
- Resolved issue in creating a v1 company - issue was related to None
value for signing entity name when creating record
- Updated logging and types for request_corporate_signature
> Resolved [#2479] v1 Create Company Issue

- cla-frontend-project-console/package.json
- cla-frontend-project-console/yarn.lock
> Rolled Back Severless Invalidate Lib - Broke the deployment

- cla-backend/cla/utils.py
- Added # to GitHub redirect sign URL when appending version
> [#2492] Bug/GitHub Redirect

- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/organization-service/client.go
- Leveraged org lookup (org-service) when updating/creating organizatin based on domain
> [#2462] Feature/ Domain lookup

- cla-backend-go/utils/utils_user_auth_lambda.go
- cla-backend-go/utils/utils_user_auth_standalone.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/events/handlers.go
- cla-backend-go/v2/gerrits/handlers.go
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- Updated checks - check both foundation and project SFID against permissions model
- Added context and debug to common permission check functions
> Updated Permissions Checks for Create CLA Group

- cla-backend-go/v2/organization-service/client.go
- Resolved bug caused by 404 on company lookup
> [#2462] Bug/Add org

- cla-backend-go/go.sum
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/signature-acl.yaml
- cla-backend-go/v2/company/service.go
- Added company_id and signatureACL to response
> [#2515] Feature/ Company Project CLA

- cla-backend-go/events/mockrepo.go
- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/events/handlers.go
- Factored in internal companyID based on signing entity name to fetch corresponding events
> [#2515] Feature/ Get Events Signing Entity Name

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Added query param for company ID for company project cla endpoint
> [#2515] Feature/Query for Company ID

- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/github_organizations/handlers.go
> Updated GitHub Organization v2 API Logging

- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Resolved assigning company designee bug that was caused by wrong companyID
> [#2527,#2529] Bug/Invite Company Admin

- cla-backend-go/events/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Resolved events endpoint caused by incorrect filter attribute changed to event_company_id
- Updated company project contributors endpoint with internal companyID as path parameter
> [#2515] Bug/Events and Contributors for Company and Project

- cla-backend-go/tests/utils_test.go
- cla-backend-go/utils/utils.go
- cla-backend-go/v2/signatures/validators.go
- Updated ValidDomain utility method to accept allowWildcards flag - determins if wildcards are allowed or not
- Updated unit tests for domain validation
> Updated Allow List Domain Validation - Allow Wildcards

- cla-backend-go/company/service.go
> Added Auto-Create Signing Entity Name on Query

- cla-backend/cla/models/docusign_models.py
> Added Check Prepare Sigs Logic to Support Signing Entity Name

- .circleci/config.yml
- cla-backend-go/tests/github_v4_test.go
> Resolved Unit Test Issue in Staging/Prod

- .circleci/config.yml
- cla-backend/cla/models/docusign_models.py
> Fixed CI/CD Tests - Updated python check-prepare load company logic

- cla-backend/cla/models/docusign_models.py
- Updated to set/reset the company_id based on if the signing entity
name was correctly specified by the employee
> Updated check_and_prepare_employee_signature logic

- cla-backend-go/signatures/service.go
- Changed email content for approval list emails for contributor
> [#2544] Bug/Update Email approval

- cla-backend/cla/models/docusign_models.py
> Resolved empty list check for python

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/helpers/create_signatures.py
- Updated error response model with more details
- Updated API to return list for get external company id
- Updated test scenario logic
> Updatd Get External ID to return list

- cla-backend/cla/models/docusign_models.py
- Response models now include additional informaiton on the company id, name, signing entity name, and external id
> Updated check_and_prepare_employee_signature error response models

- cla-backend-go/github_organizations/repository.go
- cla-backend-go/v2/github_organizations/service.go
- Resolved issue caused by return of TLF GH orgs
> [#2539] Bug/ Project Multiple GH orgs

- cla-backend-go/cmd/server.go
- cla-backend-go/v2/cla_manager/service.go
- Updated email sent to org admin with appropriate v2 link (corporate console)
- Updated email content sent to user with no LFID in the invite workflow
> [#2427,#2558] Bug/Invite Email Cla Manager

- cla-backend-go/company/service.go
- cla-backend/cla/tests/unit/test_user_service.py
- Auto-create only when searching to sync with SF
> Updated SF Auto-Create Record Logic

- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/cla_manager/service.go
- cla-backend-go/company/handlers.go
- cla-backend-go/company/service.go
- cla-backend-go/signatures/converters.go
- cla-backend-go/signatures/handlers.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.v1.yaml
- cla-backend-go/swagger/common/signature-report.yaml
- cla-backend-go/swagger/common/signature-summary.yaml
- cla-backend-go/swagger/common/signature.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/dynamo_events/cla_manager.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/signatures/converters.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Added new v3 API for CLA Summary Report which returns a quick summary
of CLA based on the query criteria.
- Added includeSigningEntityName query parameter when searching for
organizations in SF - determines if the signed entity names are included
with the response.
> Added CLA Summary Report API - Added Signed Entity Name Filter

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Made signing entity input param optional during company creation
> Feature/Signing Entity

- cla-backend-go/events/event_types.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/signatures.go
> Added additional logging and audit events for key events

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.html
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.scss
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/yarn.lock
> Gray-out/disabled "LFX Version 2" from Production EasyCLA landing page [Only for Production]

- .github/workflows/snyk.yml
> Snyk GitHub Action

- cla-backend-go/project/repository.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/utils/constants.go
- cla-backend-go/utils/errors.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/service.go
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/routes.py
- cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.ts
- Provide signatory name/email in Ui to API for v1
- Improved performance issue with GetCompanyProjectCLA API - added go routines to work faster
- Updated logging and error handling
- Check for duplicate repository records before adding
> Seting Signatory Name/Email in UI - API Performance Improvements

- cla-backend-go/company/service.go
- Resolved issue caused by recursion in the get company by ExternalID endpoint
> [#2579] Bug/Get Company by External ID

- cla-backend-go/repositories/repository.go
- Resolved add GH repository error handling issue
> [#2580] Bug/Add Repository

- cla-backend-go/company/models.go
- cla-backend-go/company/repository.go
- cla-backend-go/company/service.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/service.go
> Resolved [#2586] Cleaned Up Signing Entity Name Query Logic

- cla-backend/cla/models/docusign_models.py
> Rolled Back Check Prepare Signatures Signing Entity Name Logic

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
> Resolved Inactive Landing Page Links

- .github/workflows/snyk.yml
> Added Snyk Config for Golang and Python

- .github/workflows/snyk.yml
> Added Upload Snyk Results to GitHub Code Scanning

- cla-backend-go/projects_cla_groups/models.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/utils/errors.go
> Added Date Created/Modified/Note columns for Project CLA Group Table API

- cla-backend-go/userSubscribeLambda/main.go
> Added SignUp User Handler

- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/user-service/client.go
- Resolved updating cla manager permission for newly enrolled SFProject event
> [#2151] Bug/Enroll Project(CLA Manager permission)

- .github/workflows/snyk.yml
- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/userSubscribeLambda/main.go
- cla-backend-go/utils/constants.go
- cla-backend-go/utils/responses.go
- cla-backend/cla/models/dynamo_models.py
- cla-backend/serverless.yml
> Added Debug for User Subscribe Lambda

- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- Resolved email issue(create cla-manager role) when enrolling salesforce project
> [#2151] Bug/Enroll Project

- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/v2/user-service/client.go
> Resolved #2593 - Autocreate user from auth0

- cla-backend-go/v2/github_organizations/service.go
- Resolved not found response for SF Projects of type Project Group
> [#2611] Bug/Get GH orgs for given Project

- cla-backend-go/repositories/repository.go
- Resolved repository issue caused in the corporate sign flow
> [#2612] Bug/Sign Flow

- cla-backend-go/github_organizations/service.go
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/project-service/client.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/repositories/service.go
- cla-backend-go/v2/sign/service.go
- Added support for projects with 'LF Projects, LLC' parent
> Resolved #2616 - Corporate Console Support for Linux LLC Projects

- cla-backend-go/v2/cla_manager/handlers.go
> Added Additional Logging

- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/organization-service/client.go
- Resolved issue caused when adding standlone projects
- Updated organization-service client functions for logo pointer fields
> [#2611] Bug/Add GH org Standalone Project

- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/project-service/client.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/repositories/service.go
- cla-backend-go/v2/sign/service.go
- Resolved unexpected behaviour when enforcing CLA for repositories and orgs
> Bug/Foundation Name check

- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/project-service/client.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/repositories/service.go
- cla-backend-go/v2/sign/service.go
- Use 'ParentHeirachy' key in salesforce Project when checking Parent Name (LF Projects,LLC && TLF)
> Bug/SF Parent Hierachy

- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/project-service/client.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/repositories/service.go
- cla-backend-go/v2/sign/service.go
Reverts communitybridge/easycla#2625
> Revert "Bug/SF Parent Hierachy"

- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
> Added Search Company to Include Organization Service

- cla-backend-go/repositories/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/github-repository-input.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/repositories/service.go
- Added note as optional input to data model
- Updated repos update reposistory logic to set or append note if provided
> Resolved #2630 Enrolled Repositories Note

- cla-backend/cla/models/docusign_models.py
> Updated Logging - Resolved Logging error

- cla-backend-go/go.sum
- cla-backend-go/v2/sign/service.go
- Resolved CCLA sign issue for standalone projects
> [#2636] Bug/Sign Standalone Project

- cla-backend-go/v2/company/service.go
- Updated GitHubID value with GItHub Username
> [#2642] Feature/Contributors GH details

- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/sign/service.go
- Resolved issue for Parent project sign flow under TLF
> [#2643] Bug/Sign Parent Project Under TLF

- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/sign/service.go
- Reverted fix for [#2643] that caused regression
> Bug/Sign CCLA Revert

- cla-backend-go/v2/organization-service/client.go
- Resolved bug due to organization service update on email parameter
> Bug/Org Service Email

- cla-backend-go/v2/sign/service.go
Resolved use case for Parent Project with no parent set
> [#2643] Bug/Sign CCLA Flow

- cla-backend-go/cmd/server.go
- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/emails/v2_cla_manager_templates_test.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
> [#2649]approved list email text fixes

- cla-backend-go/cmd/server.go
- cla-backend-go/users/repository.go
- cla-backend-go/users/service.go
> Updated new user create logic/logging

- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/organization-service/client.go
- handled scenario when the company name was changed by the organization
service/clearbit on create - EasyCLA company record now honors the
SF/Clearbit name that was assigned
- Updated logging
> Resolved Create Company Issue when Company Name Was Updated By Clearbit

- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/emails/v2_cla_manager_templates_test.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/properties/user-name.yaml
- cla-backend-go/v2/cla_manager/service.go
> Resolved #2427 Email to NonLF User

- cla-backend-go/company/service.go
> Sorted Search Results

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/tests/unit/test_docusign_models.py
signature signed email content changed
> [#2647]signature signed email content changed

- cla-backend-go/v2/cla_manager/service.go
- Resolved contact admin email sending by unmasking email address got from admin scopes listing
> [#2634] Bug/Contact Admin

- cla-backend/cla/utils.py
- Updated Sign off content to 'EasyCLA Support Team'
> [#2673] Feature/Sign off

- cla-backend/cla/config.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/tests/unit/test_docusign_models.py
- cla-backend/cla/utils.py
- cla-backend/serverless.yml
- Updated email content sent to CLA Manager when they are not signatory
> [#2647] Feature/Signatory Email

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/tests/project_helpers_test.go
- cla-backend-go/utils/project_helpers.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/service.go
> Added Support for Bulk Add GitHub Repositories

- cla-backend-go/v2/company/service.go
- Catered for multi level (>3 levels) Projects to handle the ONAP use case
> [#LFX3038] Bug/Get Company Project CLA

- cla-backend-go/Makefile
> Updated Golang Lint Version to v1.37.0

- cla-backend-go/tests/v2_cla_manager_templates_test.go
- cla-backend-go/v2/cla_manager/emails.go
- cla-backend-go/v2/cla_manager/service.go
- Made functions public
- Moved Tests to common test package to access now public functions
- Changed SendEmailToCLAManager to accept a model rather than so many parameters
- Updated logging, added logrus fields, added with error
> Refactoring of CLA Manager Emails

- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/cla_manager/service.go
- cla-backend-go/emails/cla_manager_templates.go
- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- cla-backend-go/v2/cla_manager/service.go
> Feature/Email Content

- cla-backend-go/v2/cla_groups/service.go
- Resolved foundation cla-groups GET endpoint
> Bug/ Get Foundation CLA Groups

- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/v2/dynamo_events/cla_groups_db_handler.go
adding logic into existing event handler.
addresses : #2632
> [#2632]handling cla group name change and reflecting that to cla-%s-projects-cla-groups table

- cla-backend-go/project/repository.go
- cla-backend-go/utils/project_helpers.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/company/service.go
- Resolved GET cla-groups endpoint for SF Project and Company endpoints
> Bug/Get Foundation|Project CLA groups

- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- Updated content sent to company admin in regards the CLA signing
> [#2634] Feature/Contributor Contact Admin email

- cla-backend-go/v2/cla_groups/handlers.go
- Added support for enrolling project in a 3 tier level
> Bug/Enroll Middle Level Project

- cla-backend-go/go.sum
- cla-backend-go/v2/cla_groups/handlers.go
- Resolved issue raised when enrolling a project in 3 tier levels
> [#2697] Bug/Enroll Project

- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- cla-backend-go/v2/cla_manager/emails.go
- cla-backend-go/v2/cla_manager/service.go
- Updated email sent to designee with NO LFID
> [#2703,#2704]Feature/Email Refactor

- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Added logic to ensure the correct filter/query was executing
- Augmented the results to lookup missing github username, name, email, if available - response entries were previously missing some data
> Resolved [#2702] Return ICLA Signatures

- cla-backend-go/cla_manager/service.go
- cla-backend-go/utils/errors.go
- Added logic to prevent the last CLA manager from deleting themself
> Resolved [LFX-3130] Prevent Delete of Last CLA Manager

- cla-backend-go/tests/utils_string_utils_test.go
- cla-backend-go/utils/string_utils.go
- cla-backend-go/v2/acs-service/client.go
- cla-backend-go/v2/cla_manager/emails.go
- Added first and last name to user invite request
- Added utlity method with tests to parse single first/last name string into separate pieces
> Resolved User Invite with Missing First and Last Name

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/tests/unit/test_event.py
- Added cla signatory name to docusing event log entries
> Resolved [#2706] Added User Name to Event Log

- cla-backend-go/v2/cla_manager/service.go
- Resolved email sending to company admin on corporate console
> [#3136] Bug/Corporate Console Admin Email

- cla-backend-go/approval_list/handlers.go
- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/cla_manager/service.go
- cla-backend-go/company/handlers.go
- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/gerrits/handlers.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/project/handlers.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/signatures/handlers.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/common/event.yaml
- cla-backend-go/tests/utils_test.go
- cla-backend-go/utils/utils.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/models.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/dynamo_events/projects_cla_groups.go
- cla-backend-go/v2/dynamo_events/service.go
- Added new events for enroll/unenroll
- Refactored event log to ensure CLA Group and Project ID were distinct. Updated load info logic.
- Added utility method to help differentiate between internal ID's and SFID's
> Resolved 2716 Activity Log for Enroll/Unenroll

- cla-backend-go/events/event_data.go
- cla-backend-go/events/repository.go
- cla-backend-go/repositories/handlers.go
- cla-backend-go/serverless.yml
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/events/handlers.go
- cla-backend/cla/models/dynamo_models.py
- cla-backend/serverless.yml
- Added new key/index for searching events by CLA Group ID
- Updated query logic
- Updated python data models
- Cleaned up event message english
- Updated serverless config
> Search CLA Group Events by CLA Group ID

- cla-backend-go/events/event_data.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/gerrits/handlers.go
- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/repositories/handlers.go
- Updated event log summary messages using a common format
- Use LogEventWithContext when possible, added more logging
> Updated Event Log Message Formatting

- cla-backend-go/approval_list/service.go
- cla-backend-go/cla_manager/service.go
- cla-backend-go/emails/approval_list_templates.go
- cla-backend-go/emails/cla_manager_templates.go
- cla-backend-go/emails/uitls.go
- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- cla-backend-go/v2/cla_manager/emails.go
- cla-backend-go/v2/cla_manager/service.go
- Updated email content sent to Users with no lfid for invite flow
- Refactored utility functions for sending email
- Updated unit tests
> [#2730,#2731] Feature/Corporate Email updates

- cla-backend-go/signatures/service.go
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/tests/unit/test_docusign_models.py
- Updated approval and signatory emails
> [#2733,#2705] Feature/Email content
