linuxfoundation/easycla

cla-backend/package.json
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Update code license statements

LICENSE-code.txt, README.md
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Add license text for keycloak

README.md
=> Fixed build status badge after repo rename.

.github/auto-merge.yml
=> add probot-auto-merge configuration

DEV.md, cla-next/src/routes.js
Fix the broken route on the home page and update dev.md with instructions to start the landing page.
=> fix  broken route and update readme

.circleci/config.yml, cla-backend/package.json, cla-frontend-contributor-console/package.json, cla-frontend-corporate-console/package.json, cla-frontend-project-console/package.json
=> Fixing Yarn Build and Deploy Paths

cla-next/edge/security-headers.js, cla-next/next.config.js
* Added support community bridge and google fonts
=> Updated Security Headers

cla-frontend-project-console/src/ionic/modals/asset-management-modal/asset-management-modal.ts
=> Added Missing Asset Management Modal

cla-frontend-project-console/src/package.json
=> Updated logdash dependency and build staging routine

cla-frontend-project-console/src/package.json
=> Updated lodash lib version to fix deployment

.gitignore, cla-next/package.json, cla-next/src/components/CLAStep.js, cla-next/src/components/Nav.js, cla-next/src/config/cla-env-config.json, cla-next/src/config/scripts/prefetch-ssm.js, cla-next/src/config/scripts/read-local.js, cla-next/src/config/scripts/read-ssm.js, cla-next/src/services/cla.env.utils.js, cla-next/yarn.lock
**Description**
Static landing page needs to point to the correct Project and Corporate console links depending on the environment.
=> CLA-next static landing page dynamically loads url/links

cla-frontend-contributor-console/edge/security-headers.js, cla-frontend-corporate-console/edge/security-headers.js, cla-frontend-project-console/edge/security-headers.js, cla-next/edge/security-headers.js
- Added community bridge fonts
- Resolves some browser font errors
=> Added additional style/font sources

cla-next/src/components/CLAStep.js
Add URL to **add your project** button
=> Add URL to  button

cla-frontend-project-console/src/ionic/modals/asset-management-modal/asset-management-modal.ts
=> fix license

cla-backend/cla/config.py, cla-backend/cla/models/docusign_models.py
=> Added Additional Logging/Debug

cla-backend/cla/config.py
=> Fixed loading CLA_LANDING_PAGE

cla-backend/cla/models/docusign_models.py, cla-frontend-contributor-console/edge/security-headers.js, cla-frontend-corporate-console/edge/security-headers.js, cla-frontend-project-console/edge/security-headers.js, cla-frontend-project-console/src/ionic/index.html
* Added trailing slash to security headers
* removed object-src (reverted change)
* updated logging
=> Security Header Updates

cla-frontend-contributor-console/edge/security-headers.js, cla-frontend-corporate-console/edge/security-headers.js, cla-frontend-project-console/edge/security-headers.js, cla-frontend-project-console/src/ionic/service-worker.js, cla-next/edge/security-headers.js
=> Updated security header - changed cache

cla-backend/cla/models/docusign_models.py
=> Fixed logger statement typo in request_individual_signature.

cla-next/src/components/CLASummary.js, cla-next/src/components/Hero.js, cla-next/src/components/Nav.js, cla-next/src/styles/components/_hero.scss, cla-next/src/styles/components/_nav.scss
=> Text Update and New Nav Update

cla-frontend-corporate-console/src/ionic/index.html, cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.scss, cla-frontend-project-console/src/ionic/index.html, cla-frontend-project-console/src/ionic/pages/login/login.scss
Removed Font-awesome CDN because of the conflicts with the ionic icons
=> PR to fix broken icons

docs/getting-started.md
Carey provided content  and I am sending PR on behalf of her.
=> Updated PG-21

cla-frontend-contributor-console/edge/security-headers.js, cla-frontend-contributor-console/src/ionic/service-worker.js, cla-frontend-corporate-console/edge/security-headers.js, cla-frontend-corporate-console/src/ionic/service-worker.js, cla-frontend-project-console/edge/security-headers.js, cla-frontend-project-console/src/ionic/service-worker.js, cla-next/edge/security-headers.js
- Disable ionic cache as test
- Add data: to allow for font-src
=> Disable Cache and Security Headers

README.md
=> Updated User's Guide Public Link

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py
=> Added additional debugging for check and prepare signatures

cla-backend/cla/models/dynamo_models.py
=> Added defensive code for fetching github_org_whitelist

cla-backend/cla/models/dynamo_models.py
=> Roll back github_or_whitelist

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html
=> Fixed header logo

cla-backend/requirements.txt
=> Upgraded pynamodb lib to address attribute error.

cla-backend/cla/models/dynamo_models.py
=> Disable GH Org Whitelist for now

cla-backend/cla/models/github_models.py
Signed-off-by: Janina Szkut <jszkut@linuxfoundation.org>
=> Comment out log message causing TypeError

cla-backend/cla/controllers/github_application.py, cla-backend/cla/controllers/project.py
- Added additional error handling for GH repo query
- Added additional logging/debug
=> Added Error Handling and Logging

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html, cla-next/src/components/Footer.js
=> update copyright symbol with html entity

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.ts
Given a user who has passed the CLA check performed during a pull request they should be able to view the CLA agreement.
=> Contributor Console for users who pass CLA check

cla-backend/cla/models/docusign_models.py
=> fixed typos in loggers

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.ts
=> Revert CLA UI Changes

cla-backend/cla/utils.py
=> update PR comment text

cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
=> added missing project id in gerrit ccla

cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
=> added logs

cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
=> add missing project iD

cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
=> Remove logging info

cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.scss
Given a user of the project console (project.*.lfcla.com)
When the user clicks the "View Signatures" button associated with a CLA group of a project
Then a loading animation (spinner) until the list of signatures appear
=> Visual Cue: Loading: Project Console: View Signatures

cla-next/src/components/Footer.js, cla-next/src/pages/home.js, cla-next/src/styles/components/_footer.scss
>- Rename title for landing page from  'Home' to 'LF-CLA' ,
>- Add links to footer
=> Add links in Footer of lfcla.com

cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.ts
Given a user of the contributor console (contributor.*.lfcla.com)
When the user has successfully selected a company, and a signature is required
Then a loading animation (spinner) appears until the user can open the document on DocuSign for signature
=> Visual Cue: Loading: Contributor Console: CLA Doc	

cla-backend-go/init/aws.go
* Cleaned up AWS session init - added additional debug
=> AWS Session Init Cleanup

cla-backend/cla/models/github_models.py
Signed-off-by: Janina Szkut <jszkut@linuxfoundation.org>
=> Add additional logging in github models oauth2 redirect function

cla-backend-go/Gopkg.lock, cla-backend-go/health/service.go
* Added additional health check for dynamodb - included status in health response.
=> Added DynamoDB to Health Check

cla-backend/cla/routes.py
=> Added route logging on the python side

cla-backend/cla/routes.py
=> Added more logging - fixed logging

cla-backend/cla/routes.py
=> change hug output validation to png

cla-backend/cla/utils.py
=> Added debug logging for oauth2 session.

cla-backend/cla/routes.py, cla-backend/cla/utils.py
=> separate routes for badge PNGs

cla-backend/cla/routes.py
=> removed signed params

cla-backend/cla/routes.py, cla-backend/cla/salesforce.py
=> Added hug API logging

cla-backend/cla/routes.py
Signed-off-by: Janina Szkut <jszkut@linuxfoundation.org>
=> Disable hug logging middleware for now

cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.html, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.module.ts, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.ts, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.scss, cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.html, cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.scss, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.scss, cla-frontend-project-console/src/ionic/pages/project-details/project-details.html, cla-frontend-project-console/src/ionic/pages/project/project-analytics/project-analytics.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.scss, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
This PR fixes the position of the footer on Mobile and desktop screens. I introduced a wrapper class `page-content` to give the content of the page a minimum height and also push the footer to the bottom of the page.
I also added a loading spinner for visual cues
=> Fix the position of the Footer on Project and Corporate Consoles

cla-backend-go/cmd/server.go, cla-backend-go/github/handlers.go, cla-backend-go/whitelist/service.go, cla-backend/cla/routes.py, cla-backend/requirements.txt
- updated python hug library to address logging issue
- re-enabled hug api logging
- added additional CORS logging for go
- added additional github auth session logging
=> Python HUG Lib Update and Go Logging

cla-backend/cla/routes.py, cla-frontend-contributor-console/src/ionic/app/app.component.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts, cla-frontend-corporate-console/src/ionic/app/app.component.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-corporate-console/src/package-lock.json, cla-frontend-corporate-console/src/package.json, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/ionic/app/app.component.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
* Added UI configuration to support local testing of v1, v2, and v3 local API
* Copied downstream package.json changes to upstream
* Enabled python hug logging, so removed extraneous logging in routes.py
=> Added UI Config for Local Testing

cla-backend-go/cmd/server.go, cla-backend-go/cmd/server_test.go
- use url hostname instead of complete address
- added additional unit tests
- updated logging
=> Resolved CORS Hostname Mismatch Logic

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html
=> Remove Duplicate Company Name in Corporate Console View

cla-backend-go/cmd/server.go, cla-backend-go/docs/doc.go
- Added request/response logging for go
- testing /v3 go swagger documentation
=> Added Go Request Logging

cla-backend-go/company/handlers.go, cla-backend-go/docs/doc.go, cla-backend-go/docs/handlers.go, cla-backend-go/docs/swagger.go, cla-backend-go/github/handlers.go, cla-backend-go/health/handlers.go, cla-backend-go/health/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/whitelist/handlers.go
- Serve up swagger.json on `/v3` path
- Addresses API-Docs for deployment issue
- Grouped/Organized swagger operations to cleanup structure
=> Go Swagger API Docs - Swagger Cleanup/Org

cla-backend/cla/models/github_models.py
=> Fixed python log issue.

docs/EasyCLA-Requirements.md, docs/Get-Access-to-EasyCLA.md
Signed-off-by: Carey Feldstein <cfeldstein@contractor.linuxfoundation.org>
Rewrote the Get-Access-to-EasyCLA.md and added links to other files so the user can find the information they need.
Renamed "What are the EasyCLA Requirements?" file to "EasyCLA Requirements."
=> get access to easycla doc updates

cla-backend-go/cmd/server.go, cla-backend-go/github/handlers.go, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/github_models.py
- Removed v3 global session handler to investigate session mis-match issue
=> Removed v3 global session handler

.circleci/config.yml, cla-backend-go/Makefile, cla-backend-go/cmd/server.go, cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/whitelist/service.go, cla-backend/cla/models/dynamo_models.py, cla-backend/package.json, cla-frontend-corporate-console/src/ionic/modals/github-org-whitelist-modal/github-org-whitelist-modal.html, cla-frontend-corporate-console/src/ionic/modals/github-org-whitelist-modal/github-org-whitelist-modal.ts, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.ts, cla-frontend-corporate-console/src/ionic/models/cla-signature.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/auth.service.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
* Added /v3/signatures endpoint to support GH Org Whitelist API calls
* Renamed build-aws-lambda Makefile target to be consistent
* Added CLA whitelist checks debugging statements on python backend
* Updated serverless npm version
=> GitHub Organization WhiteList Updates

cla-backend/cla/controllers/github.py, cla-backend/cla/models/github_models.py
=> GitHub Organization WhiteList - Activity Checks

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> Fix UI for displaying Organizations

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
**Tasks completed**
>- Assigned a variable to hold  filtered organisations
>- Looped through the items in the array to display the selected organisations
>- Fixed lines showing under organisations.
=> Return an array of filtered organisations

.circleci/config.yml, cla-backend-go/Makefile, cla-backend-go/swagger/cla.yaml, cla-backend-go/template/handlers.go
* Removed duplicate models
* Removed unused response models
* Removed unused parameters
* Added swagger validate to build/CI
=> Go Swagger Cleanup

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
Call `githubOrgWhitelistEnabled` method to return GH Org WL
=> Call githubOrgWhitelistEnabled method to return GH Org WL

cla-backend-go/health/service.go
=> Updated health status string

cla-backend-go/Gopkg.lock, cla-backend-go/Gopkg.toml, cla-backend-go/cmd/server.go, cla-backend-go/template/handlers.go, cla-backend-go/template/repository.go, cla-backend-go/template/service.go, cla-backend/package.json, cla-frontend-project-console/src/ionic/app/app.component.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts, cla-frontend-project-console/src/package-lock.json, cla-frontend-project-console/src/package.json, package.json
- Removed Public Name field
- Aligned fields better
- Removed unused fields
- Added support for testing project console in local mode
- Updated libs for python backend and go backend
- Added logging/debug to troubleshoot PDF generation issue - determined issue was related to AWS DynamoDB read capacity - backend now reports the error
- Added spinner and message to UI when generating PDFs
Resolves #165
=> Apache Style ICLA Template Update

cla-backend/cla/models/github_models.py
- Introduced a new environment variable GH_STATUS_CTX_NAME which specifies the GH status context name. Value is set in the deployment serverless config.
- Default value is communitybridge/cla
- Updated GH status logic to use this value when updating the PR status
Resolves: #166
=> GitHub Checks Uses User's Name for Context

cla-backend-go/template/repository.go, cla-backend/cla/models/docusign_models.py, cla-frontend-contributor-console/src/ionic/app/app.component.ts, cla-frontend-corporate-console/src/ionic/app/app.component.ts, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.html, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.ts, cla-frontend-corporate-console/src/package.json
- Verified project name/entity name details, collapsed verticle spacing
- Added Signatory Email and Title
- Renamed some of the fields
- Adjusted the spacing of input fields
- Removed text from paragraph 8
- UI - Corporate Console - Updated project selection modal to sort and search
- UI - Corporate Console - added USE_LOCAL_MODE support
Resolves: #164
=> Apache CCLA Template Updates

cla-frontend-project-console/src/yarn.lock, scripts/install-frontend.sh
=> Cleaning up the build scripts and adding UI dependency.

cla-frontend-project-console/src/ionic/pages/project/project-analytics/project-analytics.html, cla-frontend-project-console/src/ionic/pages/project/project-analytics/project-analytics.module.ts, cla-frontend-project-console/src/ionic/pages/project/project-analytics/project-analytics.ts, cla-frontend-project-console/src/package.json
- removed angular-svg-round-progressbar and references
=> Removed Incompatible Library/Dependency

cla-frontend-corporate-console/src/ionic/index.html, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.html, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/services/auth.service.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-corporate-console/src/ionic/services/keycloak/keycloak.service.ts, cla-frontend-corporate-console/src/ionic/services/roles.service.ts, cla-frontend-project-console/src/yarn.lock
- Added session checking logic to the corporate console - logs out user when session expires
- Updated CLA services to catch errors and log response - redirect to login page on 401 errors
- Removed errors in the console log
- Fixed lint issues while reviewing components
Resolves: #163
=> Corporate Console Session Timeout

cla-backend-go/template/repository.go, cla-backend/cla/controllers/signing.py, cla-backend/cla/models/docusign_models.py, cla-backend/cla/routes.py, cla-backend/cla/utils.py, scripts/install-frontend.sh
- Cleaned up ICLA header spacing
- Added debug/record printout for CCLA debugging
- Setting Initial CLA Manager Value
=> CCLA Template Update

cla-backend-go/Gopkg.lock, cla-backend-go/cmd/server.go, cla-backend-go/company/handlers.go, cla-backend-go/company/repository.go, cla-backend-go/company/service.go, cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/user/repository_dynamo.go, cla-backend-go/user/service.go
- Added v3 signatures API query by projectID, supports pagination/limit with next key offset
- Fixed lint issues, cleaned up interfaces for services and repositories
- Leverage users and company queries for signatures API call
=> Signatures Backend Query

cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml
- replaced scan with query for database search
- added signature_id in response
- if lastKeyScanned is missing in response, then it means no more records
=> Resolved Signatures Query Issue

cla-backend-go/signatures/repository.go, cla-frontend-project-console/src/ionic/services/cla.service.ts
- resolved pagination issue on queries - needed additional key
=> Signatures Backend Query Pagination

cla-frontend-contributor-console/edge/security-headers.js, cla-frontend-corporate-console/edge/security-headers.js, cla-frontend-project-console/edge/security-headers.js, cla-next/edge/security-headers.js
- Added additional urls for S3
Resolves: #197
=> Embedded PDF CSP Issue

cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.scss, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
- Added "Get access" link for PMs that have no access to projects
Resolves: 187
=> Help for PMs to get access to Projects, even if they have None 

cla-backend-go/docraptor/client.go, cla-backend-go/template/repository.go, cla-backend/cla/controllers/github.py, cla-backend/cla/controllers/github_application.py
- Added logic to prevent endless creation of templates
- Added additional status/debug statements
Resolves: #205
=> Too Many Templates Causes Update Error

cla-backend-go/swagger/cla.yaml, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
- Updated v3 get signatures to handle empty query response by setting resultCount and totalCount
- Updated UI service query logic to handle empty results
=> Corporate CLA Get Signatures UI Error Handling

cla-backend-go/signatures/repository.go, cla-backend-go/users/repository.go, cla-frontend-project-console/src/ionic/assets/_marterial.scss, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- adjusted signatures table title
- adjusted signatures table pagination logic (next/previous)
- removed signatures table page size option
- allow signatures table columns to be dragged/re-ordered
- added GitHub ID to user service response
- increased performance on backend signature table lookup
- added get projects by external id error handling
- added spinner while GitHub Organizations are loaded
Resolves: #162
=> Project Console - Signature View Cleanup

cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.html, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.module.ts, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.ts
- added spinner and note when loading CLA
=> Contributor Console - CLA Loading

cla-backend/cla/models/github_models.py
=> Resolved issue with author_username not being defined.

cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
- Updated company page layout
- Updated project page
- Updated signatures response model
=> Corporate Console UI Updates

docs/Contribute-to-a-GitHub-Company-Project.md, docs/EasyCLA-FAQs.md, docs/Sign-a-CLA-as-an-Individual-Contributor-to-GitHub.md, docs/Sign-a-Corporate-CLA-on-Behalf-of-the-Company.md, docs/Whitelist-Contributors.md, docs/getting-started.md
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Cleaning up documentation

cla-backend/cla/models/docusign_models.py
- Ensure username is set to a value
=> Docusign Invalid Username for ICLA Issue

cla-backend-go/company/handlers.go, cla-backend-go/company/repository.go, cla-backend-go/company/service.go, cla-backend-go/swagger/cla.yaml, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- Added search company name API endpoing
=> Search Company Name

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py
=> Added additional docusign logging

cla-frontend-corporate-console/src/yarn.lock
=> Added yarn lock.

cla-backend-go/company/handlers.go, cla-backend-go/company/projections.go, cla-backend-go/company/repository.go, cla-backend-go/company/service.go, cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml, cla-frontend-corporate-console/src/ionic/app/app.scss, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Added status field in response to specify 'pending' or 'rejected'
- Added get invitelist for individual user for a company
- Fixed SCSS for project name and manager table in the corporate console
=> Updated Pending Invites API

cla-frontend-corporate-console/src/ionic/assets/_marterial.scss
=> Fixed Corporate Console Projects/Managers active table color

cla-backend-go/Gopkg.lock, cla-backend-go/Gopkg.toml, cla-backend/package.json, cla-backend/yarn.lock, package.json, yarn.lock
=> Package/Lib Dependency Updates

cla-backend-go/cmd/server.go, cla-backend-go/company/handlers.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/users/handlers.go, cla-backend-go/users/repository.go, cla-backend-go/users/service.go, cla-backend-go/whitelist/handlers.go, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Get Companies and Invites now queries user then list of companies/invites
- Added User Service query by user name to go backed v3
- Added auth logic to several go backend services
- Updated company user validation logic to actually work this time
=> Get Companies List Optimizations

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
>- Resize PDF icon for CLA groups
=> Resize pdf icon for CLA groups

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/github_models.py, cla-backend/cla/models/model_interfaces.py, cla-backend/cla/utils.py
- Added logging to support troubleshooting of queries and signature lookup
- Added `__str__` for signature model
- Added additional type hint information for python function return values
=> Signature Debugging

.circleci/config.yml, cla-backend/.pylintrc, cla-backend/cla/auth.py, cla-backend/cla/models/github_models.py, cla-backend/cla/utils.py, cla-backend/package.json, cla-backend/yarn.lock
- fixed logging format issues
- addressed a few python lint issues
- added lint step in CI - doesn't fail build for now
- updated serverless versions
=> Resolved Logging Format Issues / Fixed lint issues

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- added error handling for 404/user not found
=> Corporate Console - Resolved User Not Found Error

cla-backend-go/Gopkg.lock, cla-backend-go/auth/authorizer.go, cla-backend-go/company/handlers.go, cla-backend-go/company/service.go, cla-backend-go/health/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/user/repository.go, cla-backend-go/user/repository_dynamo.go, cla-backend-go/users/handlers.go, cla-backend-go/users/repository.go, cla-backend-go/users/service.go, cla-frontend-contributor-console/src/ionic/services/auth.service.ts, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/auth.service.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-project-console/src/ionic/pages/login/login.ts, cla-frontend-project-console/src/ionic/services/auth.service.ts, cla-next/edge/yarn.lock
- User find company -> invite fixes
- Added v3 Add user service endpoint
- Create user if user does not exist on companies page
- Updated error reporting on v3 go authentication module
- Report when sending invitation email
- From login, save user id, user email and user name to local storage
- Updated companies page error handling
- Added logic to clear local storage on logout
=> Corporate Console - User Invite Update

cla-backend/cla/models/dynamo_models.py
=> Added defensive checks for empty query parameters

.circleci/config.yml, cla-backend/cla/test_github_models.py, cla-backend/cla/test_user_models.py
=> Added placeholder unit tests for python user class

cla-frontend-contributor-console/src/ionic/services/http-client.ts, cla-frontend-corporate-console/src/ionic/services/http-client.ts, cla-frontend-project-console/src/ionic/services/http-client.ts
=> Added cache-control to REST API requests

cla-frontend-contributor-console/src/ionic/services/http-client.ts, cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts, cla-frontend-corporate-console/src/ionic/services/http-client.ts, cla-frontend-project-console/src/ionic/pages/auth/auth.ts, cla-frontend-project-console/src/ionic/services/http-client.ts
=> Rolled back cache-control changes

cla-backend/cla/utils.py
- Updated logic to always check CCLA when ICLA fails
Resolves: #252
=> EasyCLA Pass/Fail Check Logic - ICLA not signed fails CCLA check

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
- added sorting to project list
- added sorting to CLA group list
- fixed missing email for corporate signature
- fixed regex issue when searching for companies (only allow alpha numeric, _ and - values)
=> Project Console Sorting and CCLA Signature

cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html
Handle error status when a User's ID does not exist
=> Handle error status when a User's ID does not exist

cla-backend/cla/models/github_models.py
=> Fixed typo in logging statement

cla-backend-go/Gopkg.lock
=> Updated golang lib lockfile

cla-backend/cla/controllers/github.py
- Added logic to look for the github organization in several places
=> Extract github organization from installation event updates

cla-backend/cla/controllers/github.py, cla-backend/cla/test_github_controller.py, cla-backend/cla/test_user_models.py
=> Added addition GitHub Org Debug and Unit Tests

cla-backend-go/users/repository.go, cla-backend/cla/models/docusign_models.py
- Updated column name to match => `username` to `user_name`
=> Fixed CreateUser column name

cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-confirm/cla-employee-company-confirm.html, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-confirm/cla-employee-company-confirm.ts
- Updated spinner start/stop logic to prevent it from endlessly spinning
- Added error message to UI when an error occurs
- Added help desk link if error occurs
=> Contributor Console Erorr Handling

cla-backend/cla/controllers/gerrit.py, cla-backend/cla/test_gerrits_models.py, cla-backend/requirements.txt
- Rolled back pynamodb lib version to address issue
- Added additional debug output
=> Resolve Python DynamoDB Scan Error

cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts
- Updated logic to show signature type - now indicates employee
=> Project Console - Signature Table Type Update

cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.html, cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
- added repository add all feature
Resolves: #210
=> Project Console - GitHub Repository Add All

cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.html, cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
- Project Console - fix added/remove repository - only adds/removes for that organization
- Project Console - add/remove now sorts by organization
- Corporate Console - Sort domain, email and github whitelist
Resolves: #210
=> Project Console - GitHub Repository Add/Remove Fix

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> Corporate Console - GitHub Organization Sorting

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html
=> CFF Contributors Note

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts
=> CFF Contributors Note Update

DEV.md, cla-backend-go/Gopkg.lock, cla-backend/cla/controllers/github.py, cla-backend/cla/controllers/project.py, cla-backend/cla/controllers/signature.py, cla-backend/cla/controllers/user.py, cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/github_models.py, cla-backend/cla/models/model_interfaces.py, cla-backend/cla/test_user_models.py, cla-backend/package.json, cla-backend/yarn.lock
- Updated method signatures to return None or a list instead of 0 or 1 user record
- Allows signature processing logic to evaluate each matching user
- May have multiple user records with the same github id, github user, username or email
- Updated unit tests and existing logic to handle multiple users returned
=> Search Users Finds Multiple Matches

cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.html, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.module.ts, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
- Corporate Console - added sort to employee acknowledgements
- Corporate Console - prevented whitelist duplicates
Resolves: #287
Resolves: #288
=> Prevent Whitelist Duplicates and Sort Employee Acks

cla-backend-go/signatures/repository.go
=> Sorted GitHub Orgs from Corporate Signature Query

cla-backend/cla/salesforce.py
=> Added error handling for legacy salesforce get projects query

cla-backend/cla/models/github_models.py
Added logic to update the comment if and only if the PR has a CLA Not
Signed comment and the status of the CLA check is updated to Signed.
Resolves: #269
=> EasyCLA PR Comment Logic

.github/ISSUE_TEMPLATE/docs_update.md, .github/ISSUE_TEMPLATE/feature_request.md
Added GitHub Documentation Update Template
- Added new template for documentation
- Fixed feature request template typo
=> Added GitHub Documentation Update Template

cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.ts, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.html
- Updated text for the contributor affiliation
- Added filter for empty company names
Resolves: #300
=> Contributor Console - Affiliation Failure Feedback Update

docs/cla-troubleshooting.md, docs/contributors.md
I have updated the following files as per the ticket.
- contributors.md - Added text from line 15
- cla-troubleshooting.md - updated line 4
=> Doc update 306

cla-backend/package.json, cla-frontend-project-console/src/ionic/modals/cla-contract-version-modal/cla-contract-version-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- Fixed CCLA PDF link
- Added help page when PDF document is missing
Resolves: #312
=> Project Console - CCLA Template Link Broken

cla-backend/cla/utils.py
- Updated help text when one or more comitters fail the check
Resolves: #313
=> Add links to JIRA service desk product support for further EasyCLA help

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/routes.py, cla-backend/cla/test_user_models.py, cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.ts
- Added case insensitive search/compare for whitelists
- Added github username lookup when only the id is available
- Added github id lookup when only the username is available
- Resolves issue when github_username is not available which by-passed the GH whitelist checks
Resolves: #233
=> Whitelist Checks

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/github_models.py, cla-backend/cla/test_user_models.py, cla-backend/cla/test_utils.py, cla-backend/cla/utils.py
- Added logic to add GitHub id and username when available
- Refactored to use common utility methods
- Added unit tests
=> User Record - Add GitHub Details

cla-backend/cla/models/dynamo_models.py
- Updated API call - resolved broken reference
=> Fix GitHub Org Lookup

cla-backend-go/Makefile, cla-backend/cla/models/docusign_models.py
=> Added Additional Debug for Sending Signing Request

cla-backend/cla/models/docusign_models.py
=> Added Authority Check for Signing CLA Document and Sending Email

cla-backend/cla/models/docusign_models.py
=> Testing Docusign Email Recipient

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
- Added spinner for loading content
- Added LFID/GHID for Employee Acknowledgements
=> Contributor Console - UX Updates

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
- Loaded company name from the company response, previously used CCLA signature response (some companies may not have CCLAs yet).
=> Fix Missing Company Name

cla-backend-go/Makefile, cla-backend-go/config/ssm.go, cla-backend-go/init/aws.go, cla-backend-go/signatures/repository.go, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Added pagination support on the backend and frontend
- Loop until limit is met or no more records
- Fixes issue when retrieving signatures for Project/Company/User when there are a lot of records
- Includes Corporate Console Name Fix
- Cleaned up AWS SSM property loading
=> Resolves Issue when CCLA for a Project/Company is not retrieved

cla-backend-go/init/aws.go, cla-backend/package.json
=> Removed AWS Profile environment variable.

cla-backend/cla/models/docusign_models.py, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.ts, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.html, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.html, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts, cla-frontend-contributor-console/src/ionic/services/http-client.ts, cla-frontend-contributor-console/src/package.json, cla-frontend-corporate-console/src/config/scripts/prefetch-ssm.js, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
- Update the Contributor Console Troubleshooting Page - added GH Orgs help
- Resolved issue when CLA Manager's Name was not defined causing a Docusign service error
- Contributor Console - Allow Search filter for the company name
=> UI Enhancements

cla-frontend-corporate-console/src/ionic/app/app.component.ts, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/logout-page/logout-page.html, cla-frontend-corporate-console/src/ionic/pages/logout-page/logout-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/logout-page/logout-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/auth.service.ts, cla-frontend-corporate-console/src/package.json, cla-frontend-project-console/src/config/scripts/prefetch-ssm.js, cla-frontend-project-console/src/ionic/app/app.component.ts, cla-frontend-project-console/src/ionic/pages/login/login.html, cla-frontend-project-console/src/ionic/pages/login/login.ts, cla-frontend-project-console/src/ionic/pages/logout-page/logout-page.html, cla-frontend-project-console/src/ionic/pages/logout-page/logout-page.module.ts, cla-frontend-project-console/src/ionic/pages/logout-page/logout-page.ts, cla-frontend-project-console/src/ionic/services/auth.service.ts
- Added auth0 logout when user logs out
- Added note in Corporate Console when CLA Manager list is restricted
=> Added Auth0 Logout

cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/users/repository.go, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.module.ts, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts
- Updated backend signature service to return the CLA manager details for the project/company
- Updated UI to show the existing CLA managers and provide input form for unlisted CLA manager
=> Contributor Console - Request CLA Manager to Whitelist #348

cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts
Error Handling / Validation
Emails Sent
CCLA manager options
=> Feature/request company UI Changes

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
- Updated CLA manager list text
=> Changed CLA Manager List text

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/utils.py, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts
- Updated text for CLA Manager modal whitelist
- Fixed company name
- Added type information for python service function returns.
=> CLA Manager Whitelist Modal Updates

cla-backend/package.json, cla-backend/yarn.lock, cla-frontend-contributor-console/package.json, cla-frontend-contributor-console/yarn.lock, cla-frontend-corporate-console/package.json, cla-frontend-corporate-console/yarn.lock, cla-frontend-project-console/package.json, cla-frontend-project-console/yarn.lock, cla-next/package.json, cla-next/yarn.lock
=> Added Serverless Plugin Dependencies

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-contributor-console/src/ionic/theme/footer.scss, cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-corporate-console/src/ionic/theme/footer.scss, cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-project-console/src/ionic/theme/footer.scss, cla-next/src/components/Nav.js
Add Help Desk links on *.lfcla.com
=> Add Help Desk links on *.lfcla.com

cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.html, cla-frontend-project-console/src/ionic/pages/login/login.html, cla-next/src/components/CLAStep.js
Update *.lfcla.com console landing pages 
Issue : https://github.com/communitybridge/easycla/issues/366
=> Update *.lfcla.com console landing pages

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py
=> Added test/evaluation for manager user_name is None

cla-frontend-corporate-console/edge/security-headers.js
=> Added localhost for testing locally with cors security

cla-backend/cla/models/dynamo_models.py, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
- Updated database model to support OPNFV member documents
- Added UX updates to support member documents, non-member documents and individual (3 CLAs)
=> Added Support for OPNFV

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
=> Hide GitHub for OPENFV Projects

cla-backend-go/Gopkg.lock, cla-backend-go/cmd/server.go, cla-backend-go/onboard/handlers.go, cla-backend-go/onboard/repository.go, cla-backend-go/onboard/service.go, cla-backend-go/swagger/cla.yaml, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Updated swagger
- Added Create/Get/Delete API, handler, service and repo logic
- Added Corporate console client helper functions
=> Create CLA Manager Request API to handle Corporate Console request form

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
=> Access Page Help Link Updates and Removed Duplicate Get Help Links

cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml, cla-backend/cla/models/dynamo_models.py
Added Signature Reference Name and Signature Reference Name Lower column support
=> Added Signature Reference Name and Signature Reference Name Lower

README.md, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
=> Updated getting started link

cla-backend/cla/models/docusign_models.py
=> Added check for null template/document.

cla-backend-go/Gopkg.lock, cla-backend/serverless.yml, cla-frontend-contributor-console/src/ionic/app/app.component.ts, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.html, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.scss, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.ts, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts
Show Individual and Corporate buttons on Corporate Consoles
Show error message when trying to open individual CLA
#405
=> Contributor Console #405

cla-backend-go/Gopkg.lock, cla-backend-go/Makefile, cla-backend-go/signatures/repository.go, cla-backend-go/users/repository.go
Updated the username search to allow for signatures to be populated via lf_username or github user id
Signed-off-by: asithade <asithade@gmail.com>
=> Fix for Github User Signatures #415

.circleci/config.yml, cla-backend-go/Gopkg.lock, cla-backend-go/auth/auth0.go, cla-backend-go/cmd/server.go, cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/onboard/handlers.go, cla-backend-go/onboard/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/utils/events.go, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
=> Added v3 messaging service.

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
Removed loop and added a search method for the initial check for OPNFV
Signed-off-by: asithade <asithade@gmail.com>
=> Removed Loop & Added Search Method

cla-backend/package.json, cla-backend/yarn.lock
=> Added serverless-finch plugin for deployments

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss
=> Cla corporate update

.circleci/config.yml
=> Updating the UX Deploy CI Config.

.circleci/config.yml
=> Working on backend deploy scripts.

.circleci/config.yml
=> Working on getting the backend deployment paths setup correctly.

.circleci/config.yml
=> Tested backend deployment

.circleci/config.yml
=> Updated directory path for backend deployment.

.circleci/config.yml
=> Fixed directory typo in backend deployment CI/CD config script.

cla-backend/serverless.yml
=> Allow lambda backend to publish to SNS topic.

tests/rest/test_project_management_console.tavern.yaml
- Updated test with SF project ID changes for `project_member_documents` attribute.
- Updated status code for `/v3/template` endpoint.
=> Updated tests with SFID endpoint/status code changes

infra/README.md, infra/index.ts
- Added support for DynamoDB external project id column.
- Updated readme notes for infra deployment.
=> Infrastructure Deployment Updates

cla-frontend-corporate-console/src/ionic/modals/cla-manager-onboarding/cla-manager-onboarding.html, cla-frontend-corporate-console/src/ionic/modals/cla-manager-onboarding/cla-manager-onboarding.scss, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html
=> Update CLA on-boarding text

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/version/handlers.go, infra/README.md, package-lock.json, package.json
- Added version endpoint at /v3/ops/version which returns version, commit, builddate and branch details
- Updated serverless version to 1.60.4
- Updated infra README.
Resolves: #416 backend side
=> Added Version API Endpoint

cla-frontend-corporate-console/src/ionic/modals/cla-manager-onboarding/cla-manager-onboarding.html, cla-frontend-corporate-console/src/ionic/modals/cla-manager-onboarding/cla-manager-onboarding.scss, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html
=> Add submit button and notice text

dev.md
=> Updated developer build/run documention

infra/index.ts
- updated the hashKey and rangeKey
=> Updated reference-signature-search-index

cla-backend/cla/models/dynamo_models.py
- Fixed Attribute 'user_external_id' cannot be None
=> User External ID Fix

cla-backend-go/config/ssm.go, cla-backend-go/users/handlers.go, cla-backend-go/users/models.go, cla-backend-go/users/repository.go
- updated user service search error handling - now trap for missing params and return appropriate error response/message
- moved models to separate file
- cleaned up output
=> Updated User Service Error Handling

README.md
=> Restored CI/CD badge on the readme.

.circleci/config.yml
=> Updated CircleCI release/tag regex to allow patch tags

.circleci/config.yml, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/tests/unit/test_email_whitelist.py
- Added unit tests to test for valid and invalid emails against a signature
- Refactored functionality testing user emails against whitelists
Resolves #484
=> Fix Domain Regex

cla-backend-go/health/service.go
- Added query for each table in health and status checks
=> Added Additional Health and Status Checks

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py
- Updated get signatures by project to use dynamodb query_filter parameters
- Added employee signature query (used by GitHub and Gerrit API queries)
- Updated CCLA query to ensure that returned results were signed and approved
- Fixes issue 232 since we ensure ICLA results are signed and approved
Resolves: #232
=> Signature Query Cleanup

cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml
- Added API endpoint to report signature metrics
=> Added Signature Metrics Endpoint

cla-backend/cla/models/dynamo_models.py
- Refactored filter condition to handle None Type cases during signatures search
- Generalised filter attributes for any Pynamo Models instance
This resolves #504
=> Project Console: View Companies

cla-backend/cla/tests/unit/test_email_whitelist.py
- Added test to check email whitelisting for a specific case
This resolves #305
=> Gerrit Project Whitelisting

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/tests/unit/test_email_whitelist.py
- Fixed issue that raises on domain and email whitelist fail
This resolves 516
=> Signature Whitelist

cla-frontend-corporate-console/src/ionic/components/get-help/get-help.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.scss, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
=> Add CCLA Pending Requests

infra/index.ts
=> Updated Billing Mode and Read/Write Capacity for DynamoDB tables

.circleci/config.yml
- Updated node version logic to work with various build workflows
=> Resolve Node Version Issues

.circleci/config.yml
- Updated CircleCI Release Tag Regex to use semver (with optional leading 'v' character)
=> Updated CircleCI Release Tag Regex

.circleci/config.yml
- Updated CircleCI Release Tag Regex to use semver (with optional leading 'v' character)
=> Updated CircleCI Release Tag Regex (#523)

.circleci/config.yml
=> Release Tag RegEx Update

cla-backend-go/cmd/server.go, cla-backend-go/company/repository.go, cla-backend-go/metrics/handlers.go, cla-backend-go/metrics/service.go, cla-backend-go/project/repository.go, cla-backend-go/repositories/repository.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/users/repository.go, package.json
- Resolved merge conflicts for metrics API integration
- Added Metrics API
=> Resolved merge conflicts for metrics API integration

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
=> Fix Create /  Join Company Action

cla-backend/cla/models/github_models.py, cla-backend/cla/tests/unit/test_github.py, cla-backend/cla/tests/unit/test_github_models.py, cla-backend/cla/tests/unit/test_utils.py, cla-backend/cla/utils.py
- Added utility function checking whitelisting of a non signed user
- Refactored utility function assembling comment( body and badge)
- Added unit tests
Resolves: #309
=> Alternate Github Badge: Confirm Affiliation

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
=> Add CCLA Status and # of Pending requests

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.ts
=> Removed CFF Banner in the Contributor Console

cla-backend/cla/tests/unit/test_github.py, cla-backend/cla/utils.py
=> Updated Comment Message for missing User ID

.circleci/config.yml, cla-frontend-contributor-console/serverless.yml, cla-frontend-corporate-console/serverless.yml, cla-frontend-project-console/serverless.yml
=> Added Invalidate Cloudfront Distribution Step

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
=> CCLA Manager can see all projects and whitelist all projects associated with their company 

cla-backend-go/users/handlers.go
- Removed restriction where the current logged in user is the only one allowed to add/edit/delete/search him/herself.
=> Users API Permission Update

cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.html, cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
**When User is not a CLA Manager**
**When User is a CLA Manager**
**List of CLA Managers for a Project**
**List of CLA Managers when a user is not an admin**
**List of CLA Managers when a user is a cla manager**
resolves issue #385 
=> Allow CLA managers to manage whitelists and Non CLA Mangers to View whitelist

cla-backend/cla/controllers/company.py, cla-backend/cla/controllers/event.py, cla-backend/cla/controllers/project.py, cla-backend/cla/controllers/signature.py, cla-backend/cla/controllers/user.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/event_types.py, cla-backend/cla/tests/unit/conftest.py, cla-backend/cla/tests/unit/data.py, cla-backend/cla/tests/unit/test_company_event.py, cla-backend/cla/tests/unit/test_project_event.py, cla-backend/cla/tests/unit/test_signature_event.py, cla-backend/cla/tests/unit/test_user_event.py, cla-backend/cla/utils.py
- Add audit-trail decorator
- Added unit test cases for events
=> EasyCLA Audit Service

cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-yesno-modal/cla-company-admin-yesno-modal.html
=> Change text in Verify modal to describe a CLA Mamager

cla-backend-go/signatures/repository.go
- Added approved and signed filter to project signatures function
Resolves: #543
=> Project Console:View Signatures

.circleci/config.yml
=> Added v3 health status attribute check during CI workflow

cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.ts
Update Contributor console modal when a company is found but hasn't signed CCLA
>- Add Name of project
resolves #562
=> Update Contributor console modal when company found but hasn't signed CCLA

cla-backend/serverless.yml
- resolved typo with DynamoDB permission of index company-id-project-id-index
=> Fixed Index Permission

cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- Removed duplicate link
- Updated View Companies Link
- Fixed View Companies Link Title
=> Project Console - Updated View Companies

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
=> Remove static company_id from pending request

cla-frontend-project-console/src/ionic/app/app.component.ts, cla-frontend-project-console/src/ionic/pages/login/login.html
=> Fix "Sign Out" and "Sign In" menu options on Project Console

cla-backend-go/company/handlers.go, cla-backend-go/company/repository.go, cla-backend-go/company/service.go, cla-backend-go/project/handlers.go, cla-backend-go/project/repository.go, cla-backend-go/project/service.go, cla-backend-go/signatures/dbmodels.go, cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml, tests/rest/test_v3_metrics_api.tavern.yaml
- Updated Signature Metrics to return CLA Manager Counts
- Updated Project metrics to return project and project manager counts
- Updated Company metrics to return companies and company manager counts
- Updated Swagger and data models
- Added functional test
Resolves #616
=> Updated Metrics Endpoints

cla-backend/cla/models/docusign_models.py
- Added check for valid parameters
- Use provided project_id
=> Added Defensive Checks for request_corporate_signature

cla-backend-go/users/handlers.go, cla-backend-go/users/repository.go, tests/rest/test_v3_users_api.tavern.yaml
=> Added v1 Users Functional Tests

.circleci/config.yml, cla-backend-go/v2/metrics/handlers.go, dev.md
- Updated path/binary configuration
- Updated build documentation
=> CircleCI Build/Deploy Updates for V2

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/docs/doc.go, cla-backend-go/v2/docs/handlers.go, cla-backend-go/v2/docs/swagger.go, cla-backend-go/v2/project/handlers.go
- Added Swagger Examples
- Added docs endpoint for v2
=> Added EasyCLA v2 CLA Group and API-Docs Endpoint

cla-backend-go/Gopkg.lock, cla-backend-go/logging/logger.go, cla-backend-go/metrics/service.go, cla-backend-go/onboard/handlers.go, cla-backend-go/repositories/repository.go, cla-backend-go/users/handlers.go, cla-backend-go/utils/email.go
Removing check of UserID in getUserByUsername api.
Using log library of project instead of 3rd party
=> Removing check of UserID in getUserByUsername api.

.circleci/config.yml, cla-backend-go/serverless.yml, cla-backend/serverless.yml, infra/index.ts
=> Updated infra for metrics lambda

cla-backend-go/events/mockrepo.go, cla-backend-go/events/models.go, cla-backend-go/events/repository.go, cla-backend-go/events/service.go, cla-backend-go/signatures/handlers.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/whitelist/handlers.go, cla-backend-go/whitelist/repository.go, cla-backend/cla/controllers/user.py, cla-backend/cla/tests/unit/test_user_event.py, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts
- Service that handles API for handling whitelist requests
- Invoke service from the employee request modal
Resolves: #589
=> Contributor Console-WL Request API call

cla-backend-go/auth/auth0.go, cla-backend-go/auth/authorizer.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/user/repository_dynamo.go, cla-backend-go/users/handlers.go
if user not found then GetUserAndProfilesByLFID will return error
using info in authorization token for creating user.
=> using user auth-token info for creating new user

cla-backend/serverless.yml
- Fixed indent typo, added description
=> Adjusted Metrics Event Trigger

cla-backend/cla/controllers/company.py, cla-backend/cla/controllers/user.py, cla-backend/cla/tests/unit/test_company_event.py, cla-backend/cla/tests/unit/test_user_event.py
- Refactored events handling to cater for Events user_id change to events_user_id
Resolves #644
=> Fix Requesting CLA signature(Contributor console)

cla-backend-go/template/service.go
- Sets right content type for template pdf uploads(application/pdf)
Resolves: #676
=> Fix Template PDF Upload

.circleci/config.yml, scripts/deploy-frontend.sh
=> Rolled back Node 12 Serverless Deployment

cla-backend-go/project/repository.go, cla-backend-go/template/repository.go
- Setting the CCLA/ICLA/Member Document as empty list (which allows the template selection flow to work).
- Added debug to the template repo update logic
=> Updated Create CLA Group Logic

scripts/deploy-frontend.sh
- Switch node versions in deploy script
=> Fixing frontend deploy

scripts/deploy-frontend.sh
=> Allow nvm to work within a script

cla-backend-go/project/repository.go
=> Fixed response model for CLA Group/project external ID search

scripts/deploy-frontend.sh
=> Added load nvm.sh to support node version switch for frontend deployment

.circleci/config.yml, cla-backend-go/swagger/cla.v2.yaml, infra/index.ts
- Moved deployment routines to circle CI config (away from separate script)
- Fixed infra index update script (needed to declare the column)
- Updated the security context for the LFX v2 APIs
=> Deployment Updates + LFX API Fix

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/event_types.py, cla-backend/cla/utils.py
- user is associated with company
- employee signature is created
- emplpyee signature disapproved
Fixes #571
=> Adding audit events

cla-backend-go/Makefile, cla-backend-go/cmd/server.go, cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/github/handlers.go, cla-backend-go/init/aws.go, cla-backend-go/init/init.go, cla-backend-go/serverless.yml, cla-backend-go/swagger/cla.yaml, cla-backend/serverless.yml, cla-frontend-project-console/edge/security-headers.js, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/services/cla.service.ts, tests/rest/test_v3_github_api.tavern.yaml
- Added authenticated endpoint to check if the github org exists (using token)
- Resolved issue where Lambda deployed in us-east-2 (v2 LFX integration) can connect to us-east-1 dynamodb instances.
- Added new SSM parameter for the GitHub token
- Added config/enviroument for DynamoDB region
- Added functional test
=> GitHub Org Check and DynamoDB Region Update

cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- completed GIT organisation validation
=> Bugfix/test GitHub organization

cla-backend-go/serverless.yml
=> Adjusted API v2 SSM Permissions

cla-backend-go/serverless.yml
=> Fixed SSM Permissions Again (typo)

cla-backend/cla/models/github_models.py
- Added logging and handled exception for creating PR status
Resolves: #682
=> Feature/Log PR Status

cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
=> Optimized the service calls for CLA project and github organisations

tests/rest/test_project_management_console.tavern.yaml, tests/rest/test_v3_project_api.tavern.yaml, tests/rest/test_v3_users_api.tavern.yaml
- Fixed failing functional tests
Co-authored-by: David Deal <dealako@gmail.com>
=> Feature/ Refactor Functional Testing(API) (#691)

cla-backend/cla/models/docusign_models.py
- Reviewed/Refactored the CLA Manager = CLA Signatory workflow
- Reviewed/Refactored the CLA Manager -> Email CLA Signatory workflow
- Renamed variables to use current personas/roles
- Updated logic to not fail on no signature (initial signup)
Resolves #637
=> Reviewed and Updated the Sign Corporate Signing Workflow

infra/index.ts
=> Added secondary index.

cla-frontend-project-console/src/ionic/components/sort-table/sort-table.html, cla-frontend-project-console/src/ionic/components/sort-table/sort-table.module.ts, cla-frontend-project-console/src/ionic/components/sort-table/sort-table.scss, cla-frontend-project-console/src/ionic/components/sort-table/sort-table.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.module.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts
- Implemented sort table in cla contract companies signatures
=> - Created sort table component

cla-backend-go/template/models.go, cla-backend-go/template/repository.go, cla-backend-go/template/service.go
- Fixes issue of generation of templated based on claGroup type(CCLA/ICLA)
=> Bug/Template Generation

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss
=> UI changes on company page.

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts
=> Corporate Console: Submit button in "Select Company" Popup is not available as per the note

cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html
=> Both CCLA and ICLA templates are generated when CLA group has only ICLA or only CCLA type selected

cla-frontend-project-console/src/ionic/components/pdf-viewer/pdf-viewer.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
=> Upgrade get project by external ID to v3

cla-backend/cla/controllers/project.py
- Filter projects in the (ccla)signing process
=> Bug/Sign Only CCLA projects

cla-frontend-project-console/src/ionic/components/pdf-viewer/pdf-viewer.ts, cla-frontend-project-console/src/ionic/components/sort-table/sort-table.html, cla-frontend-project-console/src/ionic/components/sort-table/sort-table.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.module.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.html, cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- fixed error message issues while adding GitHub Organization
=> - signature and companies table sorting fixed

cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.scss, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.ts
=> Company name overlaps with Cancel and Send button when company has not signed CLA 

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
=> New user is not able to see added companies in Corporate Console

cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.scss
=> User(Contributor) has to scroll down to view all options in the Contributor Console

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts
=> Notification Sent message is not displayed when clicked on Request option while creating duplicate company 

cla-backend-go/Gopkg.lock, cla-backend-go/company/repository.go, cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/utils/utils.go, cla-backend-go/utils/utils_test.go
- Load SSM values concurrently on startup
- Support parsing of date/time string in multiple formats - resolves Company Whitelist Request time parse error
- Added time/parse unit tests
=> Resolved Date/Time Parse Error + Sped Up SSM Load

cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.html, cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.ts
=> UI hangs with spinning icon when project is entered and enter button is hit while trying to sign cla.

cla-backend-go/Gopkg.lock, cla-backend-go/cmd/server.go, cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/github/client.go, cla-backend-go/github/github_installation.go, cla-backend-go/github/github_user.go, cla-backend-go/github/init.go, cla-backend-go/github_organizations/handlers.go, cla-backend-go/github_organizations/models.go, cla-backend-go/github_organizations/repository.go, cla-backend-go/github_organizations/service.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/cla.yaml, cla-backend-go/v2/github_organizations/handlers.go, tests/rest/test_v4_github_organizations.tavern.yaml
- adding getProjectGithubOrganizations api in go backend. (in v1 and v2)
- also returning github info and list of repositories in response model.
=> Feature/748 v2 GitHub org api

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
=> Github Organizations are not aligned properly and the card looks clumsy

cla-backend-go/signatures/repository.go
- Fixed pagination issue raised in getting project signatures
=>  Bug/Signatures Pagination Error

cla-backend/cla/models/github_models.py
- Handle bad data exception for a non digit PR number
=> Bug/ API-Python PR Number Parse Error

cla-frontend-corporate-console/src/ionic/services/cla.service.ts
=> UI - Remove Unused Service Methods

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
=> Corporate Console - Not able to delete CLA Manager from Manage Whitelist page

cla-frontend-project-console/src/ionic/components/sort-table/sort-table.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- Optimized github organistion to v3
- Fixed table sorting issue
=> - Fixed pagination issue

cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.html, cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
1. Changed UI and Added proper messages when list is empty..
2. Changed CLA manager list view on whitelist screen when no LFID found. (As per discussion with @nirupama on Slack)
3. Load proper mangers list on click of View CLA Managers.
4. Added Search functionality.
=> Corporate Console - Search does not work in View Manager popup

cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
=> Completed project console cleanup 

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.scss, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> Corporate Console - Back to project signatures link is removed and menu is displayed when the Manage Whitelist page is refreshed

cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.scss, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts
=> Solved text trim and spelled mistake

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.scss, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.scss, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
=> - Fixed request company access issues

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss
=> Corporate Console: "Get Started" button should show pending requests to join a company

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.scss, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.html, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.scss
=> Footer is displayed on the top of the page and overlaps on the logo in contributor console

cla-backend-go/whitelist/repository.go
=> - Updated API endpoint with success message

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.scss, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-yesno-modal/cla-company-admin-yesno-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-new-company-modal/cla-new-company-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.html, cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.html
Footer moved at top due to change in position attribute globally. I have added fixed class to solved dialog footer issue. Ideally it should be fixed at bottom.
=> Dialog buttons misplaced

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts
=> Corporate Console - Spinning icon is still displayed a after clicking on Cancel button while trying to create duplicate company

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.scss, cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- Fixed issued in request company access on contributor console
- Added delete button to delete CLA group on project console
=> [#551 / #810 / #816] Fixed issued sending CCLA manager email

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
1. Solved issue CLA Manager is able to Join a company which CLA Manager is already associated to.
2. Cleanup unused code.
=> CLA Manager is able to Join a company which CLA Manager is already associated to

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss
=> Hand Pointer is displayed for the Company when Request to join the company is pending

cla-backend-go/cmd/server.go, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/gerrits/repository.go, cla-backend-go/gerrits/service.go, cla-backend-go/project/handlers.go, cla-backend-go/repositories/repository.go, cla-backend-go/repositories/service.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go
- Unassign github and gerrit repositories
- add note and disable signature approved for signatures
=> [#816]Bug/Delete Project

cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
Solved browser back button issue for popup on below model. Please let me know if any missing.
1. Connect Github Account
2. Delete Github Account
3. Add CLA Group
4. Delete CLA Group
5. View Signatures
6. View Companies
7. Configure Github Repositories
8. Add Gerrit Instance
=> Project Management Console: Popup window is still displayed when navigated back to All Projects page in the browse

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.scss
=> Contributor Console - Options not visible to proceed further after clicking in Corporate/Individual

cla-backend/cla/models/docusign_models.py
- Setting signature_reference_name
=> [#839] setting signature_reference_name

cla-backend/cla/controllers/signature.py, cla-backend/cla/tests/unit/test_signature_event.py
- Send email to deleted CLA manager
- Send email to added CLA manager
=> [#792] Feature/Add Delete Manager Email Notification

cla-backend-go/metrics/repository.go, cla-backend-go/metrics/service.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/cla.yaml, cla-backend-go/utils/auth_user.go, cla-backend-go/v2/metrics/handlers.go
- returning topProject metrics by 
CCLA count (does not include employee signature)
ICLA count 
ICLA+CCLA count (does not include employee signature)
- only admin will have access to topProjects api
=> top projects api

cla-backend/cla/models/github_models.py
- Fixed printout - removed trailing comma to resolve stack trace error
=> Resolved Printout Error/Trace when Creating New User

cla-frontend-contributor-console/src/ionic/modals/cla-employee-request-access-modal/cla-employee-request-access-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
- Fixed github organisation sort
- Fixed PDF not having project name and email
- Trim long text on signuature and company table
=> [#775 / #788 / #789] - github org sort, character ellipsis on table

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, cla-backend-go/Makefile, cla-backend-go/cmd/metrics_lambda/main.go, cla-backend-go/metrics/repository.go, cla-backend-go/onboard/handlers.go, cla-backend-go/signatures/service.go
- Added debug statements for running metrics lambda
- Added ability to run metrics lambda in local mode
- Added additional build target for running metrics on mac
- Updated GH templates
- Removed extraneous `fmt.Sprintf` (lint error)
=> Metrics API Testing and Debug

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html
- Updated grammar
- Moved IC sentence to below request access paragraph
=> UI - Corp Console - Updated text/grammar

cla-frontend-corporate-console/src/ionic/components/get-help/get-help.html, cla-frontend-corporate-console/src/ionic/components/get-help/get-help.scss
- Updated Nav Help Link to Getting Started - Issue: #907 
=> Updated Help Link

cla-backend-go/project/repository.go
- Fixed Dynamo Validation error update on project
=> Bug/Project Update

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> [915] - Add ellipsis to the company name

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss
=> Solved issue of logo move right side on corporate console companies page

cla-frontend-contributor-console/src/ionic/components/get-help/get-help.html, cla-frontend-contributor-console/src/ionic/components/get-help/get-help.module.ts, cla-frontend-contributor-console/src/ionic/components/get-help/get-help.scss, cla-frontend-contributor-console/src/ionic/components/get-help/get-help.ts, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.html, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.module.ts, cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.scss, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.html, cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.module.ts, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html, cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.module.ts, cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.html, cla-frontend-project-console/src/ionic/components/get-help/get-help.html, cla-frontend-project-console/src/ionic/components/get-help/get-help.module.ts, cla-frontend-project-console/src/ionic/components/get-help/get-help.scss, cla-frontend-project-console/src/ionic/components/get-help/get-help.ts, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.module.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.module.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.module.ts
=> [#907 / #818] - Help Ribbon

cla-backend-go/whitelist/models.go, cla-backend/cla/controllers/user.py, cla-backend/cla/models/docusign_models.py, cla-backend/cla/routes.py, cla-backend/cla/tests/unit/test_user_event.py, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.ts, cla-frontend-contributor-console/src/ionic/modals/cla-send-cla-manager-email-modal/cla-send-cla-manager-email-modal.html, cla-frontend-contributor-console/src/ionic/services/cla.service.ts, infra/get-ssm-parameters.ts
- Updated email contents for Contributors requesting CLA Manager to sign/authorize
- Renamed function
- Added company name as it's needed for the email
- Updated unit tests
- Fixed SSM parameter name - cla-auth0-platform-api-gw-{stage}
- Added TODO for the UI
- Changed WL to Approval List
=> [#644] Contrib Console - Email Testing/Updates

cla-backend/cla/controllers/user.py, cla-backend/cla/models/sns_email_models.py
- Updated email text
- Resolved email not being sent (issue with recipients array vs string)
=> [#644] - Email Fixes/Update

cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.scss, cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.ts, cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.html, cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.scss, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> Corporate Console - User is not able to navigate back to Companies page when clicked on Back link from menu

cla-backend/.gitignore, cla-backend/cla/controllers/project.py, cla-backend/cla/controllers/user.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/routes.py, cla-backend/cla/tests/unit/test_user_event.py, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.ts
- UI - Added Company Name to Contributor Console where Company doesn't exist
- UI - Added Contributor Console Form Validation
- API - Updated python data models to allow caller to set attributes_to_get
- API - Email text updates to invite CLA Manager
=> [#644] Contributor Workflow - Email Testing / Company Name

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
=> Resolved Issue Rendering OPNFV CLA Group

cla-backend/cla/routes.py
=> Resolve Python Routes Issue with hug types.

cla-backend/cla/routes.py
=> Resolved Route Issue

cla-backend/cla/controllers/project.py, cla-backend/cla/models/dynamo_models.py
=> Rolledback Python attributes_to_get projection for models

cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.html, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.scss, cla-frontend-contributor-console/src/ionic/modals/cla-company-admin-send-email-modal/cla-company-admin-send-email-modal.ts
=> Access Required not work in Contributor Console.

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
=> Corporate Console - Sorting order of companies and signed projects

cla-backend-go/v2/gerrits/handlers.go, cla-backend-go/v2/github_organizations/handlers.go, cla-backend-go/v2/metrics/handlers.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/repositories/handlers.go
- Adding authorization check on project,github_organizations, github_repositories, gerrits
- removing admin only authorization in top-projects api
=> adding authorization check on api

cla-backend/cla/controllers/user.py, cla-backend/cla/routes.py
=> Resolved Send Email API Error

cla-frontend-project-console/src/ionic/components/get-help/get-help.scss, cla-frontend-project-console/src/ionic/components/section-header/section-header.html, cla-frontend-project-console/src/ionic/components/section-header/section-header.scss, cla-frontend-project-console/src/ionic/components/section-header/section-header.ts, cla-frontend-project-console/src/ionic/constants/general.ts, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.scss, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.scss, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
- Hide View Companies link when only ICLA enabled
- Improved UI
- Added error messages when no description available
=> Project Console - VIEW COMPANIES is enabled for project which has only ICLA enabled

cla-backend/cla/controllers/project.py
- Fixed project controller function that had invalid parameters
=> [#960] Bug/Fetch Unsigned Projects

cla-frontend-project-console/src/ionic/modals/cla-contract-version-modal/cla-contract-version-modal.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
=> Project Console - Issues with PDF template when only CCLA or ICLA is enabled for the project 

cla-backend-go/logging/logger.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/whitelist/handlers.go, cla-backend-go/whitelist/repository.go, cla-backend-go/whitelist/service.go, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Added status query parameter
- Updated UI to query using parameter
- Added parmater on spec
- Updated query backend logic
=> [#908] Added Status Invite Filter for Queries

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
=> [#901] Filter by Pending Status

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Adjusted filter to properly count issue counts
=> [#908] Resolved Invite Count Filter

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> Resolved Missing Parameter in Invite Filter

cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.scss, cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts
=> Project Console - UI hangs with spinning icon when trying to edit CLA group with duplicate CLA group name

cla-frontend-project-console/src/ionic/components/pdf-viewer/pdf-viewer.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts
=> Project Console - View ICLA button is not selected by default and when clicked on DOWNLOAD, html file is downloaded

cla-backend-go/whitelist/service.go, cla-backend/cla/controllers/user.py, cla-frontend-contributor-console/src/ionic/components/get-help/get-help.html, cla-frontend-contributor-console/src/ionic/constants/general.ts, cla-frontend-corporate-console/src/ionic/components/get-help/get-help.html, cla-frontend-project-console/src/ionic/components/get-help/get-help.html
=> Change documentation URL

cla-frontend-contributor-console/src/ionic/modals/cla-next-step-modal/cla-next-step-modal.ts, cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.scss, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> Corporate Console: Fixed small issues and page break on company detail screen.

cla-backend/cla/salesforce.py, cla-backend/serverless.yml
=> Revert "[#947]Feature/Get SF Project by Project Service (#967)"

cla-frontend-contributor-console/src/ionic/validators/email.ts, cla-frontend-corporate-console/src/ionic/validators/email.ts, cla-frontend-project-console/src/ionic/validators/email.ts
=> Changed email validator for email validation

cla-backend-go/.gitignore, cla-backend-go/Makefile, cla-backend-go/swagger/cla.yaml, cla-backend/cla/utils.py, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, infra/get-ssm-parameters.ts
- API - Added authentication headers to the GH API calls to increase the rate limit
- API - Rolled in API spec for CLA Manager Requests
- Infra - Makefile MacOSX Updates
- Infra - Added SSM query parameter key for troubleshooting
=> [#1037] Unauthenticated GitHub API Calls - Rate Limit Exceeded

cla-backend-go/serverless.yml, cla-backend/cla/config.py, cla-backend/serverless.yml
=> Infra - Added GH Token Environment Variable

.circleci/config.yml
=> Landing Page Deployment Update

cla-backend/cla/controllers/gerrit.py, cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
- UI - Resolved Gerrit authentication flow - trap for unauthenticated error and redirect to the login.
=> [IT-19616] Gerrit Authentication Flow Update

cla-backend/cla/controllers/signature.py, cla-backend/cla/tests/unit/test_signature_controller.py
- Updated email text, subject, format, sign-off
- Change whitelist to approval list
=> Send Emails on Corporate Console Approval List Update

cla-backend-go/serverless.yml, cla-backend/cla/salesforce.py, cla-backend/cla/tests/unit/test_salesforce_projects.py, cla-backend/serverless.yml
- Leveraged existing Project Service to get SF projects
- Added unit tests
=> [#947]Feature/Platform Project Service

cla-backend-go/.gitignore, cla-backend-go/Makefile, cla-backend-go/cla_manager_requests/handlers.go, cla-backend-go/cla_manager_requests/models.go, cla-backend-go/cla_manager_requests/projections.go, cla-backend-go/cla_manager_requests/repository.go, cla-backend-go/cla_manager_requests/service.go, cla-backend-go/cmd/server.go, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/go.sum, cla-backend-go/package-lock.json, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/utils/utils.go, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, infra/index.ts
[#782] API - Added API for CLA Manager REQUEST ACCESS
- API - Added handlers, service layer, database logic for handing pending CLA manager requests
- API - Updated logic that sends email to CLA managers and requesters when requests are received, approved and denied
- API - Added logic to create/send events when CLA manager requests are generated, approved and denied
- API - Added logic to update the Signature ACL when the CLA manager request is approved
- API - added platform project and organization service client/model download/build options
- UI - Updated links in UI to support CLA Manager request/approve/deny.
=> [#782] API - Added API for CLA Manager REQUEST ACCESS

cla-backend-go/serverless.yml, cla-backend/serverless.yml
- Adding query index permissions in serverless  for table cla-<stage>-cla-manager-requests
=> Adding query index permissions for cla-<stage>-cla-manager-requests table indexes

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
=> Refactor code for company projects view and handled error

cla-backend/cla/models/github_models.py
- API - Resolved issue where the GH check for a user was looping through all project signature records to locate them in an approved list. This was causing the GitHub check to timeout and not update the status in GitHub.
=> [#1043,#1037] Update Existing GH User Approved List Logic

cla-backend-go/serverless.yml
- Adding index query permissions for indexes removed in commit c4e823248cc935c9c56f99d30e3880412f9ce09b
=> Adding index query permissions 

cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.module.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-companies-signatures-modal/cla-contract-view-companies-signatures-modal.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.module.ts, cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/pipes/trim-characters.pipe.ts, cla-frontend-project-console/src/ionic/shared.module.ts
Issue is not reproducible on Dev so just perform unit testing with changed code. @nirupamav please do regression on Production once it is deploy
=> Project Console: "View Companies" table error

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/events/handlers.go, cla-backend-go/v2/metrics/handlers.go
- Using companySFID for GetRecentCompanyProjectEvents,ListCompanyProjectMetrics api instead of company uuid
=> [#930] Using companySFID for GetRecentCompanyProjectEvents api 

cla-backend/cla/tests/unit/test_github.py, cla-backend/cla/utils.py, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
- UI - Corporate Console - Updated logic that shows the pending contributor requests
- API - Updated GH message text
=> [#1076] Resolved Pending Contributor Requests Table Issue

cla-frontend-contributor-console/edge/security-headers.js, cla-frontend-corporate-console/edge/security-headers.js, cla-frontend-project-console/edge/security-headers.js
=> Resolved Project Logo Loading Issue

cla-backend-go/package.json, cla-backend-go/yarn.lock, cla-backend/cla/salesforce.py, cla-backend/cla/tests/unit/test_salesforce_projects.py, cla-backend/package.json, cla-backend/serverless.yml, cla-backend/yarn.lock, package.json, yarn.lock
=> Resolved Project Logos

cla-backend/cla/tests/unit/test_github.py, cla-backend/cla/utils.py
=> [#1043] Added Help Desk Link

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> [#1073] Accept Button Displayed instead of Deny

cla-backend-go/company/service.go, cla-backend-go/user/repository_dynamo.go
- Added to logic to set the user's company ID in their user record when
the user is accepted as part of the request access to company flow.
=> Added User Company ID when User is Added to Company ACL

cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/pipes/local-timezone.pipe.ts, cla-frontend-corporate-console/src/ionic/shared.module.ts
=> Solved small issues [1063], [1064], [1067] and [1071].

cla-backend-go/v2/project/repository.go
- Added ICLA enabled filter getting CLA projects
=> [#932] Feature/ICLA filter

cla-backend-go/cla_manager_requests/handlers.go, cla-backend-go/cla_manager_requests/repository.go, cla-backend-go/cla_manager_requests/service.go, cla-backend-go/swagger/cla.yaml, tests/rest/README.md, tests/rest/test_v3_cla_manager_api.tavern.yaml
- Updated swagger spec to return 409 on existing CLA Manger request in pending or approved state, updated handler logic
- Added start of functional tests
=> [#1068] Prevent Duplicate CLA Manager Requests

cla-backend/cla/controllers/signature.py
- Fixed email calls for adding and deleting cla manager
- Formated email content
=> Bug/Email- CLA Manager Add|Delete

cla-backend-go/Makefile, cla-backend-go/cla_manager_requests/handlers.go, cla-backend-go/cmd/functional_tests/cla_manager/cla_manager.go, cla-backend-go/cmd/functional_tests/health/health.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/cmd/functional_tests/test_models/common.go, cla-backend-go/cmd/metrics_lambda/main.go, cla-backend-go/go.mod, cla-backend-go/go.sum
- Added example frisby golang functional framework examples. Will build upon these to provide functional testing coverage.
=> Added Frisby Golang Functional Testing Framework

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/utils/s3.go, cla-backend-go/v2/company/service.go
- adding ccla_url and cla_group_name in response of active cla list
- fixed cla.v2 swagger file
=> [#935] adding ccla_url and cla_group_name in response of active cla list

cla-backend-go/cla_manager/handlers.go, cla-backend-go/cla_manager/models.go, cla-backend-go/cla_manager/projections.go, cla-backend-go/cla_manager/repository.go, cla-backend-go/cla_manager/service.go, cla-backend-go/cmd/server.go
- Updated CLA manager package from cla_maanager_requests to a more generic cla_manager
- Updated create request logic to look for prior user requests - old logic didn't filter properly
=> Updated CLA Manager Package

.circleci/config.yml
- Updated env for funcational tests - added users
- Updated functional tests binary path
=> Functional Test Authomation Configuration

cla-backend-go/cla_manager/handlers.go, cla-backend-go/cla_manager/service.go, cla-backend-go/cmd/functional_tests/cla_manager/cla_manager.go, cla-backend-go/cmd/functional_tests/health/health.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml
- Added additional CLA manager Add/Remove functional tests
- Resolved issue with send CLA Manager events to the event log
=> Functional Test Cleanup

cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Updated Corporate Console Add/Remove manager to invoke the updated API which sends emails and adds event logs
- Updated UI to allow the CLA manager to add not only the LFID, but also the Name and Email of the new CLA manager
- Added additional form validation
=> Add/Remove CLA Manager UI Updates

cla-backend-go/v2/project/handlers.go
- Disabled permission check while getting enabled projects for user
=> [#932] Bug/V2 Enabled Projects/Scope

cla-backend-go/cmd/server.go, cla-backend-go/v2/cla_manager/handlers.go
Added email service when creating a user that doesnt have LFID
=> [#1101]:Feature/Email Send for No LFID

cla-backend-go/v2/signatures/handlers.go
- Adjusted API access to allow users with org scope
=> Allow View of Get Company Signatures from Org Scope

cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-corporate-console/src/ionic/validators/lfid.ts, cla-frontend-corporate-console/src/ionic/validators/user-name.ts
=> Corporate Console - No Action performed and error displayed in Console when trying to add CLA Manager who does not exist.

cla-backend-go/cla_manager/handlers.go
- Fixed issue when user with invalid LFID is used when adding CLA Manager
=> [#1116, #818] Bug/Add CLA Manager(v1) with invalid LFID

cla-backend/cla/controllers/github.py, cla-backend/cla/models/dynamo_models.py
- Fixed issue of case sensitive GitHubOrg Model search by organization name
=> [#1126] Bug/Installation with name check

cla-backend-go/.gitignore, cla-backend-go/Makefile, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/organization-service/client.go
- Integrated organisation service that handles setting/removing OrgUserRoleScope
- Integrated organization service to  get scope ID, roleID in deleting CLA Manager
- Search for SF Project and CLA projects based on company,project,claGroup parameters
- Changed swagger spec for both addition & deletion operations
- Modified .gitignore for user, acs and org services
=> [#932] Feature/cla-manager-v2-refactor

cla-backend-go/Makefile, cla-backend-go/cmd/server.go, cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/organization-service/client.go, cla-backend-go/v2/sign/service.go, cla-backend-go/v2/user-service/client.go
- adding acs service
- if user email is given as cla-signatory then we will search user in user service then convert that user to contact if he is lead and then add user as cla-signatory for that project,organization.
=> [#1106] converting user to contact and adding him as cla-signatory if we

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/tests/unit/data.py, cla-backend/cla/tests/unit/test_gh_org_models.py
- Fixed issue when performing insensitive case search 
- Added unittests for setting githubOrg name and scanning
=> [#1126] Bug/gh org seach name lower

cla-backend-go/cmd/functional_tests/approval_list/approval_list.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/cmd/server.go, cla-backend-go/package.json, cla-backend-go/project/handlers.go, cla-backend-go/project/repository.go, cla-backend-go/serverless.yml, cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/cla.yaml, cla-backend-go/swagger/common/signature-approval-list.yaml, cla-backend-go/swagger/common/signature.yaml, cla-backend-go/tests/utils_test.go, cla-backend-go/utils/string_utils.go, cla-backend-go/utils/utils.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/project/service.go, cla-backend-go/v2/signatures/handlers.go, cla-backend-go/whitelist/service.go, cla-backend/serverless.yml, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Updated Swagger specs for v1 and v2 - updated Signature response model (replaced whitelist with approval list naming scheme)
- Added Approval List Add/Remove Handler, Service, Repository implementation
- Wrote functional tests to support API
- Added ACS/checks/permissions checks
- Updated UI code that queries the signature fields
=> [#1135] Approval List v2 API

cla-backend-go/swagger/cla.v2.yaml
- Updated path url for delete CLA mgr
=> [#937] CLA Mgr Delete

.circleci/config.yml, cla-backend-go/cmd/functional_tests/approval_list/approval_list.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/signatures/service.go, cla-backend-go/v2/signatures/handlers.go
- Fixed email format for notifying managers
- Refactored functional tests - added more cases
- Golang Functional tests now run right after deployment, then tavern ;-O
- Updated functional test data
=> [#1135] Approval List v2 API Updates

.circleci/config.yml, cla-backend-go/cmd/functional_tests/main.go
=> Re-enabled All Functional Tests

cla-backend-go/signatures/service.go, cla-backend-go/v2/signatures/handlers.go
=> Resolved Email Format Issue

cla-backend-go/cmd/functional_tests/approval_list/approval_list.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/tests/utils_test.go, cla-backend-go/utils/utils.go, cla-backend-go/v2/signatures/handlers.go, cla-backend-go/v2/signatures/validators.go
- Fixed email format for notifying managers
- Added Approval List Validation
=> [#1135] Approval List v2 API Updates - Validation

cla-backend/cla/controllers/github.py
- Resolves GitHub Organization by Lower Name query issue
=> [#1140] GitHub Org Lookup

cla-backend-go/cmd/functional_tests/signatures/signatures.go, cla-backend-go/v2/signatures/handlers.go
- Updated error response codes
=> Updated Functional Tests

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/utils/string_set.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/events/handlers.go, cla-backend-go/v2/metrics/handlers.go
- adding projectSFID in the input for getActiveCLA api and  getCLAManagers api
- return empty array if we don't find data for it
- if projectSFID is foundation then we show data for each cla_group for each project inside it
- if projectSFID is of project then we show data for each cla_group inside of the project
=> adding projectSFID in the input for getActiveCLA api and  getCLAManagers api

cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts
=> Project Console - Page is not auto refreshed when template is generated and then Back to Project is clicked

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go
- Added endpoint that assigns the  cla-manager-designee role
=> [#1102] Feature/ Add CLA Manager Designee

cla-backend/cla/models/dynamo_models.py
=> Added Company Set Date Modified Helper Function

cla-backend/cla/models/dynamo_models.py
=> Removed Set Modified Date/Time

cla-backend-go/cmd/functional_tests/approval_list/approval_list.go, cla-backend-go/cmd/functional_tests/signatures/signatures.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/events/handlers.go, cla-backend-go/v2/gerrits/handlers.go, cla-backend-go/v2/github_organizations/handlers.go, cla-backend-go/v2/metrics/handlers.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/repositories/handlers.go, cla-backend-go/v2/sign/handlers.go
=> v2 - Ensures APIs return forbidden for authorization failures

cla-backend/cla/routes.py, cla-backend/serverless.yml
- Removed external authorizer for old python v1 APIs
- Removed old commented out code from routes.py
=> [#1106] Removed External Authorizer

cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, infra/get-ssm-parameters.ts
=> Added LFX Portal URL SSM parameter

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/project-summary.yaml
=> Added Member Portal Dashboard Summary Swagger Spec

cla-backend-go/swagger/cla.v2.yaml
=> [#1176] Added Member Portal Dashboard Summary Swagger Spec

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Added swagger spec for CLA Manager request endpoint
- Added cla_manager service 
- Added create designee and send email for cla manager requests
=> [#1107] Feature/ Add CLA Manager Request

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/project-summary.yaml
- Added permissionToAccess to response payload to allow the LFX UI to
determine if the user has access to the Foundation and/or Projects.
- Updated Descriptions
=> Updated Project Summary Response

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go
- Fixed contact admin workflow during cla manager request
- Updated swagger spec
=> [#1107] Bug/Contact Admin

cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Fixed email content with company and contributor details
=> [#1107] Bug/Email CLA Manager Designee

cla-backend-go/.gitignore, cla-backend-go/signatures/errors.go, cla-backend-go/signatures/service.go, cla-backend-go/utils/utils_user_auth.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/events/handlers.go, cla-backend-go/v2/gerrits/handlers.go, cla-backend-go/v2/github_organizations/handlers.go, cla-backend-go/v2/metrics/handlers.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/repositories/handlers.go, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/signatures/handlers.go, cla-backend/.gitignore
- Updated v2 API handlers to return error message with 403 forbidden responses
=> [#1187] Add v2 403 Error Messages

cla-backend-go/signatures/service.go
=> Updated Email Template with CLA Manager User Name

cla-backend-go/v2/cla_manager/handlers.go
- Returned bad response for case where company has no admin
=> [#1107] CLA Manager Designee (No Admin)

cla-backend/cla/models/github_models.py
=> Redirect to v2 Contributor Console When CLA Group version is v2

cla-backend-go/serverless.yml, cla-backend/cla/config.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/github_models.py, cla-backend/serverless.yml, infra/get-ssm-parameters.ts
- Added SSM Contributor Console V2 host/url
- Updated Python code to load contributor console url
- Added version, date created, date modified set/get functions
- Updated API call to get version value
=> Contributor Console v2 Config

cla-backend-go/Makefile, cla-backend/cla/models/docusign_models.py
- To prevent Docusign Session Timeout, regenerate the sign url/link
=> Regenerate Previous ICLA Signing Request Link

cla-backend/cla/models/docusign_models.py
- Updated signature signing logic to update existing signature on resume
- Added signature sign pause sign solution to gerrit flow
=> Signature Sign Pause Sign Fix

README.md
- Added announcement for replacing wl with approval list
=> Added README Announcements

cla-backend-go/v2/cla_manager/handlers.go
- Fixed scope issues for cla manager reuest with organization scope check
=> Scope for CLA Manager Request

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Added functionality to invite user to sign CLA by contributor
- Added spec for endpoint
- Added functionality to send email to company admins
=> [#1298] Feature/Invite Admin

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Updated path with no CLA group ID passed
- Implemented mapping to connect salesForceProject to CLAGroup
=> Feature/Delete CLA Manager

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Integrated the EasyCLA user in the invite process
=> [#1198] Contributor Console No CLA Manager

cla-backend/cla/models/dynamo_models.py
- Added get event date as part of the event table data model
=> Added Python Get Event Date Accessor

.circleci/config.yml
=> Resolved Landing Page Deploy

cla-backend-go/swagger/cla.v2.yaml
=> Added Project Console v2 Swagger Specifications

cla-backend-go/cmd/functional_tests/cla_group/cla_group.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/go.sum, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/service.go
- Defines a new API endpoint to validate the CLA Group Name and Description
- Wrote functional tests
- Updated swagger
- Provided implementation
=> [#1268] CLA Group Validation Service

.circleci/config.yml, cla-backend-go/cmd/functional_tests/cla_group/cla_group.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/service.go
- Updated swagger response object
- Updated functional tests
- Skip min/max character validation in service as swagger handles
- Updated CI/CD config to add PM as functional test user
=> [#1268] CLA Group Validation Updates

cla-backend-go/cla_manager/service.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Handle conflict for existing cla-manager role
- Fixed email list for cla manager alerts including deleted manager
- Fixed issue for no lfid user found when adding cla manager
=> [#937] Add/Delete CLA Mgr Cleanup

cla-backend-go/cmd/server.go, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend/cla/routes.py
- Updated API log responses to include additional detail
=> Updated Error Logs for Request CLA Manager

cla-backend/cla/models/github_models.py
- Ensure overall status fails when more than one committer fails
=> [#1278] Updated GitHub Status Update Logic

cla-backend-go/cmd/server.go, cla-backend-go/v2/cla_manager/service.go
- Added EasyCLA user if not found while adding CLA Manager (v2)
=> [#1276] EasyCLA User addition(Add CLA Manager)

cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend/cla/models/github_models.py
- Added additional event/audit logging
=> Added Event Logging for Contributor -> Designee Flows

cla-backend-go/cmd/server.go, cla-backend-go/repositories/repository.go, cla-backend-go/repositories/service.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Updated IDs EasyCLA company and project in request URL
- Integrated v1 repository service to get SFIDs
=> [#1198] Feature/Individual Contributor Console - No CLA Manager

cla-backend/cla/models/docusign_models.py
- Updated logic to pull CLA Manager's info
- Added additional debug and standarization to logs
- Updated email content
=> [#1127] CCLA DocuSign Pulling Wrong User

cla-backend-go/Makefile, cla-backend-go/cla_manager/models.go, cla-backend-go/cla_manager/service.go, cla-backend-go/cmd/functional_tests/approval_list/approval_list.go, cla-backend-go/cmd/functional_tests/cla_group/cla_group.go, cla-backend-go/cmd/functional_tests/cla_manager/cla_manager.go, cla-backend-go/cmd/functional_tests/signatures/signatures.go, cla-backend-go/go.mod, cla-backend-go/go.sum, cla-backend-go/package-lock.json, cla-backend-go/package.json, cla-backend-go/signatures/service.go, cla-backend-go/utils/email.go, cla-backend-go/utils/utils.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/organization-service/client.go, cla-backend-go/v2/organization-service/errors.go
- Updated code to return 409 conflict from org service
- Resolved lint errors
- Updated lint tool version
=> Handle Org Service Duplicate/Conflict

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Added endpoint for sending emails to CLA Managers for a given company and project
=> [#1270] Feature/Request All CLA Managers

cla-backend-go/tests/utils_regex_test.go, cla-backend-go/utils/regex.go, cla-backend-go/v2/company/handlers.go
=> Added Company Name Validation

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/company/models.go, cla-backend-go/v2/company/service.go
- Added v2 endpoint to allow contributors to fetch the list of CLA managers for a given company/cla group.
=> Added API Endpoint for Contributor get CLA Manager List

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Implemented notification endpoint that alerts a selected list of cla managers for a given project |company
=> [#1270] Feature/Email Notification

cla-backend-go/Makefile, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/cla.yaml
- Added/Updated description/examples
- Commented out unused definitions
- Cleaned up tool setup
=> Swagger Cleanup

cla-backend-go/cmd/server.go, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Handled error in case user associated with different org
- Handled firstname and lastname parameters
- Fixed complexity issues by using cla_manager service layer
=> [#1107] CLA Manager Invite(Corporate Console)

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/project/service.go
- Added additional flags to indicate if ICLA, CCLA and ICLA enabled with CCLA flags
=> [#1308] Updated CLA Enabled Endpoint

cla-backend-go/projects_cla_groups/repository.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/service.go
=> [#1290] adding api for foundation->cla-group->project mapping

cla-backend-go/v2/cla_manager/service.go
- Return right response for user-service search
=> [#1107] Bug/User Search

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Refactored user service search to search by only email
- Changed payload for createManagerRequest endpoint to use fullName other than firstName and lastName
=> [#937,#1107] Feature/User Search

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/utils/s3.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/signatures/handlers.go, cla-backend-go/v2/signatures/service.go
- adding api to get signed document link for icla,ccla
- project-manager can download signed icla,ccla document for his cla-group
- cla-manager can download signed ccla document for his company
=> [#1320] adding api to get signed document link

cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/event_types.py, cla-backend/run-lint.sh
- Add event/activity log entry when signing is complete for both ICLA and CCLA
- Send email to CLA Manager not Company Admin
- Updated debug/error responses
=> Updated DocuSign Callback Logic

cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/service.go
- Added error handling for response from the v2 integration for request corporate signature endpoint
- Added error handling from the org-service for getting userolescopes
=> [#1104,#1106] Feature/v2-Request Corporate Fixture

cla-backend-go/v2/signatures/handlers.go
- updated error message for get signature pdf
=> Updated error responses/error messages

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/model_interfaces.py, cla-backend/cla/utils.py
- Implemented accessors and setters for the Python model for the lookup table
- Created interface and utility function to get the ProjectCLAModel
=> Feature/ Python Data Model for Project-CLAGroup Lookup Table

cla-backend/cla/controllers/gerrit.py
- Added support for v2 to redirect to the new contributor console
=> Updated Gerrit Redirect Page

cla-backend/cla/controllers/gerrit.py
=> Updated Gerrit v2 Console Link

.circleci/config.yml, cla-backend-go/cmd/server.go, cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/company/service.go
- Integrated ACS service to invite user during organization creation
- Send email to user for newly created sf organization company
- Associate user with company owner role for company
=> [#1218] - Feature/Contributor Console - No Company

cla-backend-go/projects_cla_groups/repository.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/service.go, cla-backend/cla/controllers/github.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/sns_email_models.py, cla-backend/cla/tests/unit/test_github_controller.py, cla-backend/run-tests.sh
- Updated python table definitions/attributes
- Set Foundation Name, Project Name, CLA Group Name on save
- Update GH Org Offline system email to use email template
- Updated API to return additional name attributes
=> Added Name for CLA Group Project Lookup Table

cla-backend-go/v2/cla_groups/service.go
=> Added project name to cla group project list

cla-backend-go/v2/cla_manager/service.go
- Fixed get admin error raised by using the easyCLA company ID in search instead of Organization SFID
=> [#1198] Bug/Invite Company Admin

cla-backend-go/cla_manager/service.go
- Fixed issue for viewing company when CLA Manager is added
=> [#1292] Company View for added CLA Manager

cla-backend-go/v2/cla_manager/service.go
- Fixed issue raised when user with no organization is assigned cla-manager-designee for a given organization
=> [#1234] Bug/User with no Company

cla-backend-go/v2/company/service.go
- Fixed issue creating company (in easyCLA) for user having company-owner role for a salesforce organization
=> [#1341] Bug/Contributor already Company Owner

cla-backend/cla/controllers/gerrit.py
- Fixed issue caused by using project id instead of gerrit id
=> [#1322] Bug/Gerrit Redirection

cla-backend/cla/controllers/gerrit.py
- Added redirect url for the gerrit flow when user is gated
=> [#1322] Feature/Gerrit Flow Redirect

cla-backend-go/serverless.yml, cla-backend/serverless.yml, infra/index.ts
=> Added Additional DynamoDB Events Stream Handler

cla-backend/cla/models/docusign_models.py
- Fixed issue for CCLA sign process by casting set to list for signature_acl records
=> [#1319] Bug/CCLA Sign Fail

cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/company/service.go
- Fixed issue got when user without LFID tries and creates a company
- Added checks for LF Email and LFUsername during company creation
- Fixed acs service callup for send user invite
=> [#1340,#1341] Bug/v2 Add company

cla-backend/cla/models/dynamo_models.py, infra/get-ssm-parameters.ts
- Added signed_on, sigtype_signed_approved_id
- Added user_email, user_github_username, user_name
- Added set/get, added to constructor, string function
- Resolved a number of flake8 lint issues
Resolves issue identified by @prasannamahajan where a python record save action was removing previously-stored values for signature records.
=>  Added Additional Attributes to Signature Model

cla-backend-go/yarn.lock, cla-backend/yarn.lock, cla-frontend-contributor-console/edge/yarn.lock, cla-frontend-corporate-console/edge/package.json, cla-frontend-corporate-console/edge/yarn.lock, cla-frontend-project-console/edge/yarn.lock, cla-next/yarn.lock, infra/yarn.lock
- Resolved dependabot alert for acorn library
=> Updated Node Yarn Dependencies

cla-backend-go/cla_manager/service.go, cla-backend-go/signatures/repository.go
- Fixed issue caused by adding/deleting cla managers to signatures that have signed flag set to false
=> Bug/Add and Delete CLA Managers

cla-backend-go/github_organizations/repository.go, cla-backend-go/utils/utils_user_auth.go, cla-backend-go/v2/github_organizations/handlers.go
=> Added Logging While Troubleshooting GH Org

cla-backend-go/v2/sign/service.go
- Removed check for cla-signatory role for requested user
=> [#1104] Bug/Request Corporate Signature

cla-backend-go/v2/cla_manager/service.go
- Provided contributor name in email body
=> Resolved Email Body Content Issue

cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/service.go
- Fixed regex check for firstname and lastname (atmost 30 characters)
- Added CLA Manager email in content for user with no LFID
- Check organization for user to be added as CLA Manager
- Integrated acs service to send user invite for users with no LFID
=> [#937] Add CLA Manager issues

cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.module.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
=> V1 - Corporate Console - Company-Project name overlaps on the logo in Manage approved list UI

cla-backend-go/v2/cla_manager/service.go
- Altered error message for cla-manager-designee conflict
=> [#1377] Feature/Invite Company Admin Error handling

cla-backend-go/v2/cla_manager/service.go
- Altered message in error thrown for users with no LFID
=> [#1375] Feature/Invite Company Admin No LFID

cla-backend-go/v2/cla_manager/service.go
- Added org check for user not in organization
=> [#1234] Bug/CLA Manager Designee no org assocaitioin

cla-backend-go/whitelist/service.go
- Fixed email content for approvals
=> [#987] Bug/CCLA whitelist Request- Email

cla-backend/cla/models/github_models.py, cla-backend/cla/utils.py
- Removed/commented out approved_by_manager check - query previously
disabled for performance reasons
- Changed is_whitelist to is_approved, updated function call parameters
names
=> Updated GitHub Badge Logic

cla-backend-go/company/repository.go
- Fixed status for previously rejected cla manager joining company
=> [#1068] Bug/Join Company Request

cla-backend-go/yarn.lock, cla-backend/cla/models/dynamo_models.py, cla-backend/yarn.lock
- Resolved issue when CCLA signing process stalls, and user goes away
and later comes back to resume. Leveraged updated query to refine
search results to approved = True and signed = True.
=> Updated Query for get_projects_by_company_signed

cla-backend/cla/controllers/user.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/model_interfaces.py, cla-backend/cla/tests/unit/test_user_event.py, cla-backend/cla/utils.py
- Added request for invite cla manager flow fixing request count
- Added utils function to get cclawhitelistrequest instance
- Added PynamoAPI for the CCLAWhitelistRequest Table
=> [#807] Bug/CCLA Whitelist Request

cla-backend-go/serverless.yml, cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml, cla-backend/cla/models/docusign_models.py, cla-backend/serverless.yml, infra/index.ts, infra/yarn.lock
- Added ICLA Download PDF Endpoint
- Added Download Handler/Service/Repo Query/Download
- Resolved lambda deployment
- Added signature index
- Updated email template for sending email to ICLA signer
=> ICLA PDF API Endpoint

cla-backend-go/signatures/repository.go
- Fixed getting wrong signature record when updating signature ACL
=> [#937] Bug/Add CLA Manager

cla-backend/cla/salesforce.py
- Added Access control methods for getting salesforce projects
=> [#1418] Bug/API Salesforce Projects

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-contributor-console/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgraded kind-of dependencies

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgraded acorn dependencies

cla-backend-go/v2/cla_manager/service.go
- Reordered creation of CLA Manager flow starting with EasyCLA and then LFX
- Fixed issue searching for claGroup by searching by ID
=> [#937] Add CLA Manager

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-contributor-console/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgrade minimist dependencies

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgrade mem dependencies

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgrade tunnel-agent dependencies

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgrade cryptiles dependencies

cla-frontend-contributor-console/src/yarn.lock, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/yarn.lock
=> Upgrade hoek dependencies

cla-backend-go/.gitignore, cla-backend-go/Makefile, cla-backend-go/cmd/server_aws_lambda.go, cla-backend-go/go.mod, cla-backend-go/go.sum
- Issue remains with multi-parameter options in URL
=> Rolled Back aws-lambda-go-api-proxy update

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/service.go
- Added Error handling for conflict of user already in some organization
- Refactored error message for user role scope conflict error
=> [#1432] Feature/Error Handling Request Corporate Signature

cla-frontend-contributor-console/src/package.json, cla-frontend-contributor-console/src/yarn.lock
- Resolved security vulnerability in mem lib by upgrading the library
version to ^4.0.0
=> Added Resolutions Section to Update Mem lib

cla-backend-go/company/repository.go, cla-backend-go/project/repository.go, cla-backend-go/v2/company/service.go
- Auto-create the EasyCLA company on-demand from Platform Org Service if
missing
=> Auto Create EasyCLA Company from Platform Org Service

cla-frontend-contributor-console/edge/package.json, cla-frontend-contributor-console/edge/yarn.lock, cla-frontend-corporate-console/src/package.json, cla-frontend-corporate-console/src/yarn.lock, cla-frontend-project-console/src/package.json, cla-frontend-project-console/src/yarn.lock
=> Upgraded mem dependencies to latest version

cla-backend-go/cmd/server.go, cla-backend-go/company/service.go, cla-backend-go/projects_cla_groups/repository.go, cla-backend-go/v2/company/models.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/organization-service/client.go
- Resolved Organization Service API update issue (changed search org
params name from []string to string)
- Prep work org service auto-create
=> Resolved Org Service API Update

cla-backend-go/approval_list/handlers.go, cla-backend-go/approval_list/models.go, cla-backend-go/approval_list/repository.go, cla-backend-go/approval_list/service.go, cla-backend-go/cla_manager/handlers.go, cla-backend-go/cla_manager/service.go, cla-backend-go/cmd/server.go, cla-backend-go/events/mockrepo.go, cla-backend-go/events/service.go, cla-backend-go/gerrits/handlers.go, cla-backend-go/project/handlers.go, cla-backend-go/project/repository.go, cla-backend-go/project/service.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/service.go, cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/dynamo_events/github_repository.go, cla-backend-go/v2/gerrits/handlers.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/project/service.go, cla-backend-go/v2/sign/service.go, cla-backend-go/v2/signatures/handlers.go
=> Renamed Project to CLA Group

cla-backend-go/cmd/server.go, cla-backend-go/gerrits/handlers.go, cla-backend-go/gerrits/models.go, cla-backend-go/gerrits/repository.go, cla-backend-go/gerrits/service.go, cla-backend-go/project/handlers.go, cla-backend-go/project/repository.go, cla-backend-go/project/service.go, cla-backend-go/projects_cla_groups/repository.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/cla.yaml, cla-backend-go/swagger/common/gerrit-list.yaml, cla-backend-go/swagger/common/gerrit.yaml, cla-backend-go/v2/gerrits/handlers.go, cla-backend/cla/models/dynamo_models.py
- adding list gerrit api
- adding project_sfid in gerrit model
- modifying gerrit add/delete api
=> [#1451]  v2 gerrit api

cla-backend-go/serverless.yml, cla-backend/serverless.yml
Seperating out s3:ListBucket permission
it's arn should be of s3 bucket
=> [#1227] updating s3 permission in serverless

cla-backend-go/cmd/server.go, cla-backend-go/v2/sign/service.go
- Fixed missing company acl for the initial cla manager
=> Bug/ Initial CLA Manager

cla-backend-go/project/errors.go, cla-backend-go/project/handlers.go, cla-backend-go/v2/project/converters.go, cla-backend-go/v2/project/errors.go, cla-backend-go/v2/project/handlers.go
- Moved errors and converters to a separate file within the package
=> Project Package Cleanup

cla-backend/serverless.yml
=> Removed CORS check at the API-GW for v3 endpoints

cla-backend-go/Makefile, cla-backend-go/health/service.go, cla-backend-go/swagger/cla.yaml
=> Added Additional DynamoDB Tables to Health Check

cla-backend-go/signatures/service.go, cla-backend/cla/controllers/signature.py
=> Email Content Cleanup

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html, cla-next/src/components/Footer.js
=> Updated Copyright Footer Year

cla-backend-go/v2/sign/service.go
- Fixed bug that was caused by uninitialized company service instance
=> [#1462] Bug/Request Corporate Signature

cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/organization-service/client.go
- Fixed issue caused by wrong scope id used in identifying specific projectSFID
=> [#937] Bug/ Delete CLA Manager

cla-backend/cla/controllers/gerrit.py, cla-backend/cla/controllers/signing.py, cla-backend/cla/models/dynamo_models.py, cla-frontend-contributor-console/src/ionic/modals/cla-select-company-modal/cla-select-company-modal.ts, cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts
- Resolved Gerrit v1 redirect issue (problem was we used project_id
instead of gerrit_id for v1 redirect)
- updated redirect page - added favicon, updated text by adding
corporate or individual to text and button, added title to HTML page
- Renamed function from postCheckedAndPreparedEmployeeSignature to
postCheckAndPreparedEmployeeSignature
- Added/Updated Gerrit and Project python dynamodb data model string
methods - cleaned up and added additional fields to assist with debug
=> [#1466] Gerrit v1 Redirect Update

cla-backend-go/signatures/repository.go, cla-backend-go/swagger/common/signature.yaml
- Added GitHub Username to signature response model (when available)
=> Signature Response Model Update

cla-backend/cla/controllers/user.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/model_interfaces.py, cla-backend/cla/routes.py, cla-backend/run-lint-file.sh
- Ensured ID was converted to string
- Fixed lint issues in model_interfaces.py and user.py
=> [#807] Resolved Python API Error when Saving Approval Request

cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/service.go
- using user's lfusername pass by acs to add user in company_acl
=> [LFX-2107] fixing request-corporate-signature api

cla-backend-go/go.sum, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/company/service.go
- Added userEmail(LFx) as payload and removed LFID check logic
=> Feature / Add company

cla-backend-go/cmd/server.go, cla-backend-go/v2/cla_groups/handlers.go, cla-backend/cla/controllers/github.py, cla-backend/cla/models/dynamo_models.py
- deleting gerrit/github repo linked to cla-group when we delete cla-group
- updating installation_id when user re installs github app on github organization
- adding user_lf_username field in signature python model
=> Bugfix/v2 GitHub org

cla-backend-go/v2/sign/service.go
- Remove cla signatory role for failed cases during the request corporate signature flow
=> [LFX 2027] Bug/Request Corporate Signature

cla-backend-go/approval_list/service.go, cla-backend-go/cla_manager/handlers.go, cla-backend-go/cla_manager/service.go, cla-backend-go/company/service.go, cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/signatures/service.go, cla-backend-go/utils/email.go, cla-backend-go/utils/utils.go, cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/service.go, cla-backend/cla/controllers/github.py, cla-backend/cla/controllers/signature.py, cla-backend/cla/controllers/user.py, cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/tests/unit/test_github_controller.py, cla-backend/cla/tests/unit/test_user_event.py, cla-backend/cla/utils.py, infra/get-ssm-parameters.ts
- Consolidated email help links to a single routine/helper function.
- Added v1 or v2 help/doc links based on project/cla group version
- Consolidated email sign-off text into single spot
=> [#1476] System Email Updates

cla-backend-go/cmd/server.go, cla-backend-go/go.mod, cla-backend-go/go.sum, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/gerrit-repo-list.yaml, cla-backend-go/swagger/common/gerrit-repo.yaml, cla-backend-go/v2/gerrits/handlers.go, cla-backend-go/v2/gerrits/models.go, cla-backend-go/v2/gerrits/service.go
- Added initial gerrit repository listing API
=> Gerrit Repository List

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/gerrit-repo.yaml, cla-backend-go/v2/gerrits/service.go
- Added web links
- Updated swagger documentation
- Added support for additional LF gerrit servers
=> Updated Gerrit Repos API

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/service.go
- Making required field compulsory in swagger spec for create cla-group api
- handling multiple errors in create-cla-group api
- for standalone project, we wont return itself as sub project
=> [#1147] create cla group api bugfix

cla-backend-go/utils/email.go, cla-backend/cla/utils.py
=> Docs - Updated v2 Documentation Links

cla-backend-go/swagger/common/gerrit-repo-list.yaml, cla-backend-go/v2/gerrits/service.go
=> Gerrit Repos Swagger Update

cla-backend-go/signatures/handlers.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/cla.yaml, cla-backend/cla/models/docusign_models.py
- Added support for both ICLA and CCLA download via email
=> CCLA PDF Download Email Link Update

cla-backend-go/go.sum, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go
- Add CLA Manager Designees for SF projects associated with a give cla Group
=> Feature/ Add CLA Manager Designee

cla-backend-go/company/repository.go, cla-backend-go/company/service.go
- Added additional user details to company invites table
=> Added Additional Company Request Columns

cla-backend-go/v2/company/handlers.go
- Refactored error messaging for duplicate website and company name
=> [#1342] Bug/v2-Add Org

cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Updated error handling for creating cla manager designee (conflic)
=> [#1377] Feature/Designee conflict

cla-backend-go/package.json, cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/corporate-contributor.yaml, cla-backend-go/v2/signatures/handlers.go, cla-backend-go/v2/signatures/service.go, cla-backend-go/yarn.lock
- Download all Employee Signatures for this CLA Group and company as a CSV file.
=> Added GetClaGroupCorporateContributorsCsv endpoint

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Updated regex for email and full name (swagger)
- Updated Email content sent to designee and user with no LFID
- Check whether project is signed
=> [#1107] Bug/CLA Manager Request

cla-backend-go/serverless.yml
- Resolves issue when deploying to STAGING and PROD
=> Infra - Resolved v4 (EasyCLA v2) API Lambda Name

.circleci/config.yml
- Added v4 service check after deployment for DEV, STAGING, and PROD
=> Infra - Added v4 Service Check after Deploy

cla-backend-go/users/repository.go
- Fixed update on user_github_id field with 'N' type
=> Bug/Update User

cla-backend-go/v2/cla_manager/service.go
- Send email to invited user with no LFID for inviteAdmin flow
=> [#1375] Feature/Invite Email

cla-backend/cla/models/docusign_models.py
- Added error checks for missing CLA Manager name/email while processing
docusign request
=> API - Docusign Error Check

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/sign/service.go
- Updated swagger to include email format/validation
- Added swagger description and examples for email
- Added addition debug and error checks for cla-maanger-designee
=> Swagger Cleanup - Email Validation

cla-backend/cla/controllers/project_cla_group.py, cla-backend/cla/routes.py, cla-backend/yarn.lock
=> API - Added CLA Group Mappings for Python v2 API

cla-backend-go/v2/company/service.go
- Altered Subject in email sent to user that created an organization
=> [#1361] Bug/Email Content Company Profile

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- Added name in payload capturing invited Manager Name details
=> [#1376] Feature/v1 Invite Admin with Name

cla-backend-go/v2/cla_manager/service.go
- Added check for already signed project when creating cla-manager-designee role
=> [#1368] Bug/Already signed - cla manager designee

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/signatures/handlers.go, cla-backend-go/v2/signatures/service.go
- handling multiple errors and improve the status code and error logging.
- Fix the issue reported by Nirupama regarding the status code.
=> [#1233] Download all Employee Signatures for the CLA Group and company as a CSV file api bugfix
