linuxfoundation/easycla

- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/cla_manager/emails.go
- cla-backend-go/v2/cla_manager/service.go
- Added labels to User emails speficying type (GH, LF|EasyCLA)
> [#2739] Feature/Email|Username Labels

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.html
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.scss
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- Enabled v2 PROD links
- Added default/backup fonts to SCSS to address lint warnings
> Enabled Landing Page PROD v2 Links

- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- cla-backend-go/v2/cla_manager/emails.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Refactored swagger spec allowing claGroupID in place of CLAGroup Name
- Updated email content sent to CLA Mgrs with claGroup associated Projects
- Updated unit tests
> [#2736] Feature/Approval List Request

- cla-backend-go/swagger/cla.v2.yaml
- Updated swagger body parameter for claGroupID
> [#2736] Bug/Notify CLA Managers

- cla-backend-go/signatures/service.go
- Specified instructions in list format with bold format
> [#2340] Feature/Contributor Added Instructions

- cla-backend-go/emails/v2_cla_manager_templates.go
- cla-backend-go/v2/cla_manager/emails.go
- Updated notification email to CLA Manager
- Updated contributor request email
> [#2736, #2739] Feature/ Email Updates

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
> Ensure Company ACL Is Set for New Companies

- cla-backend/cla/controllers/github.py
- cla-backend/cla/controllers/project.py
- cla-backend/cla/controllers/signature.py
- cla-backend/cla/controllers/user.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/model_utils.py
- cla-backend/cla/tests/unit/test_event.py
- cla-backend/cla/tests/unit/test_project_event.py
- cla-backend/cla/tests/unit/test_signature_event.py
- cla-backend/cla/tests/unit/test_user_event.py
- cla-backend/cla/utils.py
- Updated table attributes/columns
- Updated create event logic to lookup missing values, when possible
- Updated unit tests
> Added/Updated Python Event Table Attributes

- cla-backend-go/events/repository.go
- cla-backend-go/v2/events/handlers.go
> Added Additional Event Query Logging

- cla-backend-go/cla_manager/service.go
- cla-backend-go/cmd/server.go
- cla-backend-go/emails/cla_manager_templates.go
- cla-backend-go/v2/cla_manager/emails.go
- cla-backend-go/v2/cla_manager/service.go
fixing missing contributor models and missing emailTemplateSvc initializations
addresses ~ [#2756, #2757, #2758]
> post email refactor regressions

- cla-backend-go/approval_list/handlers.go
- cla-backend-go/approval_list/service.go
- cla-backend-go/auth/authorizer.go
- cla-backend-go/cmd/server.go
- cla-backend-go/emails/prefill.go
- Added missing services in cmd/server.go and email templates
- Updated logging
> Resolved Nil Pointer

- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/v2/events/handlers.go
- Updated log events with right parent project details(standalone, multi level types)
- Updated query using parent_project index in the search query
> Bug/Corporate Console Events

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/github_organizations/service.go
- Updated GET endpoint for gh orgs with response installationURL key
> Feature/Get GH orgs response

- cla-backend-go/v2/project-service/client.go
- Resolved project service query by updating base path for client stub calls
> Bug/Project Service

- cla-backend-go/github_organizations/helpers.go
- cla-backend-go/v2/github_organizations/service.go
- Updated installation url path with 'organizations'
> Bug/Installation URL

- cla-backend-go/events/repository.go
- Resolved query for cla-group-events with using event_cla_group_id as index
> Bug/Cla Group Events

- cla-backend-go/project/repository.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/signatures/converters.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- Updated error handling
- Sped up get signature details/metrics routines - decreased PROD AWSF API latency from 11s to 5s
> Updated Get Company Projects Error Handling

- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/common/corporate-contributor.yaml
- Included signatureID in the corporate contributors response
- added docusign date/time if available, otherwise use signature modified date
> Added signature ID to contributors response

- cla-backend-go/v2/cla_manager/service.go
- Resolved masked email showing in event logs
> [#2784] Feature/Event Data for company Admin

- cla-backend-go/events/service.go
> Added Additional Event Logging

- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/project-service/client.go
> Updated Logic to Set the DocuSign Signed Date in the Response Model

- cla-backend-go/events/event_data.go
- cla-backend-go/events/service.go
- Updated activity log with LF Name details
> [#2790] Feature/Activity Log User update

- cla-backend-go/swagger/cla.v2.yaml
- Resolves issue with company with name: Swisscom (Schweiz) AG
> Updated Company and SFID RegEx on v2 APIs

- cla-backend-go/signatures/service.go
- Updated email content with gerrit steps
> [#2795] Feature/Approval Email to Contributor

- cla-backend-go/v2/project-service/client.go
> Added Additional Project Service Logging

- cla-backend-go/cmd/server.go
- cla-backend-go/config/config.go
- cla-backend-go/config/ssm.go
> Added New Platform API Gateway Key

- cla-backend-go/gerrits/repository.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/v2/gerrits/handlers.go
- Updated gerrit query to perform a query instead of a scan
- Updated gerrit query filter - only search gerrits by CLA Group ID - ignore projectSFID
- Updated logging
> Updated Gerrit Query

- cla-backend-go/cmd/server.go
- cla-backend-go/docraptor/client.go
- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/gerrits/lf_group.go
- cla-backend-go/gerrits/repository.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/project/helpers.go
- cla-backend-go/project/repository.go
- cla-backend-go/signatures/handlers.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/gerrit-group-response.yaml
- cla-backend-go/swagger/common/gerrit-user-list.yaml
- cla-backend-go/utils/errors.go
- cla-backend-go/v2/gerrits/handlers.go
- Added GetUsersOfGroup service API
- Added AddUserToGroup service API to add users to a given CLA Group/Gerrit instance
- Added RemoveUserFromGroup service API to remove users to a given CLA Group/Gerrit instance
- Added HTTP API calls to the identity system
- Added event logging
> [#2973] Added Gerrit Add/Remove User from Gerrit Logic

- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/cmd/server.go
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- Invalidate gerrit contributors based on email|domain removals from approval lists
> [#2793] Feature/Invalidate Gerrit Contributors

- cla-backend-go/signatures/repository.go
- Resolved error when getting gerrit users for approval list update
> [#LFX-3147] Bug/ Update Approval List

- cla-backend-go/events/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend/cla/models/dynamo_models.py
- Updated next key logic, added support for CLA Group Next Key
> Resolved CLA Group Event Query NextKey Issue

- cla-backend-go/swagger/requirements.txt
- Resolved CVE-2020-14343 moderate severity Vulnerable versions: < 5.4
Patched version: 5.4 A vulnerability was discovered in the PyYAML
library in versions before 5.4, where it is susceptible to arbitrary
code execution when it processes untrusted YAML files through the
full_load method or with the FullLoader loader. Applications that use
the library to process untrusted input may be vulnerable to this flaw.
This flaw allows an attacker to execute arbitrary code on the system by
abusing the python/object/new constructor. This flaw is due to an
incomplete fix for CVE-2020-1747.
> Updatd PyYAML Lib Vulnerability

- cla-backend-go/signatures/repository.go
- Handled empty ecla list for approval list updates
> [LFX 3147] Bug/Approval List Update (Ecla)

- cla-backend/cla/models/dynamo_models.py
- Added search_missing_event_data_lower() function
- Added type hints
> Added Python Event Function for Searching For Missing Data Lower Column

- cla-backend-go/go.sum
- cla-backend-go/signatures/repository.go
- Ignore invalidate signatures errors raised when updating approval List
> [#LFX 3147] Bug/Approval List

- cla-backend-go/v2/cla_groups/service.go
refactor ListClaGroupsForFoundationOrProject and add some timeout handling for goroutines
addresses : #2818
> refactor ListClaGroupsForFoundationOrProject

- cla-backend-go/signatures/repository.go
- Resolved dereference issue caused during invalidating signature records
>  [#LFX 3147] Bug/Approval List Update

- cla-backend-go/events/service.go
- cla-backend-go/v2/cla_groups/handlers.go
- set cla group id if not set
- set parent project sfid to foundation for projects that don't have
parents
> setting missing fields in event log on creation

- cla-backend-go/go.sum
- cla-backend-go/signatures/repository.go
- added icla signature invalidation upon email removal from approval list
> [#2792] Feature/Approval Update - invalidate ICLA

- cla-backend-go/v2/github_organizations/service.go
- cla-backend/cla/models/dynamo_models.py
- Updated logger functionName output
- Added python get_repository_models_by_repository_sfdc_id helper query
> Updated Logging + Added New Python Query

- cla-backend-go/github_organizations/service.go
- Get GH orgs for Parent/Project or both use cases
> [#2838] Bug/Get Project GH Orgs

- cla-backend-go/signatures/repository.go
- Invalidate icla/ecla resolved by searching email against domain
Signed-off-by: nickmango <wanyaland+nickmango@gmail.com>
> [#2792] Bug/Domain Approval Removal

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_data_test.go
- cla-backend-go/project/handlers.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/project/handlers.go
> adding more information to cla_group.updated event log summary and

- cla-backend-go/signatures/email.go
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/tests/signatures_test.go
- cla-backend-go/utils/email.go
- Added email functionality to icla/ecla users upon signature invalidation (approval list update)
> [#2842] Feature/Invalidation Email alert

- cla-backend-go/events/event_data.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/tests/signatures_test.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/repositories/service.go
- Updated GitHub Org and Repository queries to resolve display issue.
> Resolved [#2838] GitHub Organization Not Displayed on PCC

- cla-backend-go/github_organizations/helpers.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/v2/github_organizations/service.go
> Resolves [#2838] GitHub Organization/Repo Display Issue in PCC

- cla-backend-go/github_organizations/service.go
> Resolved GitHub Query Issue with Missing Parent SFID

- cla-backend-go/signatures/email.go
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/tests/signatures_test.go
- Resolved icla invalidation for email removals
- Resolved email sent for invalidation notification
> [#2792,#2842] Bug/Update Approval List

- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/v2/github_organizations/service.go
- Trap and handle the situation for no repositories
- Remove duplicates
> Updated GitHub Query Logic

- cla-backend-go/signatures/repository.go
> Added Nil Check For Signature Query

- cla-backend-go/v2/cla_groups/handlers.go
> Resolved Event Log Entry for Edit CLA Group

- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/utils/constants.go
- Refactored logic with generic helper function for individual signature invalidation
> [#2792]Refactor/Individual Signature

- cla-backend-go/go.sum
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- Resolved nil pointer issue caused with no gerrit users found
- Resolved wrong user search by using user_email string set field rather than lf_email
> [#2792] Bug/Update Approval List

- cla-backend-go/github_organizations/helpers.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/utils/utils_user_auth_lambda.go
- cla-backend-go/utils/utils_user_auth_standalone.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/service.go
> Added/Updated Logging for GitHub/Repository APIs

- cla-backend-go/events/event_data.go
- cla-backend-go/v2/project/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- Added Additional Debugging for User Permissions Issues
- Resolved Permissions Issue when Querying for Signatures. Lookup projects from Project CLA Group Mapping Table instead of CLA Group fields
> Added Additional Debugging for User Permissions Issues

- cla-backend-go/github_organizations/service.go
- cla-backend-go/repositories/service.go
- cla-backend-go/v2/github_organizations/service.go
- Updated Get GH project org repos logic that resolves the UI unenforcement of CLA
> [#2866] Bug/UnEnforce CLA

- cla-backend-go/events/repository.go
- Added missing fields to match python event log
> Added Date Created/Modified to Event Log

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_data_test.go
- Updated event log text with correct user information
> Resolved [#2651] Event Log Updates

- cla-backend/cla/controllers/signing.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/event_types.py
- Added request_employee_signature_gerrit and request_employee_signature
logging to help track down issue with employee ack for onap
> Added Logging

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/utils.py
- Added string to datetime python helper function to assist with event
log processing - added get_events_type_by_week in dynamo events class
- Added additional logging to docusign routines
> Added String to DateTime Python Helper Function

- cla-backend-go/signatures/email.go
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/tests/signatures_test.go
- Added email for CCLA+ICLA, CCLA+ICLA+ECLA, CCLA cases
> [#2842] Feature/Email for Approval Update

- cla-backend/cla/models/dynamo_models.py
> Added Python Note Field for CLA Group

- cla-backend-go/utils/utils_user_auth_lambda.go
- cla-backend-go/utils/utils_user_auth_standalone.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/events/handlers.go
- cla-backend-go/v2/metrics/handlers.go
- cla-backend-go/v2/sign/handlers.go
- cla-backend-go/v2/signatures/handlers.go
- Added additional permission check logging
- Added permission check for child projects (if any have access, we allow)
- Added missing ctx parameter to permission check functions - to be consistent and have proper logging
> Added Permission Checks Logging

- cla-backend-go/v2/signatures/handlers.go
- Updated check for IsUserAuthorizedForAnyProjects when querying for signatures
> Resolved Issue with Permission Check for Project List

- cla-backend-go/events/event_data.go
- cla-backend-go/events/mock.go
- cla-backend-go/github/branch_protection/mock.go
- cla-backend-go/github_organizations/mock.go
- cla-backend-go/repositories/mock/mock_repository.go
- cla-backend-go/repositories/mock/mock_service.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/github_activity/service_test.go
- Added user name/email to struct, set in call, printout in event log
> Updated Assign Role Scope Event Log Text

- cla-backend-go/signatures/repository.go
- Resolved issue raised in ONAP use case for empty lists
> [#2882]Bug/Approval List Update

- cla-backend-go/cmd/server.go
- cla-backend-go/signatures/email.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/utils/cla_user.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Added API that handles invalidation of ICLA and email notification
> [#2897] Feature/API Invalidation of ICLA

- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/github_activity/service_test.go
> some defensive code against the data coming from github about transferred action

- cla-backend-go/events/event_data.go
- cla-backend-go/signatures/service.go
- cla-backend-go/v2/github_activity/service_test.go
- updated event log, data structures, etc.
> [#2886] Updated Event Log Details for Approval List

- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/project-service/client.go
> Added Defensive Logic to Prevent Setting Enabled Services on TLF Projects

- cla-backend-go/cla_manager/handlers.go
- cla-backend-go/cla_manager/service.go
- cla-backend-go/events/event_data.go
- cla-backend-go/template/service.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- Added authUser object as parameters to service calls
- Added additional debug for templates as well
> Updated the CLA Manager Add/Remove Event Log Text

- cla-backend-go/signatures/repository.go
- Resolved email and email domain approval list removal invalidation for gerrit use cases
> Bug/Invalidate Gerrit

- cla-backend-go/signatures/repository.go
- Resolved failed search for iclas based on signature_reference_name or email
> [#2891] Bug/Search ICLA

- cla-backend-go/signatures/repository.go
- Updated email subject for signature invalidation
> [#2842] Feature/Email Subject

- cla-backend-go/cla_manager/service.go
- cla-backend-go/events/service.go
- Resolved foundation event logging with TLF as parent
- Added logging for cla manager add/removal
- Added lf username to eventargs params
> [#2886] Bug/Event Logging

- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/common/icla-signature.yaml
> Added UserID to ICLA Signature Response

- cla-backend-go/serverless.yml
- cla-backend-go/signatures/handlers.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.v1.yaml
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/utils/auth_user.go
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/signatures/converters.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Signature queries will now return Active, Incomplete, and Disabled signatures in most views
- Updated swagger to allow clients to filter based on approved and signed signatures
- Added USER_AUTH_TRACING to allow printout of user scopes for authenticated users (when needed)
> Updated Signature Queries

- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/common/icla-signature.yaml
- cla-backend-go/swagger/common/signature-summary.yaml
- cla-backend-go/swagger/common/signature.yaml
> Resolved Signature Query Issue

- cla-backend-go/signatures/repository.go
- Added default sort order, updated next key logic
> Added Sort to Project Signature Query

- cla-backend-go/v2/sign/service.go
- Removed logic that returns an error with CLA Signatory does not have
an LFID - it's not required. If they do then fine - we can assign the
cla-signatory role, but if it's missing then it's not a show-stopper.
> Resolved #2938 Signatory Email Not Being Sent

- cla-backend-go/signatures/repository.go
- Resolved issue with project and company query - issue occured when
more than 1 CCLA signature was on file, user specified limit 1, and the
next key was invalid.  Ultimately, the issue was with the next key logic
- it was missing the signature_reference_id in the hash.
> Resolved [#2948] Signature Query for Project and Company

- cla-backend-go/signatures/repository.go
> Resolved CCLA Query Issue

- cla-backend-go/v2/company/service.go
> Resolved 2955 - Fixed Contributor Console Typo

- cla-backend-go/projects_cla_groups/repository.go
- Resolved missing fields [date_created, date_modified, note] for project cla group association
> [#2954] Bug/Create CLA Group

- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/signatures/handlers.go
- Updated search term query logic - now searches for
signature_reference_name_lower, user_email, user_github_username,
user_docusign_name fields. Removed invalid filter when creating
response.
> Resolved PCC-1009 - Search Term Query

- cla-backend-go/v2/signatures/handlers.go
- Removed invalid ICLA check for corporate signatures
- Added permissions check back
> Resolved PCC-1014 Corporate Signature Query

- cla-backend-go/github_organizations/mock.go
- cla-backend-go/github_organizations/models.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/swagger/common/github-organization.yaml
- cla-backend-go/v2/github_organizations/service.go
- Added enabled flag that helps activate/deactivate GH Orgs
> [#PCC-494]Feature/ GH Organization CRUD

- cla-backend-go/.gitignore
- cla-backend-go/Makefile
> Added Build for Mac Arm64

- cla-backend-go/Makefile
> Updated Mac Arm64 Build Output File

- README.md
> Minor README Update

- cla-backend-go/signatures/repository.go
> Resolved V1 Signature Query Issue

- cla-backend-go/github_organizations/repository.go
- cla-backend/cla/models/dynamo_models.py
- Updated GHOrg Model to cater for enabled flag
- Updated Get GhOrganizations endpoint returning enabled orgs
> Feature/ Get GH Org

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.html
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
> Removed Landing Page Request Access Button/Link

- docs/README.md
> Updated Documentation Links

- cla-backend/cla/user_service.py
- Updated log/error log for user service role checks
> User Service Role Checks Cleanup/Debug

- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/models.go
- cla-backend-go/v2/project-service/client.go
- Leveraged project-service summary endpoint
- Updated enroll and enroll endpoints to cater for multi level projects
> Feature/Enroll & Unenroll Projects

- cla-backend-go/tests/project_service_test.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/project-service/client.go
- Resolved context exceeded issue by passing in a valid context object
> [PCC-1165] Added Context to Project Summary API Call

- cla-backend-go/tests/project_service_test.go
- cla-backend-go/v2/project-service/client.go
> Resolve Lint Issue

- cla-backend-go/.golangci.yaml
- cla-backend-go/cmd/functional_tests/cla_manager/cla_manager.go
- cla-backend-go/events/mockrepo.go
- cla-backend-go/github/branch_protection/protected_branch_v4.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/template/handlers.go
- cla-backend-go/template/repository.go
- cla-backend-go/template/service.go
- cla-backend-go/user/repository.go
- cla-backend-go/user/service.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/dynamo_events/autoenable.go
- cla-backend-go/v2/dynamo_events/service.go
- cla-backend-go/v2/dynamo_events/signatures.go
- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- cla-backend-go/v2/template/handlers.go
- Added Defensive Checks for Project Tree Parent - only check parent if parent ID is set
- Resolved a number of lint issues (testing new linter)
> [PCC-1165] Resolved Helper Invalid Memory Address

- .circleci/config.yml
- cla-backend-go/Makefile
- cla-backend-go/swagger/cla.v1.yaml
- cla-backend-go/swagger/cla.v2.yaml
- image: circleci/golang:1.16.5
> Updated golang CI/CD Version

- cla-backend-go/events/event_data.go
- cla-backend-go/template/repository.go
- cla-backend-go/template/service.go
- cla-backend-go/v2/template/handlers.go
- Added/updated event log logic to set project SFID which allows log to
show up on the PCC console, updated event log text
> Resolved PCC-1158 - Event Log Created When Template Updated

- cla-backend-go/events/event_data.go
- cla-backend-go/template/handlers.go
- cla-backend-go/utils/auth_user.go
- cla-backend-go/v2/template/handlers.go
- Adde new and old POC for the data model
- Set new template POC value if set in the event text/output
> Updated Add/Update Template Event Log Message Content

- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- Consolidated CLA Type and Signature Type query parameters into one
- Updated swagger for allowed parameters for signature type
- Updated batch query size from 100 to 1000 - which descreased query times from 37 seconds to 5.78 seconds
> Cleaned Up/Optimized Signature Query

- cla-backend-go/v2/cla_groups/service.go
- Updated error handling for the project to CLA group mapping query
> Resolved/Updated Error Handling for Missing Project to CLA Group Mapping

- cla-backend-go/events/event_data.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/project/handlers.go
> Updated Add/Delete CLA Group Event Log Entries

- cla-backend-go/v2/company/service.go
- Resolved signatory name for active clas for a give company and project
> [#LFX-3163] Bug/ Signatory Details

- cla-backend-go/v2/company/service.go
- Removed cla-manager set for signatory name (active cla-list endpoint)
> LFX-3163 Feature/ Signatory Name

- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
- Resolved GH status update for a company affiliation use case
> Bug/ GH Status Update

- cla-backend-go/v2/project-service/client.go
> Resolved Project Service Parent Nil Pointer Issue

- cla-backend-go/events/service.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/project-service/client.go
> Cleaned up Enroll/Unenroll Issue

- .circleci/config.yml
- cla-backend-go/events/service.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
> Added Logic to Prevent Unenroll of All Projects Under a CLA Group

- cla-backend-go/utils/errors.go
- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
- Changed 500 internal server error to a 400 bad request
- Added custom enroll/unenroll error structure/object to allow us to
determine the type of error
> Updated Enroll/Unenroll Response Code

- cla-backend-go/events/event_data.go
- cla-backend-go/github_organizations/handlers.go
- cla-backend-go/github_organizations/mock.go
- cla-backend-go/github_organizations/repository.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/repositories/mock/mock_service.go
- cla-backend-go/repositories/service.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/dynamo_events/autoenable.go
- cla-backend-go/v2/dynamo_events/github_repository.go
- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/github_organizations/handlers.go
- cla-backend-go/v2/github_organizations/service.go
- cla-backend-go/v2/repositories/service.go
- Removed trailing comma in syntax of query
- Normalized API function calls for Github -> GitHub
- Updated event log message when updating to include branch protection value
> Resolved GitHub Org Update Issue

- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/service.go
> Activity Log Cleanup for Create CLA Group

- cla-backend-go/events/event_data.go
- cla-backend-go/project/repository.go
- cla-backend-go/project/service.go
- cla-backend-go/v2/cla_groups/service.go
> Resolved CLA Group Name/Description Update Issue

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_data_test.go
> Resolved Event Log Unit Test Issues

- cla-backend/cla/models/github_models.py
> Added Additional Debug for GitHub comments

- cla-backend/cla/config.py
- cla-backend/cla/project_service.py
- Updated is stanalone and parent checks for SF projects
> Updated Project Parent Logic in Python

- cla-backend/cla/models/dynamo_models.py
> Resolved GitHub User Index Name Issue

- cla-backend/cla/models/dynamo_models.py
> Resolved User Index Issue

- cla-backend-go/v2/signatures/handlers.go
- Added error details to approval list errors
> Added Additional Error Output for Approval List Errors

- .circleci/config.yml
- updated circleci configuration to build go backend once
> Optimize Go Build

- cla-backend-go/v2/project-service/client.go
- Added a locking mutex around access to a shared cache/map used by
multiple go routines
> Resolved Concurrency Issue

- cla-backend-go/v2/project-service/client.go
> Resolved Minor Lock/Unlock Issue

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/gitlab_organizations/handlers.go
- Added missing project name to forbidden responses
> Added GitLab Org Permissions Feedback

- cla-backend-go/gitlab/client.go
- cla-backend-go/gitlab/client_test.go
- cla-backend-go/gitlab/init.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
> Updated Debug for GitLab

- cla-backend-go/gitlab/auth.go
> Added GitLab Auth Debug

- cla-backend-go/v2/github_organizations/service.go
- Resolved issue which caused the orgs query to fail.
> Resolved GitHub Org Parent Project Issues

- cla-backend-go/v2/github_organizations/service.go
> Resolved Additional Parent Project ID Issue

- cla-backend-go/gitlab/auth.go
> Added More GitLab Auth Debug

- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/cmd/server.go
- cla-backend-go/gitlab/client.go
- cla-backend-go/gitlab/client_test.go
- cla-backend-go/gitlab/init.go
- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/service.go
> Testing GitLab Auth

- cla-backend-go/cmd/gitlab/auth/main.go
- cla-backend-go/config/ssm.go
> Added More Debug for Callback

- cla-backend-go/config/ssm.go
> Testing GitLab Secret Fix

- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/cmd/server.go
- cla-backend-go/config/config.go
- cla-backend-go/config/ssm.go
- cla-backend-go/gitlab/auth.go
- cla-backend-go/gitlab/client_test.go
- cla-backend-go/gitlab/init.go
- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/service.go
> Added GitLab App Client Secret

- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/service.go
> Updated GitLab Group Search

- cla-backend-go/repositories/models.go
- cla-backend-go/swagger/common/gitlab-add-repository.yaml
- cla-backend-go/swagger/common/gitlab-repository.yaml
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/repository.go
> Changed GitLab Repository ID from Int to String

- .circleci/config.yml
- cla-backend-go/v2/repositories/gitlab_services.go
> Added Missing CLA Group to GitLab Repo Insert

- cla-backend-go/repositories/models.go
- cla-backend-go/swagger/common/gitlab-add-repository.yaml
- cla-backend-go/swagger/common/gitlab-repository.yaml
- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/handlers.go
- cla-backend-go/v2/repositories/repository.go
- Changed API call, repleased with all projects query with additional
filters
> Reviewed and Updated GitLab Project Query

- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/repositories/gitlab_services.go
> Updated GitLab WebURL and Path

- cla-backend-go/cmd/server.go
- cla-backend-go/github_organizations/service.go
- cla-backend-go/repositories/constants.go
- cla-backend-go/swagger/common/gitlab-project-repository.yaml
- cla-backend-go/utils/errors.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/repository.go
- cla-backend-go/v2/repositories/service.go
> Added GitLab Repositories to Response

- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/repository.go
> Resolved Add GitLab Org Issue with No Auth

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/gitlab-organization.yaml
- cla-backend-go/swagger/common/gitlab-project-organization.yaml
- cla-backend-go/swagger/common/gitlab-repository-info.yaml
- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/common/models.go
- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/constants.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/service.go
- Added Full Path column/response entity
- Added Web URL column/response entity
- Added constants for column names
- Standardized GL response tags/element names
> Updated GitLab Org Data Model

- cla-backend-go/repositories/models.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/gitlab-add-repository.yaml
- cla-backend-go/swagger/common/gitlab-project-organization.yaml
- cla-backend-go/swagger/common/gitlab-project-repository.yaml
- cla-backend-go/swagger/common/gitlab-repository-info.yaml
- cla-backend-go/swagger/common/gitlab-repository.yaml
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/repository.go
> Updated GitLab Repository Data Models/Responses

- cla-backend-go/v2/gitlab_organizations/service.go
> Added Repository Full Path

- cla-backend-go/cmd/server.go
- cla-backend-go/config/config.go
- cla-backend-go/config/ssm.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/gitlab_sign/handlers.go
- cla-backend-go/v2/gitlab_sign/service.go
- cla-backend-go/v2/store/repository.go
- Added flow for merge request that initiates the sign request
> Feature/Gitlab Redirect Contributor console

- cla-backend-go/tests/utils_context_test.go
- cla-backend-go/utils/context.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/handlers.go
- Added helper functions for adding authUser to the context and fetching the values
> Added Context Helper Functions

- cla-backend-go/gitlab_api/client.go
- cla-backend-go/gitlab_api/client_groups.go
- cla-backend-go/gitlab_api/client_projects.go
- cla-backend-go/swagger/common/gitlab-organization-create.yaml
- cla-backend-go/swagger/common/gitlab-project-organization.yaml
- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/service.go
- Changed org name to group id
- Updated API calls to use Group ID instead of Org Name
> Updated GitLab Onboarding API

- cla-backend-go/swagger/common/gitlab-organization.yaml
- cla-backend-go/v2/common/models.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
> Addeed GitLab External ID to Response & Index Update

- cla-backend-go/v2/gitlab_organizations/service.go
> Resolved GitLab Query Issue

- cla-backend-go/gitlab_api/client_groups.go
- cla-backend-go/serverless.yml
- cla-backend-go/swagger/common/gitlab-organization-create.yaml
- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/dynamo_events/gitlab_webhooks.go
- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/gitlab_sign/service.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/service.go
- cla-backend/serverless.yml
- Added indexes for DB query
- Added query for full path
> Added GitLab Full Path Support

- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
> Updated Docs and Added Full Path to Response

- cla-backend-go/v2/gitlab_organizations/service.go
> Added Check for GL Full Path

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
> Updated Lambda Index Permissions

- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/service.go
> Resolved GitLab Query Bug

- cla-backend-go/swagger/common/gitlab-repositories-add.yaml
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/handlers.go
> Resolved GitLab Lookup Error With No OrgName Value

- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
> GitLab Debug/Cleanup

- cla-backend-go/v2/repositories/gitlab_services.go
- Resolved Query by empty GitLab Group/Org name
- Added go routine for adding repos
> Resolved GitLab Query Issue + Added Go Routine

- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/service.go
> Added Org Name in Callback Workflow

- cla-backend-go/v2/gitlab_organizations/repository.go
> Resolved Duplicate Key Issue in GL Repo

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/repositories/gitlab_services.go
- cla-backend-go/v2/repositories/handlers.go
> Updated GitHub/GitLab Permissions Checks

- cla-backend-go/swagger/common/gitlab-organization-create.yaml
- cla-backend-go/swagger/common/gitlab-organization-update.yaml
- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- change group_name to organization_name to be consistent
> Updated GitLab Organizations Swagger

- cla-backend-go/gitlab_api/client_groups.go
- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/v2/gitlab_organizations/service.go
- Added note to check if the user doesn't have maintainer permissions
when onboarding a gitlab org/group
> Added GitLab Permissions Error Details/Response

- cla-backend-go/cmd/server.go
- cla-backend-go/users/repository.go
- cla-backend-go/v2/gitlab_sign/handlers.go
- cla-backend-go/v2/gitlab_sign/service.go
- cla-backend-go/v2/store/repository.go
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/utils.py
- Updated user_gitlab_attribute call with integer in the repository call
- Updated signature meta data set(v4) and get (v2)
- Updated Store value type in stores table
Signed-off-by: Harold Wanyama <hwanyama@Harolds-MBP-2.local.tld>
> Bug/Gitlab Redirect contributor console

- cla-backend-go/gitlab_api/client_groups.go
- cla-backend-go/v2/gitlab_organizations/service.go
> Cleanup GitLab Error Messages

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
> Added Repository Type Index Lambda Permissions

- cla-backend-go/users/repository.go
- cla-backend-go/utils/conversion.go
- cla-backend/cla/config.py
- cla-backend/cla/controllers/signing.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/routes.py
- Updated create user with emails attribute
- Added gitlab callback endpoint (Docusign callback)
Signed-off-by: Harold Wanyama <hwanyama@Harolds-MBP-2.local.tld>
> Feature/Gitlab Docusign Flow

- cla-backend/cla/controllers/signing.py
- Resolved issue raised by gitlab flow for individual signature
> Bug/Individual Signature

- cla-backend/cla/models/docusign_models.py
- Resolved repository provider check error that blocked icla flow for Gitlab
> Bug/Gitlab ICLA Sign

- cla-backend/cla/models/docusign_models.py
- Resolved lower case check for gitlab/github repo check
> Bug/GitLab ICLA

- cla-backend-go/tests/github_v4_test.go
- cla-backend-go/v2/gitlab-activity/service_test.go
- cla-backend-go/v2/gitlab_sign/service.go
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/utils.py
- Resolved gitlab callback fail upon icla signing
- Updated create user with username attribute for icla flow
> Bug/Gitlab-ICLA Sign

- cla-backend-go/v2/gitlab_organizations/handlers.go
- Resolved parent check for given projectSFID for POST of gitlab org
> Bug/ POST Gitlab

- cla-backend-go/tests/gitlab_access_token_decode_test.go
> Added GitLab Auth Decode Test

- .circleci/config.yml
> Resolved Functional Tests CI/CD Issue

- cla-backend/cla/models/docusign_models.py
- Resolved icla callback to gitlab trigger for MR update
> Bug/MR Update

- cla-backend/cla/models/docusign_models.py
- Resolved repo check for post signing of GitLab/GitHub
> Bug/Emp Acknowedgement Gitlab

- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/model_interfaces.py
- cla-backend/cla/utils.py
- Resolved employee check for gitlab flow
- Updated Signature Pynamo model  with gitlab approval lists
> [#3236] Bug/GitLab ECLA

- cla-backend/cla/models/dynamo_models.py
- Resolved unbound error for gitlab employee ack check
> [#3236]Bug/GitLab Emp check

- cla-backend/cla/models/dynamo_models.py
- Resolve gitlab org check for ecla flow
> Bug/GitLab ECLA

- cla-backend/cla/models/dynamo_models.py
- Resolved logging issue caused on gitlab group approvals
> Bug/GitLab Approval

- cla-backend/cla/models/github_models.py
- cla-backend/serverless.yml
- Updated serverless variable/config to match new serverless constructs
- Resolved issue when github session is a string vs a dict - manually convert string to dict to resolve type issue
> Serverless Cleanup + Resolved Python Session Issues

- .circleci/config.yml
- cla-backend/cla/models/github_models.py
> Resolved Additional GitHub Session Issues

- .circleci/config.yml
> Resolved CI/CD Deployment Config Issue

- cla-backend/cla/models/dynamo_models.py
- cla-backend/serverless.yml
- Resolved bug for gitlab org approval list check
- Updated staging in serverless config
> [$2344] Bug/Gitlab Group ECLA check

- cla-backend-go/events/event_data.go
- cla-backend-go/signatures/service.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
> Updated Activity Log Details for GitLab

- cla-backend/cla/models/docusign_models.py
- Resolved GitLab MR update upon company affiliation
> [#2344] Bug/Company Affiliation

- cla-backend/cla/models/dynamo_models.py
- Applied gitlab url rather than gitlab group name for approval criteria
> Feature/GitLab URL criteria

- cla-backend-go/utils/validators.go
- Edited regex for gitlab org approval list update to handle gitlab.com domain
> Feature/Gitlab URL

- cla-backend/cla/models/dynamo_models.py
- Resolved search for gitlab url with cases with missing 'groups' in url
> [#2344,#2371] Gitlab URL Criteria

- cla-backend/cla/models/docusign_models.py
- Resolved issue raised on MR update for new employee flow
> [#3244,#3271] Bug/Gitlab Employee ack

- cla-backend-go/v2/organization-service/client.go
- Updated client code to match updated swagger specification - several
fields are now optional where we previously needed values. Updated code
to match.
> Updated Organization Service Swagger Client

- cla-backend/cla/utils.py
- Resolved update MR for ecla flow
> [#3271] Update MR

- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- Updated MR trigger for handling gitlab org url approval criteria checks
> [#2371] Feature/GitLab URL approval criteria

- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab-activity/service_test.go
- Resolved gitlab_activity test cases and linting issue
> Bug/Gitlab Activity

- cla-backend-go/serverless.yml
- cla-backend/serverless.yml
> Added GitLab Org URL Index Lambda Permissions

- cla-backend-go/v2/gitlab_sign/handlers.go
- Resolved session check for gitlab oauth sign flow
> [#3243] Bug/GitLab Oauth

- cla-backend-go/cmd/gitlab/project_settings/main.go
- cla-backend-go/v2/gitlab_sign/handlers.go
- Resolved redirect uri issue for gitlab sign request flow
> [#3473#] Bug/GitLab Redirect URI

- cla-backend-go/cmd/gitlab/project_settings/main.go
- cla-backend-go/gitlab_api/auth.go
- cla-backend-go/v2/gitlab-activity/handlers.go
- cla-backend-go/v2/gitlab_sign/handlers.go
- Resolved issue with fetching gitlab oauth token
> [#3473] Bug/GitLab Sign Token

- cla-backend-go/gitlab_api/auth.go
- Updated description for FetchOauthToken
> Bug/ Gitlab Token

- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- cla-frontend-contributor-console/package.json
- cla-frontend-contributor-console/yarn.lock
- cla-frontend-corporate-console/package.json
- cla-frontend-corporate-console/yarn.lock
- cla-frontend-project-console/package.json
- cla-frontend-project-console/yarn.lock
resolved vulnerabilities identified by dependabot:
- tar - GHSA-5955-9wpr-37jh -> update to ^4.4.18
- set-value - CVE-2021-23440 -> update to ^4.0.1
- axios - CVE-2021-3749 -> update to ^0.21.2
- pac-resolver - CVE-2021-23406 -> update to ^5.0.0
> Resolved Vulnerabilities

- cla-backend-go/gitlab_api/auth.go
> [#3297] Lint Issues

- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/gitlab_sign/handlers.go
- Added origin url to session for authorization flow
> [#3297] Bug/Gitlab Session update

- cla-backend-go/v2/gitlab_organizations/handlers.go
- Resolved session values int cast fail
> Bug/GitLab Session auth flow

- cla-backend-go/v2/gitlab_organizations/handlers.go
- Resolved missing key for gitlab_repository_id in session
> Bug/GitLab Session Repo ID

- cla-backend-go/v2/gitlab_organizations/service.go
- Added logging and improved error handling for gitlab sign flow
> [#3297] Bug/Initiate Sign

- cla-backend-go/v2/gitlab_organizations/service.go
- cla-backend-go/v2/gitlab_sign/service.go
- Resolved error handling for gitlab sign flow
> Bug/Pointer Derefecence - Sign

- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/serverless.yml
- cla-backend/yarn.lock
- cla-frontend-contributor-console/package.json
- cla-frontend-corporate-console/package.json
- cla-frontend-project-console/package.json
- cla-landing-page/package.json
- cla-landing-page/yarn.lock
- package.json
- yarn.lock
- Updated axios lib to v0.21.4
- Removed serverless offline lib
> Axios Lib Update

- cla-backend-go/v2/gitlab_sign/handlers.go
- Resolved sign flow for existing user session
> [#3297] Bug/GitLab Client Sign

- cla-backend-go/v2/gitlab_organizations/handlers.go
- Removed salesforce project parent check for gitlab config update
> Bug/GitLab Config Auto Enable

- cla-backend-go/v2/gitlab_organizations/service.go
- Updated error handling to properly identify create user issues
> Resolved Create GitLab User Issue

- cla-landing-page/package.json
- cla-landing-page/src/app/components/home/home.component.ts
- cla-landing-page/yarn.lock
- Added GitLab references to the landing page
- Resolved a number of landing page library vulnerabilities - added
resolution constraints to address them
> [#3321] Added GitLab Text to Landing Page

- .circleci/config.yml
- cla-landing-page/package.json
- cla-landing-page/yarn.lock
> Resolved Landing Page Build Issue

- cla-backend-go/v2/gitlab-activity/service.go
- Updated sign url link on gitlab using same tab
> Feature/GitLab Sign URL

- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/handlers.go
- Handle nil code/state for gitlab oauth callback
> [#3318,#3235] Bug/GitLab Oauth

- cla-backend-go/v2/gitlab_organizations/handlers.go
- Trim trailing "/" for gitlab org fullpath url
> [#3328]Bug/GitLab Org Post

- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/routes.py
- Added gitlab repositories in response for v2/project api
> Bug/Child Project Repos

- cla-backend-go/v2/gitlab_organizations/handlers.go
- cla-backend-go/v2/repositories/repository.go
- Formatted error handling on addition of gitlab group
> [#3328]Feature/GitLab Error Handling

- cla-backend/cla/routes.py
- resolved fetching repos by cla-group-id reference
> Bug/Project Repos

- cla-backend-go/v2/organization-service/client.go
- cla-backend/cla/models/github_models.py
- cla-backend/requirements.txt
- Resolved case for the pygithub query for accessing pr authors
- Updated pyGithub to 1.55
- Updated PyJWT to 2.3.0
> Bug/GH Committers Fail

- cla-backend/cla/models/github_models.py
- Resolved exception handling error for IncompletableObject (pyGithub library)
> Bug/Get Github authors

- cla-backend-go/events/service.go
- cla-backend-go/utils/utils_user_auth_standalone.go
- cla-backend-go/v2/cla_manager/handlers.go
- cla-backend-go/v2/cla_manager/service.go
- cla-backend-go/v2/sign/handlers.go
- while troubleshooting an issue, updating permissions logging for signing
> Updated Sign Handler Permission Logging

- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github_models.py
- Handled invalid author details for PR comment update
Signed-off-by: Harold Wanyama <wanyaland+nickmango+foo@gmail.com>
> Bug/PR Status Update

- cla-backend/cla/models/github_models.py
- Handling invalid author logging bug
Signed-off-by: Harold Wanyama <wanyaland+nickmango+foo@gmail.com>
> Bug/Invalid GH author

- cla-backend/cla/models/github_models.py
- Resolved invalid author for creating PR status
Signed-off-by: Harold Wanyama <wanyaland+nickmango+foo@gmail.com>
> Bug/Invalid Author PR Update

- cla-backend-go/utils/utils_user_auth_lambda.go
- cla-backend-go/utils/utils_user_auth_standalone.go
> Added permissions check debug

- cla-backend/cla/models/github_models.py
- Resolved update status issue - process the correct commit
> Resolved Update Status Issue

- cla-backend/cla/models/github_models.py
- Added logic to retry fetching the GitHub PR when an error occurs.
> Added PR Fetch Retry Logic

- cla-backend-go/utils/email.go
> Resolved Link Error with Documentation

- cla-backend/cla/utils.py
Signed-off-by: David Deal Missing <ddeal+missing@linuxfoundation.org>
> Added Logic to Add Multiple GitHub Labels For Failed PR

- cla-backend/cla/utils.py
- Resolves issue when company is not found
> Added Company Lookup/Load Error Handling

- cla-backend/cla/tests/unit/test_github_models.py
- cla-backend/cla/user.py
- cla-backend/cla/utils.py
> Updated the GitHub Comment Body Logic

- cla-backend/cla/tests/unit/test_user_commit_summary.py
- cla-backend/cla/utils.py
> Working to Resolve Type Error When Generating GitHub Body Text

- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
> Resolved Typo in PR Checks Debug Statement

- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
> Resolved Commit SHA Issue with User Commit Summary Object

- cla-backend/cla/user.py
- cla-backend/cla/utils.py
> Reformatted the GitHub comment block text

- cla-backend/cla/utils.py
> Fixed Git SHA Printout in GH

- cla-backend/cla/user.py
> GitHub Commit - Hide User Public Email

- cla-backend/cla/tests/unit/test_user_commit_summary.py
- cla-backend/cla/user.py
- cla-backend/cla/utils.py
> Added User Tag to GitHub Comment When Missing Authorization

- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/corporate-contributors-list.yaml
- cla-backend-go/v2/company/handlers.go
- cla-backend-go/v2/company/service.go
- cla-backend-go/v2/gitlab-activity/service.go
- updated swagger/api
- updated service layer to pass the next key, page size to the backend query logic
- updated and simplified the DB query logic to support next key and page size values
> Added Pagination to the Company Contributor Query

- cla-backend-go/Makefile
- cla-backend-go/cmd/server.go
- cla-backend-go/go.mod
- cla-backend-go/go.sum
- cla-backend-go/swagger/common/corporate-contributors-list.yaml
- cla-backend-go/v2/company/service.go
- Added totalCount to response
- Resolved lint errors
- Updated download for swagger tool
- Updated linter version
> Added TotalCount for Company Contributors Response

- cla-backend-go/signatures/repository.go
- added logic to search additional fields for user info from UI
> [PCC-1009] - Updated ICLA Search Criteria

- README.md
Signed-off-by: carlos-anhaya-lf <carlos.anhaya.lf@icloud.com>
> add blank space to readme

- tests/UserDevTest.postman_environment.json
Creating PR for test contribution end to end testing
> Test env file

- cla-backend-go/.golangci.yaml
- cla-backend-go/Makefile
- cla-backend-go/cmd/server_standalone.go
- cla-backend-go/cmd/user-subscribe-lambda/cmd/serve_local.go
- cla-backend-go/signatures/email.go
- cla-backend-go/signatures/events.go
- cla-backend-go/signatures/helpers.go
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/common/signature.yaml
- cla-backend-go/tests/github_user_test.go
- cla-backend-go/tests/github_v4_test.go
- cla-backend-go/tests/gitlab_client_test.go
- cla-backend-go/users/repository.go
- cla-backend-go/users/service.go
- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend/cla/models/dynamo_models.py
- updated signature model to include new field, updated swagger spec
which generates the go models
- started plumbing new logic
> Added Initial Auto-Create ECLA Logic

- cla-backend-go/signatures/service.go
> Added Debug to Auto Create ECLA

- cla-backend-go/signatures/service.go
> Added Placeholder for GitHub Status Update

- cla-backend-go/signatures/converters.go
- cla-backend-go/signatures/dbmodels.go
- cla-backend-go/signatures/models.go
- cla-backend-go/signatures/projections.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/model_interfaces.py
- Updated python data model - added support for additional fields
- Updated golang data model - added support for additional fields
> Auto Enable ECLA Database Updates

- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/common/user.yaml
- cla-backend-go/users/repository.go
- cla-backend-go/users/service.go
> Added Logic to Set User Company ID When Auto Enable ECLA

- cla-backend-go/Makefile
- cla-backend-go/signatures/service.go
- cla-backend-go/users/repository.go
- ensure GitHub ID (numeric value) is type Number when inserting into
DynamoDB
> Resolved Type Error For GitHub ID

- cla-backend-go/signatures/repository.go
- for creating ECLA with no name, need a value for the signature reference name/reference lower name columns as they are indexed - cannot be null
> Updated ECLA Signature Create Logic

- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/users/repository.go
- cla-backend-go/users/service.go
- Added date/time to note for user record when auto-creating or updating.
> Updated ECLA Processing Logging Output

- .circleci/config.yml
- .gitignore
> Updated to Node 14 For Serverless Deploy

- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-landing-page/package.json
- cla-landing-page/serverless.yml
- cla-landing-page/yarn.lock
> Updated Landing Page Serverless Version

- cla-backend-go/github/github_repository.go
- cla-backend-go/repositories/mock/mock_repository.go
- cla-backend-go/repositories/mock/mock_service.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/repositories/service.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/v2/repositories/service.go
> Updated Repository Lookup For GitHub Status

- cla-backend-go/github/github_repository.go
> Resolved Nil Pointer Exception

- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
> Added Defensive Checks for GitHub Status Checks

- cla-backend-go/cmd/server.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/service.go
- Fixed panic issue for github validity checks
- Refactored triaging missing and signed github users
> Feature/Ecla Auto Refresh

- .circleci/config.yml
- cla-backend-go/signatures/service.go
- cla-landing-page/package.json
- cla-landing-page/serverless.yml
- cla-landing-page/yarn.lock
> Resolved Nil Pointer Issues

- .circleci/config.yml
> Added Install AWS CLI for Landing Page Deployment

- .circleci/config.yml
- addded --paths value to aws cli
> CI/CD - Landing Page - Invalidate Distribution

- .circleci/config.yml
> Updated AWS CLI Installation

- .circleci/config.yml
- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/users/repository.go
> Resolved ECLA Query Issue

- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/service.go
- updated affiliation logic
- resolved nil pointer
> Updated Affiliation Logic for Updating GitHub

- cla-backend-go/cmd/server.go
- cla-backend-go/config/config.go
- cla-backend-go/config/ssm.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/service.go
- Added comment and status update for missing and signed users
- Added config value for CLA logo URL
> Feature/Cla Comment & status

- cla-backend-go/github/github_repository.go
- Refactored context update for GH auto refresh on ecla creation
> Bug/Status Context

- cla-backend-go/v2/cla_groups/handlers.go
- Added removal of project cla group association for the delete action for a cla Group
> [#3603] Feature/ CLA Group Deletion

- cla-backend-go/v2/cla_groups/helpers.go
- Resolved validation issue for cla group deletion
> Bug/Uneroll Cla groups validation

- cla-backend-go/v2/cla_groups/helpers.go
- Removed validation check for CLA for child projects already enlisted under Foundation CLA
> [#3638]Feature/Create CLA for child under Umbrella CLA

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Added endpoint that updates the auto-create-ecla column for a given claGroup and company
- Added event handling
> [#3640] Feature/ Ecla auto create API

- cla-backend-go/v2/cla_groups/handlers.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/models.go
- cla-backend-go/v2/cla_groups/service.go
- Added validation check for project level CLA when enrolling sibling projects
- Added ProjectStack models to handle traversing projectTree by levels
> Feature/Enroll Validation

- cla-backend-go/v2/cla_groups/service.go
- Resolved display for child level CLAs at foundation level
> [#PCC-2606] Displaying Child level CLA

- cla-backend-go/github_organizations/service.go
- cla-backend-go/v2/github_organizations/service.go
- Resolved Get for GH orgs for a given grandchild enrolled at foundation level CLA
> [#PCC-2601] Github Org details for grandchild project

- cla-backend-go/repositories/repository.go
- cla-backend-go/v2/github_activity/service.go
- cla-backend-go/v2/repositories/service.go
- Removed project_sfid and repository_sfdc_id attributes on disabling a repo
- Updated project_sfid and repository_sfdc_id on enabling/re-enabling
> [#PCC-2601] Feature/Enable and Disable Repositories

- cla-backend-go/repositories/mock/mock_repository.go
- Resolved mock interface issue for updating GH function:wq
> [#2601] Bug/Update Github

- cla-backend-go/Makefile
- cla-backend-go/cmd/repository_project_update/main.go
- Added script that removes project details from disabled repositories
> [#PCC-2601] Repositories Data cleanup

- cla-backend-go/v2/github_organizations/service.go
- Resolved fetching GH orgs at the foundation level
> Bug/Get Project GH orgs

- cla-backend-go/v2/company/service.go
- Resolved fetching project details for 2nd tier salesforce project having multiple projects
> Bug/Parent Level fetching CLAs

- cla-backend-go/v2/dynamo_events/cla_manager.go
- Removed foundation level check when assigning cla-manager role and use associated salesforce projects
> Bug/Signature Event for CLA Manager assignment

- cla-backend-go/v2/github_organizations/service.go
- Resolved fetching GH orgs for a given salesforce project
> [#2622] Bug/Get Project GH orgs

- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
- Resolved validation check issue when creating CLA
> Bug/Validation Create CLA

- cla-backend/package.json
- cla-backend/serverless.yml
- cla-backend/yarn.lock
Reverts communitybridge/easycla#3686
> Revert "Updated Serverless Version"

- cla-backend-go/v2/gitlab_organizations/repository.go
- Fetch gitlab orgs using the gitlab project index only
> [#PCC-2652] Feature/Project GitLab orgs

- cla-landing-page/src/app/app.component.html
- cla-landing-page/src/app/app.component.ts
- cla-landing-page/src/app/app.module.ts
- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/app/components/home/home.component.ts
- cla-landing-page/src/app/core/services/lfx-header.service.ts
> feat: updated lfx header v2

- cla-landing-page/src/app/app.component.ts
- cla-landing-page/src/environments/environment.dev.ts
- cla-landing-page/src/environments/environment.prod.ts
- cla-landing-page/src/environments/environment.ts
> feat: updated lfx header cdn from angular vars

- cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
- cla-landing-page/src/app/components/home/home.component.ts
- cla-landing-page/src/app/core/services/lfx-header.service.ts
> feat: updated lfx header query selectors

- .circleci/config.yml
- cla-backend-go/package.json
- cla-backend/package.json
- cla-landing-page/package.json
- cla-landing-page/yarn.lock
- resolved landing page deployment issue, problem is with file-type library updates
> Package and CI/CD Updates

- .circleci/config.yml
- .github/dependabot.yml
> Added Dependabot Configuration

- .circleci/config.yml
> CI/CD Remove Staging Deployment

- .github/workflows/snyk-scan-npm-landing-page-pr.yml
- .github/workflows/yarn-scan-backend-go-pr.yml
- .github/workflows/yarn-scan-backend-pr.yml
- .github/workflows/yarn-scan-landing-page-pr.yml
- cla-backend-go/package.json
- cla-backend-go/serverless.yml
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- cla-landing-page/serverless.yml
- added yarn scanning for landing-page, python backend and go backend
- remove file-type dependency update as this breaks serverless
- normalized serverless version in serverless file and node package import
> Updated Dependencies + Added Yarn Scanning

- .circleci/config.yml
- cla-backend-go/Makefile
- cla-backend-go/package.json
- cla-backend-go/serverless.yml
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/serverless.yml
- cla-backend/yarn.lock
- resolves serverless error deploying to dev
> CI/CD - Serverless Deployment Updates

- cla-backend-go/v2/github_organizations/service.go
- Reverted [#PCC-2622] that discarded fetching github orgs for enrolled child projects
> [#2722] Revert Parent/Child GH Orgs

- cla-backend-go/Makefile
- cla-backend-go/tests/v2_cla_manager_templates_test.go
- resolved unit test issue with text update
- added output to the Makefile after unit test runs
> Updated Unit Test Criteria

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- removed tests for prod deployment (already done in merge to main)
- ensure jq is installed prior to testing the health endpoints
> CI/CD - Updated GitHub Action PROD Deployment

- .github/workflows/deploy-prod.yml
- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
> CI/CD - Resolved Production Deployment

- cla-backend-go/swagger/common/gitlab-organization.yaml
- cla-backend-go/v2/common/models.go
- cla-backend-go/v2/gitlab-activity/service.go
- Updated gitlab org model swagger spec leveraging gitlabOrgService queries
> [#3537] Bug/GitLab Model

- cla-backend-go/v2/gitlab-activity/service.go
- cla-backend-go/v2/gitlab_organizations/service.go
- Updated gitlab author in gated PR with login and name details
> Feature/ GitLab author details

- .github/workflows/build-pr.yml
> CI/CD - Remove AWS Secrets from Build PR Job

- cla-backend-go/v2/gitlab-activity/handlers.go
- always return 200 from GitLab requests as they can disable the webhook
on non-200 responses. We don't want that!
> GitLab - Updated Callback Response Logic

- cla-backend-go/v2/gitlab-activity/service.go
- Updated gitlab author details with username and name
> Feature/GitLab MR Author

- cla-backend-go/v2/signatures/service.go
- added new logic to walks through each page of ICLA signatures and
returns the complete list.
> Resolved ICLA CSV Limit Issue

- cla-backend-go/gitlab_api/mr.go
- cla-backend-go/v2/gitlab-activity/service.go
- Resolved conflict getting commit authors with search by ID other than full name
> [#3768] GitLab commit Authors

- cla-backend-go/v2/cla_groups/service.go
- This fix addresses a use case when we have a project under a Parent
Project/Foundation and this project is the only project in the list,
then we need to set the foundation SFID to the current project SFID
value. This addresses the issue when we have a parent project and child
project situation where the parent has a CLA Group and this is a
request to create a new CLA Group for the child project - this is new
logic that we added to support nested CLA groups where some child
projects can inherit the CLA Group from the parent project while other
child projects can have their own CLA Group.
> [#3773] - Create CLA Group Issue Under Parent

- cla-backend-go/cmd/gitlab_repository_check/handler/handler.go
- cla-backend-go/v2/repositories/repository.go
- Edited gitlab repo fetch by orgname other than prefix search
- Handled edge cases with no repos returned for a given gitlab org
> Bug/Gitlab Repo Check

- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
> Rolled Back Vulnerability Update - Broke Serverless

- cla-backend-go/gitlab_api/mr.go
- Resolved fetching gitlab user with email search
> [#3657] Bug/GitLab MR gate

- cla-backend-go/gitlab_api/mr.go
- cla-backend-go/v2/gitlab-activity/service.go
- Fallback handled in case search by email and name fails
> Bug/Fetch Gitlab User

- cla-backend-go/gitlab_api/mr.go
- Handled case of gitlab user not matching by email check
> Bug/GitLab User search

- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/cla.v1.yaml
- cla-backend-go/v2/company/service.go
- Resolved search with filtering at the db level
> [#LFX-3198] Bug/Contributers search

- cla-backend-go/gitlab_api/mr.go
- cla-backend-go/v2/gitlab-activity/service.go
- Default to payload author details
> Bug/Get Gitlab Author details

- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/cla_manager/service.go
- Updated cla_maanger_designee endpoint removing foundation check to cater for multi level cla_groups in a project heirachy
- Resolved child creation of a CLA group with existing CLA at the Parent
> [#3773][#LFX-3206] Foundation|Project Fixes

- cla-backend-go/users/repository.go
- cla-backend-go/v2/gitlab-activity/handlers.go
- cla-backend-go/v2/gitlab-activity/service.go
- Added check for email by user_emails field
- process all emails for potential signups
> [#3795] Bug/ICLA check

- cla-backend-go/v2/company/service.go
- Handled whitespaces in search term
> Bug/ Corporate Company contributors search

- cla-backend-go/events/repository.go
- cla-backend-go/swagger/common/event-list.yaml
- Added results count to activity log response
> Feature/Events Pagination

- cla-backend-go/events/repository.go
> Resolved Lint Error

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- cla-backend-go/Makefile
- cla-backend-go/auth/auth0.go
- Updated golangci-lint to v1.51.2
- Resolved lint error when closing response body (was ignoring error response)
- Updated CI/CD go version to 1.20.1
> Lint - Updated Lint Version + Resolved Lint Issue

- cla-backend-go/signatures/service.go
- cla-backend-go/utils/auth_user.go
- cla-backend-go/v2/signatures/handlers.go
- On API update to turn on the AutoCreateEcla feature, we should also
work to create ECLA records for those individuals on the approval list
> Auto Create ECLA Updates

- .github/workflows/deploy-staging.yml
- cla-backend-go/events/mock.go
- cla-backend-go/events/mockrepo.go
- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/cla_groups/service.go
- cla-backend-go/v2/events/handlers.go
- cla-backend-go/v2/project-service/client.go
- Added search capability on event_data values
> Feature/ Events Search

- cla-backend-go/v2/signatures/service.go
- added total count and project ID to CCLA signature response object
> Resolved Missing Total Count and Project ID From CCLA Response Object

- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Resolved fetching company and project contributors
- Added pagination feature
> [#PCC-2669] Bug Get Company Contributors

- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/v2/events/handlers.go
- Resolved next key validation error
- Resolved multiple orgs
- Fixed parent & child activity log entries shown for a given project
> [#CDC-1647][#3817] Bug/Next Key

- cla-backend-go/events/repository.go
- added filter criteria to resolve missing filter
> Updated GetCompanyClaGroupEvents

- cla-backend/cla/models/dynamo_models.py
- Fetched ecla signature with approved and signed as true
> [#3824] Bug/Ecla signature check

- cla-backend/cla/models/dynamo_models.py
- Revert fetching latest signature
> Revert fetching latest signature

- cla-backend-go/events/event_data.go
- adjusted the activity log text
> Updated Activity Log Text for Auto-create ECLA

- cla-backend-go/v2/gitlab-activity/service.go
- added additional logic to lookup the GitLab user by ID
> GitLab - Updated GitLab User Search Logic

- cla-backend/cla/models/github_models.py
- Added fallback for searching users by github username
> [#3834]Feature/PR github username search

- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- updated aws-sdk to ^2.1329.0
- updated file-type to ^16.5.4
> CI/CD - Updated aws-sdk lib + file-type list

- cla-backend-go/cmd/server.go
- cla-backend-go/events/mockrepo.go
- cla-backend-go/events/repository.go
- cla-backend-go/events/service.go
- cla-backend-go/v2/events/handlers.go
- Fetch company project events by claGroupIDs
> [#3827] Feature/Company Project Events

- cla-backend-go/events/mock.go
- updated GetCompanyClaGroupEvents function arguments in the mock object to match the service interface
> Resolved Unit Test Mock Object Issue - GetCompanyClaGroupEvents

- cla-backend-go/v2/project-service/client.go
- Resolved adding cla groups for projects under LLC umbrella.
> [#3786] CLA group creation for LLC Umbrella Projects

- cla-backend-go/utils/project_helpers.go
- Factored in fetching of Projects LLC cla groups
> Feature/ Projects LLC cla groups

- cla-backend-go/tests/project_helpers_test.go
- cla-backend-go/utils/project_helpers.go
- cla-backend-go/v2/cla_groups/helpers.go
- cla-backend-go/v2/project-service/client.go
- Falsify LF Projects LLC as root parent unit test case
- Removed cases of LF Projects LLC in root parent checks
> Bug/LF Projects as Root Parent test

- cla-backend-go/v2/gitlab-activity/service.go
- Fetched cla user by user_emails instead of lf_email
> [#3816]Bug/Fetch Gitlab user by email

- cla-backend-go/v2/gitlab-activity/service.go
- Handled check against all gitlab users found by email
> [#3816]Feature/Get gitlab users by email

- cla-backend-go/v2/events/handlers.go
- Resolved use case of fetching events for a given foundation
> [#3827]Bug/Foundation Level CLAs

- cla-backend-go/users/repository.go
- Resolved query by string set value by user emails when searching for a user
> [#3816] Bug/User Emails search

- cla-backend-go/v2/cla_groups/service.go
- Ignore errors when fetching invalid cla-groups
> [#PCC-2846] Bug/Get Foundation CLA

- cla-backend-go/users/repository.go
- cla-backend-go/v2/gitlab-activity/service.go
- Resolved gitlba icla status check with multi cla records
> [#3863,#3816] Bug/Gitlab ICLA sign

- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/common/corporate-contributor.yaml
- Added approved and signed status for company contributors
> [#CD-1707] Feature/Ecla Status

- cla-backend-go/gitlab_api/mr.go
- cla-backend-go/v2/gitlab-activity/handlers.go
- cla-backend-go/v2/gitlab-activity/service.go
- Added /easycla command feature that enables MR check against the EasyCLA bot
> [#3844]Feature/Gitlab Command

- cla-backend-go/gitlab_api/webhook.go
- added logic to subscribe to notes/comments
> GitHub - Subscribe to Comments

- cla-backend-go/gitlab_api/mr.go
- Update existing PR instead of new comment for /easycla command trigger
> [#3844] Feature/Gitlab easycla comment

- cla-backend-go/v2/gitlab_organizations/repository.go
- cla-backend-go/v2/gitlab_organizations/service.go
- Show all gitlab orgs under foundationsfid
> [#3796] Feature/Project Gitlab orgs

- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
- Added co-author user fetch by email
> [#3884]Feature/Fetch Github User

- cla-backend/cla/models/github_models.py
- Added co-committer in Github PR checks when gating
> [#3884] Feature/Co-Committer

- cla-backend/cla/models/github_models.py
- Added ignore case for web-flow author
> Feature/Ignore Web flow author

- cla-backend/cla/models/github_models.py
This reverts commit 1ebe05ba390d90ab639e503c68115bb8564b57c7.
> Revert "Feature/Ignore Web flow author"

- cla-backend/cla/models/github_models.py
- Ignored web-flow login in committer details
> [#3903] Bug/Committer Web flow

- cla-backend-go/v2/company/service.go
- Resolved getting signature status for company|project contributors
> [#3900] Bug/Contributor Signature status

- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
- Leveraged organisation installation details to fetch github user by email
> [#3903] Bug/Missing ID

- cla-backend-go/package.json
- cla-backend/package.json
> Feature/ Vuls fix

- cla-backend-go/signatures/repository.go
- Fetch all company contributors irrespective of the signed and approved status
> [#3900] Feature/Fetch all contributors

- cla-backend/cla/models/github_models.py
- Updated co-author ignoring failed user searches by email
> [#3884] Bug/Co-author update

- cla-backend/cla/models/github_models.py
- Added search by name to make comparisons with search by email
> [#3844] Co-author Search

- cla-backend-go/signatures/repository.go
- Remove duplicate contributors for a given company project
> [#3920] Bug/Duplicate signatures

- cla-backend/cla/models/github_models.py
added case if previously cla passed and by removing user from whitelist, it should be restricted on CLA check
> resolved multiple CLA check comment

- cla-backend-go/signatures/repository.go
- Resolved pagination issue for employee acknowledgements endpoint
> [#3948] Bug/Employee Acknowledgement

- infra/README.md
> feat: updated docs

- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- Resolved dynamo query when updating approval list previously having wrong queries for existing eclas
> [#3936] Bug Update Approval List

- cla-backend-go/signatures/service.go
- Added goroutine handler for processing ecla signature check
> [#3936]Bug/Update Approval

- infra/README.md
> WIP feat: updated readme copies (test)

- cla-backend/cla/routes.py
- Disabled auth check for the /v2/user endpoint
> Feature/User Endpoint auth

- cla-backend/requirements.txt
- urllib3 update with a lower version handling compatability
> Library update

- cla-backend/cla/models/github_models.py
- Handled failed exceptions when getting co-author details resolving missingID
- Refactored search using email
> [#3884] Bug/Co Author Fetching user

- cla-backend/cla/models/github_models.py
- Handle github search by email with an empty list
> [#3884] Bug/Fetching user by email

- cla-backend-go/company/repository.go
- cla-backend-go/company/service.go
- cla-backend-go/swagger/common/org.yaml
- Added ccla enabled flag for org searches
- Used concurrency to improve performance
> [#3972] Feature/Org Search

- cla-backend/cla/models/github_models.py
- Added enqueue action item for a given pull request handling the new merge queue feature
> [#3846] Feature/Merge Queue

- cla-backend/cla/controllers/github.py
- Handled Merge queue for a given PR event
> [#3846] Feature/PR Enqueue

- cla-backend/cla/controllers/github.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
- Added gate checks for the new merge_queue GH feature
> [#3846] Feature/Merge Group Gating

- .github/workflows/deploy-dev.yml
- Commented v2 health check due to depracated use of salesforce causing failures
> Bug/ v2 Health Check

- .github/workflows/deploy-dev.yml
This reverts commit 0d0090741f6b82ac6ac685c7cb5197f248b4b8a7.
> Revert "Bug/ v2 Health Check"

- cla-backend/cla/models/github_models.py
- Resolved check for pull requests and merge queue events
> [#3846] Bug/Pr and Merge Queue activity

- cla-backend/cla/config.py
- cla-backend/cla/models/github_models.py
- Resolved Pr fetch for merge_group event
> [#3846] Bug/Fetch PR for Merge Queue

- cla-backend/cla/config.py
> Bug/Config Fetch

- cla-backend/cla/models/github_models.py
- Resolved fetching commit authors for merge_group
> Bug/Get commit Authors

- cla-backend/cla/models/github_models.py
- Resolved error fetching cla repository
> Bug/Merge Queue Repo

- cla-backend/cla/models/github_models.py
- Resolved handling user commits
> Bug/Merge Group Update

- cla-backend/cla/models/github_models.py
- Resolved fetching sign url for signed users
> [#2846] Bug/Sign URL

- cla-backend/cla/models/github_models.py
- Create commit for merge_group_sha head
> Bug/Create Commit for sha

- cla-backend/cla/models/docusign_models.py
- cla-backend/requirements.txt
This reverts commit b88ba3ba77b7bb902937bd931f6480569f3ce612.
> Revert "resolved issues"

- cla-backend/cla/models/github_models.py
- Handled enqueued action for a given PR added to a merge group
> [#3844] Bug/Enqueued Action

- cla-backend-go/github/github_repository.go
- cla-backend-go/utils/validators.go
- Updated validation for github and gitlab handles allowing .
> [#4006] Bug/Approval List handles

- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/github_models.py
- Handle signature query by reference_id with a none last_evaluated_key
> Bug/Signature Query

- cla-backend/cla/models/docusign_models.py
- cla-backend/serverless.yml
- Changed authentication using oauth2.0
> Feature/Docusign Authentication

- cla-backend/serverless.yml
- Removed docusign  private key loading from serverless
> Bug/Docusign private Key

- cla-backend/cla/config.py
- cla-backend/cla/models/docusign_models.py
- cla-backend/serverless.yml
- Added support for oauth2 using jwt grant flow
> [#3970] Feature/Docusign Oauth Implementation

- tests/functional/cypress.env.json
- tests/functional/cypress/e2e/cla-manager.spec.ts
- tests/functional/cypress/e2e/events.spec.ts
- tests/functional/cypress/fixtures/cla-manager/assignCLAManager.json
- tests/functional/cypress/fixtures/cla-manager/createCLAManager.json
- tests/functional/cypress/fixtures/cla-manager/createCLAManagerDesignee.json
- tests/functional/cypress/fixtures/cla-manager/isCLAManagerDesignee.json
- tests/functional/cypress/fixtures/events/getProjectEvents.json
- tests/functional/cypress/support/commands.js
- tests/functional/run-local-cli.sh
Added cypress test case for cla-Manager API services 
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/cla-manager
> Added cypress test case for cla-manager API

- cla-backend/cla/models/docusign_models.py
- cla-backend/requirements.txt
- Added oauth setup for docusign auth flow
- Changed library for getting s3 document using requests package
> [#3970,#4095]Feature/Docusign Authentication

- cla-backend/requirements.txt
- Added missing cryptography==41.0.2 package
> [#3970,4002] Bug/Docusign Authentication flow

- package.json
- tests/functional/cypress.config.ts
- tests/functional/cypress/e2e/cla-group.spec.ts
- tests/functional/cypress/e2e/cla-manager.spec.ts
- tests/functional/cypress/e2e/events.spec.ts
- tests/functional/cypress/e2e/foundation.spec.ts
- tests/functional/cypress/e2e/github-organizations.spec.ts
- tests/functional/cypress/e2e/github-repositories.spec.ts
- tests/functional/cypress/e2e/metrics.spec.ts
- tests/functional/cypress/fixtures/metrics/getClaManagerDistribution.json
- tests/functional/cypress/fixtures/metrics/getCompanyMetric.json
- tests/functional/cypress/fixtures/metrics/getProjectMetric.json
- tests/functional/cypress/fixtures/metrics/getTopCompanies.json
- tests/functional/cypress/fixtures/metrics/getTopProjects.json
- tests/functional/cypress/fixtures/metrics/getTotalCount.json
- tests/functional/cypress/fixtures/metrics/listCompanyProjectMetrics.json
- tests/functional/cypress/fixtures/metrics/listProjectMetrics.json
- tests/functional/cypress/support/commands.js
- tests/functional/package.json
- tests/functional/yarn.lock
- yarn.lock
Added cypress test case for metrics API
- https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/metrics
> Added cypress test case for metrics API

- cla-backend-go/signatures/constants.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/metrics/repository.go
- after updating the linter, we encountered a few additional lint
issues. This PR resolves the lint issues by adding the nolint comment
since the issues identified are not problems
> Resolved Go Lint Issues

- .github/workflows/build-docker-pr.yml
- .github/workflows/deploy-dev.yml
- cla-backend/Dockerfile
- cla-backend/requirements.txt
- cla-backend/serverless.yml
> CI/CD - ECR/ECS Python Deployment Test

- cla-backend/serverless.yml
> CI/CD - Fixed Serverless Variable Reference Issue

- cla-backend/Dockerfile
> Resolved Dockerfile Add/Copy Issue

- .github/workflows/build-docker-pr.yml
- .github/workflows/deploy-dev.yml
- cla-backend/Dockerfile
- cla-backend/Makefile
- cla-backend/run-docker-shell.sh
- cla-backend/run-docker.sh
- fixed import/copy/add
- resolved architecture in CI/CD GitHub action
> Dockerfile Updates

- tests/functional/cypress/appConfig/config.dev.ts
- tests/functional/cypress/e2e/gitlab-organizations.cy.ts
- tests/functional/cypress/fixtures/gitlab-organizations/addProjectGitlabOrganization.json
- tests/functional/cypress/fixtures/gitlab-organizations/getGitLabGroupMembers.json
- tests/functional/cypress/fixtures/gitlab-organizations/getProjectGitlabOrganizations.json
- tests/functional/cypress/fixtures/gitlab-organizations/updateProjectGitlabGroupConfig.json
- tests/functional/cypress/support/commands.js
-Added cypress test case for Gitlab-organizations API
- https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/gitlab-organizations
> Cypress test case for gitlab-organizations

- tests/functional/cypress/e2e/gitlab-repositories.cy.ts
- tests/functional/cypress/fixtures/gitlab-repositories/enrollGitLabRepository.json
- tests/functional/cypress/fixtures/gitlab-repositories/getProjectGitLabRepositories.json
- Added cypress test case for gitlab-repositories API
- https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/gitlab-repositories
> Cypress gitlab repositories

- tests/functional/cypress/e2e/health.cy.ts
- tests/functional/cypress/e2e/version.cy.ts
- tests/functional/cypress/fixtures/health/healthCheck.json
- tests/functional/cypress/fixtures/version/getVersion.json
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/version
> Cypress version

- cla-backend-go/v2/sign/jwt.go
- Used the right variables for the integrator key and user_id
> Bug/Env Variables for Docusign

- cla-backend-go/v2/sign/docusign.go
- Use the static ssm config value for the docusign account Id
> Feature/Docusign Account ID

- cla-backend-go/cmd/server.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/sign/handlers.go
- cla-backend-go/v2/sign/service.go
- Updated payload for the docsign webhooks accepting json
- Moved callbacks to v4
> Feature/Docsign Payload

- cla-backend-go/v2/sign/handlers.go
- cla-backend-go/v2/sign/service.go
- Resolved docusign callback URL for icla
> Bug/callback URL

- cla-backend-go/v2/sign/models.go
- cla-backend-go/v2/sign/service.go
- Updated payload model for icla
> Webhook Payload

- cla-backend-go/v2/sign/service.go
- Updated base URL for docusign flow
> Docusign Callback URL

- cla-backend-go/cmd/server.go
- Resolved implementation error of the cla_group API handlers
> [#4202] Bug/Cla_group CRUD APIs

- cla-backend-go/v2/sign/service.go
- Reverted test callback url for ccla docusign flow
> Feature/Docusign callback URL

- cla-backend-go/v2/sign/service.go
- Resolved use case for 2 PRs for unsigned ICLA
> [#4210]Bug/Double PR ICLA

- cla-backend-go/v2/sign/service.go
- Updated the base URL for callback handler on Gitlab icla flow
> Bug/Gitlab Callback

- cla-backend/cla/models/docusign_models.py
- Resolved signature saving by shifting to the boto3 packge from pynamodb
> Bug/Request Employee Signature

- cla-backend-go/v2/sign/service.go
- cla-backend/cla/models/docusign_models.py
- Resolved wrong date_modified format for ccla signature
- Handled none values for ecla signature_reference_name attribute
> [#4225,#4228] Bug/Incorrect date format for ccla

- cla-backend/cla/utils.py
- Changed flow for icla and ccla checks for an invalidated contributor use case
> [#3897]Feature/ICLA and ECLA use case

- cla-backend-go/github_organizations/repository.go
- Resolved issue when deleting/disassociating a given gh org for a salesforce project
> [#4084] Bug/Dissassociate gh org

- cla-backend-go/repositories/models.go
- cla-backend-go/repositories/repository.go
- cla-backend-go/swagger/common/github-repository.yaml
- cla-backend-go/v2/github_organizations/service.go
- Resolved gh org deletion by factoring clagroup signed level
> [#4084]Bug/Github Org Delete

- cla-backend-go/repositories/mock/mock_repository.go
- Resolved mock repository interface for the new function `GitHubDisableRepositoriesOfOrganizationParent`
> [#4084] Bug/Mock Repositories Unit Test

- cla-backend-go/cmd/server.go
- cla-backend-go/v2/sign/handlers.go
- cla-backend-go/v2/sign/service.go
- Implemented gerrit request icla and callback for docusign sign flow
> [#4002] Feature/Gerrit Sign

- cla-backend-go/v2/sign/service.go
- Resolved return url for the docusign flow
> [#4240] Bug/Gerrit Return URL

- cla-backend-go/events/event_data.go
- cla-backend-go/v2/sign/service.go
- Resolved email and dispatch events for docusign auth flow
- Fixed the s3 Upload
> [#4249] Bug/Email & Event Dispatch Docusign

- cla-backend-go/cmd/server.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/swagger/common/approval-item.yaml
- cla-backend-go/swagger/common/corporate-signature.yaml
- cla-backend-go/swagger/common/corporate-signatures.yaml
- cla-backend-go/v2/signatures/converters.go
- cla-backend-go/v2/signatures/service.go
- Added event_date for added on time for an approval list item
- Updated the json response for the company signatures API to reflect these changes
> [#3750] Feature/Approval List date

- cla-backend-go/events/repository.go
- cla-backend-go/signatures/converters.go
- cla-backend-go/swagger/cla.v1.yaml
- cla-backend-go/v2/signatures/converters.go
- Added project_sfid on events fetching datetime values for approval list items
> [#3750] Bug/Approval List Child Projects

- cla-backend-go/serverless.yml
- Added permission for the events table project-sfid-event-type-index
> [#3750] Feature/Events Index permission

- cla-backend-go/serverless.yml
- Added permission for querying event-project-sfid-event-type-index
> [#3750] Bug/ Events Index Permission

- cla-backend-go/v2/sign/service.go
- Resolved issue for signatory signed callback
> [#4247]Bug/Docusign CCLA callback

- cla-backend-go/v2/sign/service.go
- Added the right cla manager email post signing
- Associated SFcompany with the event
> [#4247] Feature/Email and event logging

- cla-backend-go/v2/signatures/converters.go
- Reverted approval date added to use signature_modified in the interim(perfomance issue)
> [#3750]Bug/Approval Date Reverted

- cla-backend/cla/models/github_models.py
> uncomment co-author commit

- cla-backend-go/gerrits/lf_group.go
- cla-backend-go/v2/sign/service.go
- Added user to ldap group upon icla && ccla signing
> [#4240]Feature/Gerrit Icla

- cla-backend-go/gerrits/lf_group.go
- cla-backend-go/gerrits/service.go
- cla-backend-go/v2/sign/service.go
- Handled nil pointer execption for auth user
- Handled email send for icla
- Added ldap group for corporate callback
> [#4240] Bug/LDAP Gerrit LDAP group addition

- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/dynamo_models.py
- Resolved signature update for the gerrit employee signature update
> [#4273] Request Ecla - Gerrit

- cla-backend-go/approval_list/models.go
- cla-backend-go/cmd/dynamo_events_lambda/main.go
- cla-backend-go/cmd/migrate_approval_list/main.go
- cla-backend-go/cmd/server.go
- cla-backend-go/events/mockrepo.go
- cla-backend-go/events/repository.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/utils/constants.go
- cla-backend-go/v2/approvals/models.go
- cla-backend-go/v2/approvals/repository.go
- cla-backend-go/v2/signatures/converters.go
- cla-backend-go/v2/signatures/service.go
- Added script to migrate approval list details to the cla-<stage>-approvals table
- Updated the signatures table with the right date_added column
> [#3846] Feature/Approval List Date Added

- cla-backend-go/cmd/migrate_approval_list/main.go
- cla-backend-go/events/mockrepo.go
- cla-backend-go/events/repository.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/approvals/repository.go
- Added delete args in script for deleting all records
- Added concurrency
- Handled aws exception with retries
> [#3750]Feature/Update Approval List Script

- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/approvals/repository.go
- Update approval api to handle add/remove
> Feature/Approval Status

- cla-backend-go/cmd/gitlab_repository_check/handler/handler.go
- Updated signature repo arguments
> Bug/Signature Repo config

- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/signatures/converters.go
- Resolved approval items update of date_added attribute
> [#3750] Bug/ Company Project Signatures

- cla-backend-go/serverless.yml
- Added permission acess querying approvals table with indices
> [#3750]Bug/Approval Index Permissions

- cla-backend-go/serverless.yml
- Addressed the permissions role limit for the serveless framework
> [#3750]Bug/Lamda Perms Limit

- cla-backend-go/serverless.yml
- Updated PutItem and a host of other permissions for cla-<stage>-approvals table
> Feature/Approvals Table Update

- cla-backend-go/cmd/migrate_approval_list/main.go
- Enhanced event search with cla_group_id filter
> Bug/Approval List filter

- cla-backend-go/v2/cla_manager/service.go
- Updated User name attribute to make it more generic
> [#4236] Feature/Enhance Email notification email

- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github.py
- cla-backend/cla/tests/unit/test_github_models.py
- cla-backend/cla/utils.py
- Added generated date for comment body
> [#4195] Feature/bot comment edit

- cla-backend/cla/tests/unit/test_event.py
- cla-backend/cla/utils.py
- Resolved bug for datetime modified hidden element
> [#4195] Bug/User Summary Body

- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github_models.py
- cla-backend/cla/utils.py
- Handled co-author with invalid email use case (missing ID)
> Feature/Co-author Invalid email

- cla-backend/cla/controllers/github_application.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github_models.py
- Added label identifying the EasyCLA status for the Github search feature
> [#3577] Feature/PR Label

- cla-backend/cla/models/github_models.py
- Fixed missing param with orgname for the update_pull_request function
> Bug/Update PR Label

- cla-backend/cla/controllers/github_application.py
- cla-backend/cla/models/github_models.py
- Fixed wrong path name for repository in the PR labels update api
> Bug/Label Update

- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github_models.py
- Resolved test case for PR label update
> Bug/Label Unit Test

- cla-backend/cla/models/github_models.py
- Resolved param entry item for organisation name in the update PR function
> Bug/Github org PR

- cla-backend/cla/controllers/github_application.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/tests/unit/test_github_models.py
This reverts commit 10e22326f3d77b46deec307b7d47fc0aa48381aa.
> Revert "[#3577] Feature/PR Label"

- cla-backend-go/cla_manager/service.go
- Resolved email body to feature the right project name for cla manager addition and removal
> [#3498]Bug/Add & Remove CLA Manager Email

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- cla-backend/yarn.lock
- Update pip before installing packages CI/CD pipeline
> Feature/Pip Upgrade

- cla-backend-go/package-lock.json
- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/requirements.txt
- cla-backend/yarn.lock
> [#3966] Feature/Vulnerabilities

- cla-backend/requirements.txt
- Auto resolved package dependencies for boto3
> [#3966] Vulnerabilities Fix

- cla-backend-go/swagger/cla.v1.yaml
- Updated regex for companyName search parameter to resolve missing special characters
> [#3581] Bug/Organisation Search

- .github/workflows/build-pr.yml
> Bug/Go Dependecies

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
Reverts communitybridge/easycla#4347
> Revert "Bug/CD Dev"

- .github/workflows/build-pr.yml
- cla-backend-go/package.json
- Upgraded serverless package resolving snyk vulnerability
> Bug/Serverless Vul

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- Upgraded node version
- Updated the deploy script for both prod and dev for v2(golang) apis
> Bug/Serverless Upgrade

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- Cleanup of node module packages to handle serverless upgrade
> Bug/Package Cleanup

- cla-backend-go/package.json
- Reverted to the older serverless package due to deploy issues
> Bug/Serverless Package

- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/signatures/handlers.go
- cla-backend-go/v2/signatures/service.go
- Added endpoint /cla/authorization that returns whether a given lfid user is authorized
> [#4357]Feature/LFID authorized status

- cla-backend-go/users/models.go
- cla-backend-go/users/repository.go
- Resolved fetch by lfusername bug caused due to string set map value of user emails
> [#4348]Bug/User Fetch unmarshalling

- cla-backend-go/gerrits/service.go
- Resolved fetching repo list for https://mockapi.gerrit.dev.itx.linuxfoundation.org instance
> [#4395] Bug/Gerrit Instances

- .github/workflows/build-pr.yml
- cla-backend-go/package.json
- cla-backend-go/yarn.lock
- cla-backend/package.json
- cla-backend/yarn.lock
- Addressed fast-xml-parser and ws vulnerability issues
> Bug/Vulnerability Fixes

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
- Use dev branch to handle dev updates
> Feature/Dev Branch

- cla-backend-go/cmd/ldap_gerrit_check/main.go
- Script that checks activity logs for a project and lfusername
> [#4394] Feature/Script

- .github/workflows/build-pr.yml
- cla-backend/cla/utils.py
- Updated the missing ID help link
> [#4428]Feature/Missing ID Help Link

- cla-backend-go/Makefile
- Upgraded lint version to v1.61.0
> Feature/Golang Lint version

- cla-backend-go/gerrits/service_test.go
- Resolved repo list in the test case
> [#4395]Bug/Test case

- cla-backend-go/signatures/repository.go
Reverts communitybridge/easycla#4469
> Revert "[#4460] Feature/Corporate contributors dups"

- cla-backend-go/signatures/service.go
- cla-backend-go/signatures/service_test.go
- added case insensitive search for emails
> [#4472] Approval List search

- cla-backend-go/cla_manager/service.go
- cla-backend-go/emails/cla_manager_templates.go
- cla-backend-go/emails/cla_manager_templates_test.go
- cla-backend-go/emails/prefill.go
- cla-backend-go/projects_cla_groups/mocks/mock_repository.go
- cla-backend-go/projects_cla_groups/repository.go
- cla-backend-go/v2/cla_manager/service.go
> [#3498] Bug/Email Template

- docs/contributor-api.md
- Added markdown for sequence flow for a contributor who is gated
> Feature/Contributor Sequence flow

- cla-backend-go/cla_manager/service.go
- cla-backend-go/emails/cla_manager_templates.go
- Updated email params on cla group for cla managers
> [#3498]Bug/CLA Manager Email

- cla-backend-go/v2/sign/service.go
- Used input return url value for post signing ICLA
> Bug/Gerrit Return URL

- cla-backend/cla/tests/unit/test_ecla.py
cc @mlehotskylf @amolsontakke3576 @thakurveerendras
> Fix missing license header

- cla-backend-go/v2/sign/service.go
Set correct Gerrit return URL.
cc @mlehotskylf
> Gerrit return URL

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
Reverts communitybridge/easycla#4515
> Revert "Test main branch on dev environment without doing a prod release"

- utils/find_non_acked_signatures_after_date.sh
cc @mlehotskylf @thakurveerendras
> New util script to mass update signatures embargo_acked flag

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- cla-backend-go/signatures/repository.go
- cla-backend/requirements.txt
- utils/cla_group_corporate_contributors.sh
- utils/company_project_contributors.sh
Fixes https://github.com/communitybridge/easycla/issues/4519
> 4519: Fix edge case - when there are no corporate contributors

- .github/install-dependencies.yml
- .github/workflows/deploy-dev.yml
Try to fix the failing dev deployment
> Try to fix the failing dev deployment

- .github/workflows/deploy-dev.yml
Reverts communitybridge/easycla#4536
> Revert "Try newest versions 2"

- .github/workflows/deploy-dev.yml
Reverts communitybridge/easycla#4535
> Revert "Try newest versions"

- .github/workflows/deploy-dev.yml
Reverts communitybridge/easycla#4543
> Revert "Fix?"

- utils/check_unique.sh
- utils/cla_authorization.sh
- utils/lookup_cla_group_sf.sh
- utils/lookup_examples.sh
- utils/lookup_sf.sh
- utils/lookup_user_by_lfid.sh
- utils/lookup_user_by_lfid_sf.sh
- utils/lookup_user_sf.sh
Util scripts for [this investigation](https://docs.google.com/spreadsheets/d/1INQMWSMV9RKNRHRiRBYAcuO5WMRYM4tM0NFilJZOHtI/edit?usp=sharing).
PTAL & merge as this won't break anything (it only adds shell scripts to investigate authorization cases).
> Added utils/investigation scripts

- .github/workflows/build-pr.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
> Check if CI workflow is fixed

- cla-backend-go/auth/authorizer.go
- utils/get_companies_go.sh
- utils/get_company_by_external_id_go.sh
- utils/get_company_py.sh
- utils/request_corporate_signature_go_post.sh
- utils/request_corporate_signature_py_post.sh
- utils/search_company_go.sh
- utils/test_sanctioned_flag.sh
- utils/update_company_is_sanctioned.sh
All company related APIs in both v3 and v4 return `isSanctioned` flags - to test on dev call any of those APIs for a single company that I've marked as sanctioned:
That company is (on `dev`):
- name: `Cloud Native Computing Foundation`.
- UUID: `0ca30016-6457-466c-bc41-a09560c1f9bf`.
- External ID/SFID: `0014100000Te0yqAAB`.
I can mark any other company as "sanctioned" if needed for testing @amolsontakke3576 cc @mlehotskylf 
Also see various API calls and sanctioned flag returned:
```
root@darkstar:~/go/src/github.com/communitybridge/easycla# DEBUG='' ./utils/get_company_by_external_id_go.sh 0016s000006UKKqAAO
{
"companyACL": null,
"companyExternalID": "0016s000006UKKqAAO",
"companyID": "10bde6b1-3061-4972-9c6a-17dd9a175a5c",
"companyName": "The Linux Foundation Duplicate",
"created": …
```
> Support isSanctioned flag in all APIs + util scripts

- cla-backend/cla/models/dynamo_models.py
cc @mlehotskylf @jarias-lfx followup for slack [discussion](https://linuxfoundation.slack.com/archives/C0697E1QHNG/p1747899743085879?thread_ts=1747859052.071759&cid=C0697E1QHNG).
> Change expire TTL cla-{stage}-store for active_signature:{uuid} keys

- cla-backend/cla/controllers/repository_service.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/routes.py
- utils/get_user_from_session_py.sh
> Allow get_redirect_url param

- utils/search_aws_log_group.sh
- utils/search_aws_logs.sh
This just adds utils to lookup EasyCLA AWS logs across all log groups cc @mlehotskylf @amolsontakke3576 @dealako @thakurveerendras @jarias-lfx
> Logs lookup utils for EasyCLA

- CHECK_PR.md
- cla-backend-go/signatures/email.go
cc @mlehotskylf additionally we need this: https://github.com/communitybridge/easycla/issues/4488#issuecomment-2918443160.
> Update references to 'Not Covered' text

- cla-backend-go/swagger/cla.v1.yaml
- cla-backend-go/swagger/common/user-compat.yaml
- cla-backend-go/swagger/common/user.yaml
- cla-backend-go/users/handlers.go
- cla-backend-go/users/models.go
- cla-backend-go/users/repository.go
- cla-backend-go/users/service.go
- cla-backend-go/v2/signatures/mock_users/mock_service.go
- cla-backend/cla/routes.py
- docs/Python_APIs_updates.md
- tests/py2go/README.md
- tests/py2go/api_test.go
- tests/py2go/dynamo.go
- utils/get_user_compat_go.sh
cc @mlehotskylf - this is `wip`.
> Port '/v2/user/<uuid>' py API to '/v3/user-compat/<uuid>' go API

- README.md
- WHITELISTING_BOTS.md
- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/github/bots.go
- cla-backend-go/github_organizations/models.go
- cla-backend-go/signatures/service.go
- cla-backend-go/swagger/common/github-organization.yaml
- cla-backend-go/v2/sign/helpers.go
- cla-backend-go/v2/sign/service.go
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/event_types.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/routes.py
- utils/describe_all.sh
- utils/describe_table.sh
- utils/list_tables.sh
- utils/skip_cla_entry.sh
cc @mlehotskylf @jarias-lfx - this is `WIP` will continue on this tomorrow.
> Add support for whitelisting bots

- WHITELISTING_BOTS.md
- cla-backend-go/github/bots.go
- cla-backend/cla/models/github_models.py
- utils/skip_cla_entry.sh
This is only to update debugging info and logs so I will merge this once CI passes cc @mlehotskylf
> Add more visibility and fix one dminor debugging message in another function

- WHITELISTING_BOTS.md
- cla-backend-go/github/bots.go
- cla-backend-go/swagger/common/github-organization.yaml
- cla-backend/cla/models/github_models.py
- utils/skip_cla_entry.sh
> Refactor to support array of configs, additional name pattern and make email & name patterns optional + update util scripts and docs

- WHITELISTING_BOTS.md
- cla-backend-go/github/bots.go
- cla-backend-go/swagger/common/github-organization.yaml
- cla-backend/cla/models/github_models.py
cc @mlehotskylf @ahmedomosanya
> Clarify what login is used for vs username, account for GitHub bots (like Copilot) having no login but only email

- BOT_ALLOWLIST.md
- README.md
- cla-backend-go/github/bots.go
- cla-backend-go/signatures/service.go
- cla-backend-go/v2/sign/helpers.go
- cla-backend/cla/models/github_models.py
cc @mlehotskylf @ahmedomosanya
> Use inclusive naming 'whitelist' -> 'allowlist'

- cla-backend-go/cmd/server.go
- cla-backend-go/go.mod
- cla-backend-go/go.sum
Generated with [OpenAI](https://platform.openai.com/)
> Add logging v3/v4 API calls

- CO_AUTHORS.md
- cla-backend-go/github/github_repository.go
- cla-backend/cla/models/github_models.py
- tests/functional/README.md
- utils/calculate_api_stats.sh
- utils/count_apis.sh
- utils/search_aws_log_group.sh
- utils/search_aws_logs.sh
- Update finding by GitHub username.
- Updates to log API calls from all versions.
More details: [on slack](https://linuxfoundation.slack.com/archives/C0697E1QHNG/p1755753777859899?thread_ts=1755709282.893649&cid=C0697E1QHNG).
Generated with [OpenAI](https://platform.openai.com/) Assisted by [OpenAI](https://platform.openai.com/)
> Update finding by github username (step 4)

- CO_AUTHORS.md
- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/service.go
- cla-backend-go/users/mocks/mock_repo.go
- cla-backend-go/users/repository.go
- cla-backend-go/users/service.go
- cla-backend-go/v2/sign/helpers.go
- cla-backend-go/v2/signatures/mock_users/mock_service.go
- cla-backend/cla/controllers/user.py
- cla-backend/cla/models/dynamo_models.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/models/model_interfaces.py
- cla-backend/cla/utils.py
This implements https://github.com/linuxfoundation/easycla/issues/4760.
Details on the ticket.
cc @mlehotskylf @ahmedomosanya @jarias-lfx 
> Update co-authors searching algorithm - support lookup easyCLA DynamoDB database by emails

- .gitignore
- cla-backend/cla/controllers/github.py
- cla-backend/cla/models/dynamo_models.py
- utils/search_aws_log_group.sh
Fixes https://github.com/linuxfoundation/easycla/issues/4759 cc @mlehotskylf @jarias-lfx @ahmedomosanya 
> Fix #4759 bug - no `organization_installation_id` update

- cla-backend/cla/models/github_models.py
> Update handlers to also support enqueued PR

- cla-backend/cla/models/dynamo_models.py
- utils/search_aws_log_group.sh
> Fix github installation_id

- utils/count_apis.sh
This is related to https://github.com/linuxfoundation/easycla/issues/4762
It updates the API calls aggregation script to generate useful reports like this:
```
N API path
279784 /v2/github/activity
20305 /v4/ops/health
20220 /v3/ops/health
1909 /v2/repository-provider/github/sign/<id>/<id>/<id>
1009 /v2/project/<uuid>
837 /v2/user/<uuid>
634 /v4/company/<sfid>/project/<sfid>/cla
372 /v4/company/<uuid>/project/<sfid>/events
358 /v2/github/installation
331 /v3/organization/search
258 /v4/project/enabled/<sfid>
228 /v4/metrics/total-count
215 /v4/company/<uuid>/project/<sfid>/cla-managers
214 /v2/user/<uuid>/active-signature
200 /v4/request-individual-signature
181 /v4/signatures/project/<sfid>/company/<uuid>
168 /v2/return-url/<uuid>
154 /v4/signed/individual/<id>/<id>/<id>
151 …
```
> Unicron aggregate used api calls

- tests/functional/README.md
- tests/functional/cypress.config.ts
- tests/functional/cypress/appConfig/config.dev.ts
- tests/functional/cypress/appConfig/config.production.ts
- tests/functional/cypress/e2e/cla-group.cy.ts
- tests/functional/cypress/e2e/cla-manager.cy.ts
- tests/functional/cypress/e2e/company.cy.ts
- tests/functional/cypress/e2e/docs.cy.ts
- tests/functional/cypress/e2e/events.cy.ts
- tests/functional/cypress/e2e/foundation.cy.ts
- tests/functional/cypress/e2e/github-organizations.cy.ts
- tests/functional/cypress/e2e/github-repositories.cy.ts
- tests/functional/cypress/e2e/githubActivity.cy.ts
- tests/functional/cypress/e2e/gitlab-organizations.cy.ts
- tests/functional/cypress/e2e/gitlab-repositories.cy.ts
- tests/functional/cypress/e2e/health.cy.ts
- tests/functional/cypress/e2e/metrics.cy.ts
- tests/functional/cypress/e2e/projects.cy.ts
- tests/functional/cypress/e2e/signatures.cy.ts
- tests/functional/cypress/e2e/version.cy.ts
- tests/functional/cypress/support/commands.js
- tests/functional/cypress/support/e2e.js
- tests/functional/package-lock.json
- tests/functional/package.json
- tests/functional/run-single-test.sh
- tests/functional/utils/prettier.sh
- tests/functional/utils/run-single-test.sh
- tests/functional/yarn.lock
cc @mlehotskylf - this is for https://github.com/linuxfoundation/easycla/issues/4762.
> Fixing cypress functional test coverage - WIP

- utils/get_all_functions_configs.sh
- utils/get_all_ssms_values.sh
- utils/get_function_config.sh
- utils/get_ssm_value.sh
- utils/get_ssms_values.sh
- utils/list_aws_functions.sh
- utils/list_ssm_parameters.sh
> New utils to get AWS functions configuration and SSM values

- tests/functional/cypress/e2e/cla-group.cy.ts
- tests/functional/cypress/support/commands.js
> Update test coverage to be able to run locally (no GW) and by using deployed dev version (with ACS and GW)

- tests/functional/cypress/e2e/cla-manager.cy.ts
This is for https://github.com/linuxfoundation/easycla/issues/4762
As expected, small followup fix.
> Fix one test case

- cla-backend-go/github/github_repository.go
- cla-backend/cla/models/github_models.py
- cla-backend/cla/utils.py
> Final updates related to detecting comment body changes and stable sort of signed/missing SHAs per authors/co-authors

- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/v2/sign/helpers.go
- cla-backend-go/v2/sign/service.go
- cla-backend/cla/models/docusign_models.py
- utils/delete_user_repository_project_signature.sh
- utils/search_aws_log_group.sh
- utils/search_aws_logs.sh
> Add logging of ECLA signed/ack events and invatlidate caches on those events

- COMMIT_AUTHORS_CACHING.md
- cla-backend-go/events/event_data.go
- cla-backend-go/events/event_types.go
- cla-backend-go/github/github_repository.go
- cla-backend-go/signatures/repository.go
- cla-backend-go/swagger/cla.v2.yaml
- cla-backend-go/v2/sign/handlers.go
- cla-backend-go/v2/sign/helpers.go
- cla-backend-go/v2/sign/service.go
- cla-backend/cla/models/docusign_models.py
- cla-backend/cla/models/github_models.py
- cla-backend/cla/routes.py
- utils/clear_cache_go.sh
- utils/clear_cache_py.sh
- utils/delete_user_repository_project_signature.sh
- utils/search_aws_log_group.sh
- utils/search_aws_logs.sh
> Add support for commit authors caching

- cla-backend-go/github/github_repository.go
> Detecting 'failed CLA' comment if CLA failed due to missing commit author
