linuxfoundation/easycla

cla-backend/cla/models/github_models.py, cla-backend/cla/utils.py
1. Removes hyperlink for cla-sign status badge.
2. Adds https://lfcla.com as hyperlink for `detail` link for successful signs.
=> Removed sign_url hyperlink for badge and added lfcla.com for detail link

cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.html, cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.scss, cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
Given a user of the project console (project.*.lfcla.com)
When the user clicks the "CONFIGURE GITHUB REPOSITORIES" button associated with a CLA group of a project, and clicks on one of the projects to "ADD" them
Then a loading animation (spinner) appears next to the repo name until added
Then display "REMOVE"
Given the load times out
Then an error message displays to the user within the context of the "View signatures" Modal
=> Visual Cue: Loading: Project Console: Add Repo to CLA Check

cla-backend-go/cmd/server.go, cla-backend-go/docs/doc.go, cla-backend-go/docs/handlers.go, cla-backend-go/swagger/cla.yaml
- Added /api-docs endpoint for the API documentation
=> Add Go Services API Documentation Endpoint

cla-backend/cla/routes.py, cla-backend/cla/utils.py
- Show lfcla.com if all commits are signed else show sign url if there are few unsigned, like detail link
- Changed SVG to PNG in routes, related to PR [94](https://github.com/communitybridge/easycla/pull/94l)
=> Add link badge

cla-backend/cla/controllers/repository_service.py, cla-backend/cla/routes.py, cla-backend/cla/utils.py
- Load PR badge icons from S3.
- Removed the functions which serves badges from lambda
=> load badge icons from s3 instead of lambda

cla-backend-go/Makefile
- removed lambda build flags for Linux testing locally
=> Golang Build Linux Locally

cla-backend/cla/controllers/user.py
Fixed references to EasyCLA and CLA Manager to conform with branding and role naming
Signed-off-by: Mike Dolan <mdolan@linuxfoundation.org>
=> Fixed references to EasyCLA and CLA Manager

cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.scss, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
Given the projects page on the project manager console
When the page loads
Then the following text appears with "Get Access" linked to: https://docs.linuxfoundation.org/x/QRZx [NOTE: Currently internal LF doc only]:
"Don't see your projects here?
Get Access"
=> CLA-907: Help for PMs to get access to Projects

cla-backend/cla/models/github_models.py
- Updated logic to only add a comment when the check fails
Resolves: #167
=> GitHub Contributor - Don't Add Comment when CLA Check Passes

cla-frontend-corporate-console/src/ionic/modals/projects-ccla-select-modal/projects-ccla-select-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html, cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts
- Resolved issue by filtering data for empty/null project names.
- Trimmed whitespace for project names to fix sorting issue
- Rolled back object/embed PDF view page control since we want to avoid using external service that may not be accessible to all users
=> Company Unsigned Project Error

cla-backend-go/cmd/root.go, cla-backend-go/cmd/server.go, cla-backend-go/company/handlers.go, cla-backend-go/company/repository.go, cla-backend-go/company/service.go, cla-backend-go/swagger/cla.yaml, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Added query company by user manager v3 go endpoint - replaces v1/v2 python
- Added new company by user manager plus invites query v3 go endpoint - useful
to return a list of companies and pending invites for a given user -
in support of the UX
- added UI endpoints for UI team to leverage
=> Company Query by User Manager and Combined User and Invite Query

cla-backend-go/signatures/repository.go, cla-backend-go/swagger/cla.yaml, cla-backend/cla/__init__.py, cla-backend/cla/config.py, cla-backend/cla/controllers/signature.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/test_utils.py, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.html, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- Updated logic to detect when bots are added to the GitHub whitelist
- Auto-creates a bot user in the EasyCLA system when a bot is added to the GitHub whitelist
- Auto-creates a bot signature in the EasyClA system when a bot is added to the GitHub whitelist
- Added database node column support for users and signatures tables
- Attempted to clean up logging config
- Added defensive code to Go backend when looking up signatures
- Updated project/signatures response model to include the signature reference id, version and created/modified date/time values
- Added company name to whitelist modals
- Added GitHub bot note to the GitHub whitelist modal
- Provided company and project name details to whitelist modal parameters
- Added company name to corporate console company page
Resolves: #284 …
=> Allow Bots to be Whitelisted and Affiliated Automatically

cla-backend/cla/controllers/signature.py, cla-backend/cla/routes.py, cla-frontend-corporate-console/src/ionic/app/app.scss, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.html, cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.ts, cla-frontend-corporate-console/src/ionic/models/cla-signature.ts, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html, cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts
- refactored github org whitelist to allow freeform input
- added regex validator for github org whitelist
- removed specialization logic for github org whitelist to check based on users github permissions
- updated python service handler to accept github_org_whitelist values (like the other whitelists)
- added info/warning message for form validation errors
- updated whitelist title and button labels
Resolves: #293
=> GitHub Org Whitelist: Allow freeform input

cla-frontend-project-console/src/ionic/pages/login/login.html
- Per discussions with the support team, removed the invalid support email on the login page
=> Project Console - Support Email Incorrect

cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.ts, cla-frontend-contributor-console/src/ionic/services/cla.service.ts, cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.ts, cla-frontend-corporate-console/src/ionic/services/cla.service.ts, cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html, cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
Add release version somewhere on the website, probably the footer so we know what version of EasyCLA is deployed.
=> Add release version to website

cla-backend-go/Makefile
=> Set Golang Build Flag to ensure binary is statically linked

cla-frontend-contributor-console/serverless.yml, cla-frontend-corporate-console/serverless.yml, cla-frontend-project-console/serverless.yml
- updated configuration to reduce Default and Max Cache times (TTL) in an
attempt to address user/UI issues related to problems after a release
Resolves: #526
=> Updated CloudFront Cache Control Settings

cla-backend-go/project/handlers.go, cla-backend-go/project/repository.go, cla-backend-go/project/service.go, cla-backend-go/swagger/cla.yaml, cla-backend-go/whitelist/service.go, cla-backend/serverless.yml, infra/index.ts, tests/rest/test_v3_project_api.tavern.yaml
- Added logic to prevent duplicate CLA groups from being created
- Added new GSI for DynamoDB for project_name
- Added GetProjectByName API endpoint and implementation
- Updated Create logic to check if project name or external ID exists
- Fixed lint issue in whitelist
- Renamed GetProject to GetProjectByID to be more clear
- Added functional tests
Resolves #610
=> Prevent Duplicate CLA Groups

.circleci/config.yml
- Updated to node12 for serverless deployment to fix the recent error
messages are showing up:
An error occurred: ClientEdgeLambdaFunction - The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: c334b1cc-d348-4a45-a5fd-c1b854c06932).
=> Use Node12 for serverless deploy

infra/get-ssm-parameters.ts, infra/index.ts
- Adjusted read capacity for Gerrit and GitHub tables
- Adjusted read and write capacity for metrics table
- Deployed changes to DEV, STAGING, and PROD - tested in DEV
=> Adjusted Infra Read and Write Capacity

cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.html, cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.scss, cla-frontend-corporate-console/src/ionic/modals/view-cla-managers-modal/view-cla-managers-modal.ts, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html, cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss
Added below points.
1. wrap word in table view.
2. Trim project name to 25 characters in dialog.
3. Added tooltip for trimmed content.
=> Missing data and Overlap issues when Project name is too long

cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
=> Corporate Console - Tool tip is not displayed for + icon to add cla manager in Manage White list page

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
Issue was when group name having long single word (without space). Ideally it should not be present but I have added solution.
=> Solved issue of long text with no space

cla-backend-go/events/repository.go
- /recent/evetns will return events where project_id is present and contains_pii = false
=> /recent/events will return events only when event is associated with project

cla-backend-go/package.json, cla-backend-go/serverless.yml, cla-backend-go/yarn.lock, cla-backend/package.json, cla-backend/serverless.yml, cla-backend/yarn.lock
- Added serverless-prune-plugin + config to clean up old version of our
lambdas which was causing "Code storage limit exceeded" errors
- Updated/Upgraded serverless dependencies (yarn.lock)
=> Infra - Added Serverless Prune

cla-backend-go/package.json, cla-backend/package.json
- Added prune:{dev|staging|prod} script targets to manually prune the
code versions for Lambdas to avoid "Code storage limit exceeded" errors
=> Added Serverless Prune Script Target

.circleci/config.yml
- Updated golang build version to 1.14.2
=> Updated CircleCI Golang Build Version

infra/index.ts
- Added company_id_external_project_id column to the attributes list since it was referenced in an index
=> Resolved DynamoDB Events Table Index Configuration Issue

cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.html, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.scss, cla-frontend-corporate-console/src/ionic/modals/add-company-modal/add-company-modal.ts
Added validation to the Company Name to max 60 characters which is perfect for docusign pages.
=> Corporate Console - Company name is displayed outside the document in docusign when company name is too long

cla-frontend-project-console/src/ionic/constants/general.ts
- Updated get access link on the project console to direct users to the
help desk link
=> [#1096] - Get Access Link Update

.circleci/config.yml
- Now that the functional tests are working properly, I removed
halt_build_on_fail=false condition to allow failed functional tests to
fail the CI/CD workflow
=> Enabled Functional Test Gating

.circleci/config.yml, cla-backend-go/cmd/functional_tests/approval_list/approval_list.go, cla-backend-go/cmd/functional_tests/health/health.go, cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/cmd/functional_tests/test_models/common.go, cla-backend-go/cmd/server.go, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/serverless.yml, cla-backend-go/service_discovery/service_discovery.go, cla-backend-go/signatures/errors.go, cla-backend-go/signatures/service.go, cla-backend-go/users/repository.go, cla-backend-go/users/service.go, cla-backend-go/utils/signature_utils.go, cla-backend-go/v2/signatures/handlers.go, cla-backend/serverless.yml, infra/index.ts
- Added Logic to Send Emails to CLA Managers
- Added Logic to Send Emails to Contributors when email or GH Username is added/removed from the Approval List
- Updated Functional Tests to use API-GW/ACS endpoint
- Added additional functional test users
- Added Get user by Email service/db function
- Added Logic to create events when Approval list is updated
=> [#1135] Approval List v2 API

cla-backend-go/cmd/functional_tests/org_service/org_service.go, cla-backend-go/serverless.yml, cla-backend/serverless.yml
- Set the debug flag to true for logging API requests to the core platform
=> Added API DEBUG in CloudWatch Log

infra/index.ts
Extend CORS rules to `cla-signature-files-...` bucket.
Included explicit `region` attribute to align with other bucket configurations.
=> Add CORS rules to `cla-signature-files-...` bucket

cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
- Resolved issue identified by Code Scanning Alert: External links that
open in a new tab or window but do not specify link type 'noopener' or
'noreferrer' are a potential security risk. Added anchor attributes.
=> Resolved Potentially Unsafe External Link

cla-backend-go/v2/cla_manager/service.go
- Assigned cla-manager role rather than contact when user has no LFID
=> Bug/ No LFID cla manager

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/service.go
root_project_sfid  i.e foundation_sfid can be passed to the request_corporate_signature api if only one cla-group is linked with it
adding extra validations in request_corporate_signature api
=> [#1104] supporting cla signing at foundation level

cla-backend-go/cmd/dynamo_events_lambda/main.go, cla-backend-go/cmd/functional_tests/org_service/org_service.go, cla-backend-go/cmd/server.go, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/gerrits/service.go, cla-backend-go/project/handlers.go, cla-backend-go/repositories/service.go, cla-backend-go/signatures/models.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/service.go, cla-backend-go/v2/dynamo_events/projects_cla_groups.go, cla-backend-go/v2/organization-service/client.go
- Refactored delete CLA Group logic - moved most of delete code to service layer
- Added count to delete gerrit repos - only show event log when one or more gerrits are removed
- Added count to delete github repos - only show event log when one or more github repositories are removed
- Added count to number of signatures invalidated - only show event log when one or more signatures are invalidated
- Added remove permissions for CLA Manager, CLA Manger Designee, CLA Signatory
- Logging Updates
- Added additional event logging
=> [#1503] Delete CLA Group Cleanup

.circleci/config.yml
- Updated golang build ci version to 1.14.6
=> Updated CI golang build version

cla-backend/cla/models/github_models.py
- Resolved case where previous GitHub failed comment was not being updated
=> [#1043,#1498] CLA Check Comment Update

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/sign/service.go
- Fix the issue reported by Nirupama regarding authority_name provided as space than giving 500 internal server error.
- Update the validation while checking empty before that doing string trimming.
=> [#1519] V2 - While sending request to signatory 500 is returned when only spaces is provided for the authority_name api bugfix 

cla-backend-go/project/handlers.go, cla-backend-go/project/models.go, cla-backend-go/project/repository.go, cla-backend-go/swagger/common/properties/cla-group-name.yaml, cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.html, cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts, cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts, cla-frontend-project-console/src/ionic/services/cla.service.ts
- Added swagger spec constraints on the CLA Group name and CLA Group description - resolves issue with DocuSign envelope submission (too long)
- Updated PMC to match max length for CLA Group name and description.
- Added v1 UI description to CLA Group - users can now add/edit the CLA Group description field. Added UI validation.
- Resolved CLA Group edit/update issue which prevents updates.
=> [#1497] CLA Group Name Length

cla-backend/cla/models/docusign_models.py
- python - truncate project name to 100 characters to prevent API error with DocuSign
=> [#1497] Resolve DocuSign Subject Length Issue

cla-backend-go/v2/cla_manager/service.go
- Resolved panic issue caused by checking rolescopeConflict
- Allow users not associated with org to get added as designees
=> [1107] Bug/CLA Manager Request

cla-backend-go/project/handlers.go
1. The checking project already exists instead of name-checking with the project's internal ID.
=> [#1626] V1 - Project Console - Not able to update project name

cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
- check for nil before dereference
- consolidated API parameters - used single authUser variable for both
user id and email
=> Resolved Nil Reference for user email

cla-backend/requirements.txt
- Added setuptools 49.1.0 to hopefully resolve new issue with loading hug libraries on ubuntu/debian (lambada run-times)
- See: https://github.com/pypa/setuptools/issues/2232 and https://github.com/pypa/setuptools/issues/2350
=> Resolved Issue Loading Hug Under Ubuntu/Debian

cla-backend-go/project/service.go, cla-backend-go/v2/cla_groups/service.go
1. Call the Platform Project Service to determine the type =  project and project-group.
2. Based on type call the GetClaGroupByProjectSFID and GetClaGroupsByFoundationSFID function and returns the cla-group details.
=> [#1623] V2 - get cla groups endpoint returns empty list when queried by projectsfid

cla-backend-go/v2/cla_manager/service.go
- Fixed user invite with project ID missing.. Passing foundationSFID in the user invite payload
=> [#1737] Bug/Invite Admin with no LFID (Contributor Console)

cla-frontend-corporate-console/src/ionic/modals/add-manager-modal/add-manager-modal.ts
=> Corporate Console - Error message is not displayed when trying to add already accepted/added CLA Manager

cla-backend/cla/controllers/github.py, cla-backend/cla/models/dynamo_models.py
- Updated GitHub repo event logic to set the GitHub installation ID if
missing
- Added logic to set the modified time when we save the GH org record
=> Set GitHub Installation ID if Missing

cla-backend-go/cmd/functional_tests/main.go, cla-backend-go/cmd/repositories/repositories.go, cla-backend-go/github/client.go, cla-backend-go/github/github_installation.go, cla-backend-go/github/github_org.go, cla-backend-go/github/github_repository.go, cla-backend-go/github/github_user.go, cla-backend-go/github/protected_branch.go, cla-backend-go/github/protected_branch_test.go, cla-backend-go/go.mod, cla-backend-go/repositories/handlers.go, cla-backend-go/repositories/repository.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/repositories/handlers.go, cla-backend-go/v2/repositories/service.go
Adds 2 new endpoints for working with github protected branches
- `GET /project/{projectSFID}/github/repositories/{repositoryID}/branch-protection`  : gets the current status for the repo
- `POST /project/{projectSFID}/github/repositories/{repositoryID}/branch-protection`  : updates branch protection
=> github protected branch functionality and endpoints

cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/cla_manager/service.go
- use companySFID for invitation sending instead of internal id
- revert back the change for failing on error for invitation sending
=> use companySFID for invitation sending instead of internal id

cla-backend-go/v2/dynamo_events/service.go
- Don't log raw event - way too verbose in the log stream
=> Reduced event logging on dynamodb record updates

cla-backend/package.json, cla-backend/yarn.lock
- Resolved vulnerability with node-fetch library - Vulnerable versions: < 2.6.1, Patched version: 2.6.1
=> Updated Node-Fetch Library

cla-backend-go/project/helpers.go, cla-backend-go/project/models.go, cla-backend-go/project/projections.go, cla-backend-go/project/repository.go, cla-backend-go/swagger/common/project.yaml, cla-backend/cla/models/dynamo_models.py
- Added CLA Group project_live attribute/column to allow PROD reporting
of which repos are actually LIVE used by the community.
- Updated Python Data Model
- Updated GoLang Data Models
- Updated Project repository - moved helpers and projections to separate file
=> Added CLA Group project_live attribute support

cla-backend-go/v2/acs-service/client.go, cla-backend-go/v2/dynamo_events/projects_cla_groups.go, cla-backend-go/v2/dynamo_events/signatures.go
- Added additional logic to remove CLA roles associated with Projects
and Orgs associated with a CLA Group when the CLA Group is removed.
=> [#1503] CLA Group Delete - Role Cleanup

cla-backend-go/utils/utils_user_auth.go
- Removed user.Admin check -> user.admin will be true if the caller is
super-admin or system-admin or m2m client. In our case, users should be
in another role to access EasyCLA.
- Remmoved the user.Allowed check -> this may be used in the future, but
currently not implemented
=> Removed Admin User Permissions Check

cla-backend/cla/config.py, cla-backend/cla/controllers/github.py, cla-backend/cla/routes.py, cla-backend/cla/tests/unit/test_github.py, cla-backend/serverless.yml
addresses #1870 
- load the github webhook secret from ssm
- check for the signature of the request on `/github/activity`
=> adding check on /github/activity endpoint for webhook secret validation,

cla-backend-go/swagger/cla.v2.yaml
- Added regex for authority_name when signing corporate signatures allowing digits
=> Feature/Corporate Signature Input

bug-reporting.md, cla-backend/cla/controllers/github.py, cla-backend/cla/models/docusign_models.py, cla-backend/cla/models/github_models.py, cla-frontend-project-console/edge/security-headers.js, cla-frontend-project-console/src/ionic/decorators/restricted.ts, cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts, cla-frontend-project-console/src/ionic/pages/auth/auth.ts, cla-frontend-project-console/src/ionic/services/auth.service.ts, cla-landing-page/package.json, cla-landing-page/src/app/app.component.ts, cla-landing-page/src/app/app.module.ts, cla-landing-page/src/app/core/services/auth.service.ts, cla-landing-page/src/app/core/services/lfx-header.service.spec.ts, cla-landing-page/src/app/core/services/lfx-header.service.ts, cla-landing-page/yarn.lock
- Removed GitHub Secret printout from the AWS log
- Added more Github Secret processing debug
- Reordered DocuSign logic callback - updated GH comment/status early in the flow rather than at the end to make the GH refresh/status more responsive to use as they are navigated back to the UI from DocuSign
=> Remove GH Secret from Log + Re-Order Docusign Callback

cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
@nirupamav This fix depends on @wanyaland to update the old records flag.
=> V1 - REMOVE button is shown for disabled repos in Configure Github Repistories popup

cla-backend/cla/config.py, cla-backend/cla/controllers/github_application.py, cla-backend/cla/models/github_models.py, cla-backend/cla/utils.py
-  Moved to GitHub application class GitHubInstallation as loading the
GITHUB_PRIVATE_KEY from SSM is taking ~1 sec on startup which is killing
our response performance - in most API calls this key/attribute is not
used, so, we will lazy load this property on class construction
=> Lazy Load GitHub private Key

cla-backend-go/v2/company/service.go
- Handle error thrown if user is already associated with an org (ignore association)
=> [#2195] Feature/Error Handling Org association

cla-backend-go/github/github_repository.go, cla-backend/cla/models/github_models.py
- Updated logic to detect our existing GitHub comment - should now
properly identify own comment and update the comment details when we
transition from failed PR check to successful PR check.
=> [#722, #2194] Resolved GitHub Comment Update Issue

cla-backend/cla/config.py, cla-backend/cla/controllers/github.py, cla-backend/cla/models/github_models.py, cla-backend/cla/tests/unit/test_github_models.py, cla-backend/requirements.txt
* adds pr comment handler to check for `/easycla` command in order to re-run the cla checks.
=> [#2110] adding pr comment handler to check for comment commands

cla-backend-go/v2/cla_groups/service.go
Added function to check cla group present and return the data.
=> [LFX-2790] Project Console - Unable to add the CLA Group with the same name which got removed during un-enrollement of last project from the CLA Group

cla-backend-go/v2/cla_groups/service.go
Removed condition block and fixed the cla-group issue.
=> [#2224] Project Console - Unable to add the CLA Group with the same name which got removed during un-enrollement of last project from the CLA Group

cla-frontend-contributor-console/src/package.json, cla-frontend-contributor-console/src/yarn.lock
- Resolved low severity Vulnerable versions: >= 6.0.0, < 6.0.3 Patched
version: 6.0.3 Versions of kind-of 6.x prior to 6.0.3 are vulnerable to
a Validation Bypass. A maliciously crafted object can alter the result
of the type check, allowing attackers to bypass the type checking
validation.
=> Updated kind-of library

cla-frontend-corporate-console/src/package.json, cla-frontend-corporate-console/src/yarn.lock
- kind-of: low severity Vulnerable versions: >= 6.0.0, < 6.0.3 Patched
version: 6.0.3 Versions of kind-of 6.x prior to 6.0.3 are vulnerable to
a Validation Bypass. A maliciously crafted object can alter the result
of the type check, allowing attackers to bypass the type checking
validation.
- Minimist: low severity Vulnerable versions: >= 1.0.0, < 1.2.3 Patched
version: 1.2.3 Affected versions of minimist are vulnerable to prototype
pollution. Arguments are not properly sanitized, allowing an attacker to
modify the prototype of Object, causing the addition or modification of
an existing property that will exist on all objects.
=> Updated kind-of and minimist libraries

cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/user-service/client.go
- Refactored update user company details during cla manager designee flow
- Removed conversion to contact as this is done upon platform trigger on the user update
=> Feature/ Update Contributors Company

cla-backend-go/utils/signature_utils.go, cla-backend-go/utils/utils_user_auth_lambda.go, cla-backend-go/utils/utils_user_auth_standalone.go, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/events/handlers.go, cla-backend-go/v2/gerrits/handlers.go, cla-backend-go/v2/github_organizations/handlers.go, cla-backend-go/v2/metrics/handlers.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/repositories/handlers.go, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/signatures/handlers.go
- LF Operations has a scope of admin or developer which both have the user.Admin flag set to true on the auth model. This PR includes changes to allow the handler to invoke the permission checks with or without admin (LF-Operations) scope permissions. This allows for protected API endpoints, such as the CLA Manager endpoints to be reserved for only cla-manager roles.
=> Resolved [#1172] LF Operations Permissions

cla-backend-go/swagger/cla.v2.yaml
Added swagger validation for name pattern.
=> [#2366] When designating someone else to be a CLA Manager in the contributor console, it doesn't allow a period ('.') in the name

cla-backend-go/repositories/handlers.go, cla-backend-go/v2/dynamo_events/projects_cla_groups.go
Added project name instead of project SFID in easycla enables cla service for project event.
=> [#2369] Admin console - Issues on Activity Log

cla-backend-go/v2/project-service/client.go, cla-backend/cla/utils.py
- Updated GitHub comment to use landing page link from the configuration
which sets the link to a different value based on the DEV, STAGING, and
PROD environment.
=> Resolved [#2330] Invalid GitHub badge link in STAGING

cla-backend-go/swagger/common/add-gerrit-input.yaml
- Updated regex rule for gerrit instances name attribute
=> [#LFX2984] Feature/ Regex Gerrit Name

cla-backend-go/package.json, cla-backend-go/yarn.lock, cla-backend/package.json, cla-backend/yarn.lock, cla-frontend-contributor-console/package.json, cla-frontend-contributor-console/yarn.lock, cla-frontend-corporate-console/package.json, cla-frontend-corporate-console/yarn.lock, cla-frontend-project-console/package.json, cla-frontend-project-console/yarn.lock, package.json, yarn.lock
- Updated Axios library due to CVE-2020-28168 high severity Vulnerable
versions: < 0.21.1 Patched version: 0.21.1 Axios NPM package 0.21.0
contains a Server-Side Request Forgery (SSRF) vulnerability where an
attacker is able to bypass a proxy by providing a URL that responds with
a redirect to a restricted host or IP address.
=> Resolved Axios NPM Package/Library Vulnerability

cla-backend/cla/models/docusign_models.py
- Resolved issue When full_name docusign attribute is not in the
template, if not set, we try the signatory_name attribute, if still not
found don't set user_docusign_name in the signature. Added defensive
checks to avoid NoneType.
=> Resolved Issue with DocuSign ICLA Processing

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/utils/conversion.go, cla-backend-go/v2/cla_groups/service.go, cla-backend/cla/models/dynamo_models.py
- Updated swagger model to include the `setup_completion_pct` attribute, type integer ranging from 0-100
- Added CLA Group completion pct value to response payload - we CLA Group is created, but without a being assigned a repository, the completion pct is 80%. When the CLA Group is created and has one or more repositories the completion percentage is 100%.
=> Resolved #2433 Which Adds A CLA Group Setup Completion Pct

.circleci/config.yml
- Added pip upgrade command when setting up the python tool chain. This
aleviates the pip update warnings in the logs.
=> Infra - Resolved Pip Warning - Upgraded Pip to Current Version

cla-backend-go/go.sum, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/company/service.go
- Refactored GET for company, project CLAs by leveraging signing entity name
- Updated response with multiple companies
=> [#2515] Feature/Company Sign status

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/properties/company-signing-entity-name.yaml, cla-backend-go/utils/constants.go, cla-backend-go/utils/responses.go, cla-backend-go/v2/cla_manager/errors.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/handlers.go, cla-backend-go/v2/company/service.go
- Updated many API calls to switch from SFID to internal ID due to our
support of signing entity names. As a result of this introduction, we
now can have zero, one or more than 1 internal company records matching
a single SF parent record.  As a result, the APIs were updated to force
the client to provide the interal ID.
- Updated logging and permission checks to lookup SFID to check for
platform permissions
=> Updated v2 Corporate Console APIs - Changed SFID to Internal ID

cla-backend/cla/tests/unit/test_utils.py, cla-backend/cla/utils.py, cla-backend/requirements.txt
since we needed more low level access to the url parsing
=> cover more cases for urls that include # and remove the furl library

cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/cla_manager/service_test.go, cla-backend/cla/models/github_models.py, cla-backend/cla/tests/unit/test_github_models.py
- try not to save noreply github emails when creating the users from github flow
- try not to fetch noreply emails for the existing user emails
addresses ~[#2536]
=> [#2536] Fix/exclude noreply GitHub emails

cla-backend-go/go.sum, cla-backend-go/repositories/repository.go, cla-backend-go/swagger/common/github-repository-input.yaml, cla-backend-go/v2/repositories/service.go
- Resolved issue raised on reenabling repository
=> [#2600] Bug/ Add|Update Repository

cla-backend-go/go.sum, cla-backend-go/v2/repositories/service.go
- Resolved panic caused by different interfaces for gh-repo-input between v1 & v2
=> [#2600] Bug/Add GH Repo

cla-backend-go/Makefile, cla-backend-go/approval_list/service.go, cla-backend-go/cla_manager/handlers.go, cla-backend-go/cla_manager/service.go, cla-backend-go/emails/approval_list_templates.go, cla-backend-go/emails/approval_list_templates_test.go, cla-backend-go/emails/cla_manager_templates.go, cla-backend-go/emails/cla_manager_templates_test.go, cla-backend-go/emails/params.go, cla-backend-go/emails/params_test.go, cla-backend-go/emails/uitls.go, cla-backend-go/emails/v2_cla_manager_templates.go, cla-backend-go/emails/v2_cla_manager_templates_test.go, cla-backend-go/v2/cla_manager/handlers.go, cla-backend-go/v2/cla_manager/service.go
include project corporate console links inside of the email templates + support the extra fetching of the data and the rendering
addresses ~[#2677]
=> [#2677] include project corporate console links inside of the email templates

cla-backend-go/go.sum, cla-backend-go/v2/cla_groups/helpers.go, cla-backend-go/v2/cla_groups/service.go
- Updated enroll and unenroll sf projects with cla group
- Supported 3 level heirachy
=> [#LFX3038] Feature/Project Heirachy

.github/workflows/codeql-analysis.yml
- Resolved CodeQL warning: 1 issue was detected with this workflow: git
checkout HEAD^2 is no longer necessary. Please remove this step as Code
Scanning recommends analyzing the merge commit for best results.
=> Updated CodeQL Configuration

cla-backend/cla/models/docusign_models.py, cla-backend/cla/user_service.py
- Added defensive checks when the logged in user is not defined in the User Service. Now we handle the situation.
- Resolved logging error with trailing comma
- Added return types for User service helper functions -> returns List[dict] type helpers for IDE
=> Resolved IndexError When User Not Found in User Service

cla-backend-go/v2/cla_manager/service.go
Resolved #2748 - Remove GitHub User ID From Contributor Approval Email Request
- Removed GitHub ID from email content
- Added horizontal spacing to comma-separated list
=> Resolved #2748 - Remove GitHub User ID From Contributor Approval Email

cla-backend-go/approval_list/handlers.go, cla-backend-go/approval_list/repository.go, cla-backend-go/approval_list/service.go
- return request ID without having to query the record again - avoid data consistency issue (save -> read)
- renamed a few functions to match current naming conventions
- updated logging
=> Resolved Index Out of Range Error

cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/v2/cla_groups/helpers.go
- Added logic to set the enabled services for parent with the appropriate configuration is set
- Added new configuration for this flag (cla-enable-services-for-parent-{stage})
=> Resolves 2796 - Set Enable Services = CLA for Project Parent

cla-backend-go/cmd/dynamo_events_lambda/main.go, cla-backend-go/cmd/server.go, cla-backend-go/github/github_org.go, cla-backend-go/go.sum, cla-backend-go/signatures/models.go, cla-backend-go/signatures/repository.go, cla-backend-go/utils/constants.go
- Handled signature invalidations for ghorg and domain approval removals
- Implemented ghorg client for getting users under ghorg
- Handled ICLA and ECLA signature updates
=> [#2792] Feature/Invalidate Contributors

.github/ISSUE_TEMPLATE/bug_report.md, cla-backend-go/signatures/converters.go, cla-backend-go/utils/utils.go
- Added/updated signedOn date logic to use docusign date if available,
if missing, use the created date (generally close to the same value)
=> Resolved [#2814] CCLA Signature Signed On Date Not Showing

cla-backend-go/project/repository.go, cla-backend-go/project/service.go, cla-backend-go/v2/cla_groups/service.go
- When searching by foundation, we need to first consult the Project CLA
Group Mapping table entries for the CLA Groups - then load each CLA
group. Previous logic was only looking at the CLA Group table foundation
SFID (v1) value.
=> Resolved Foundation Query Issues

cla-backend-go/v2/cla_groups/helpers.go, cla-backend-go/v2/cla_groups/service.go
- Resolved issue of looping over unique CLA Groups when querying for
foundations. Bug caused timeout/channel blocking due to a mismatch of
channels vs looping iterations.
=> Resolved #2816 Issue with Foundation Query and Unique CLA Groups

cla-backend-go/docraptor/client.go
closing docraptor body is handled elsewhere, doing it here breaks the code
=> [#2817] closing docraptor body is handled elsewhere

cla-backend-go/cmd/server.go, cla-backend-go/v2/github_organizations/service.go
- Leveraged v1 getorgs service that caters for duplicates and returns right gh-orgs
=> [#2838] Bug/Project Github Orgs

cla-backend-go/gerrits/lf_group.go, cla-backend-go/go.mod, cla-backend-go/go.sum, cla-backend-go/signatures/models.go, cla-backend-go/signatures/repository.go, cla-backend-go/tests/utils_test.go, cla-backend-go/utils/signature_utils.go
- Only load gerrit user list on approval list removals
- Updated logging/error handling
- Load both ICLA and CCLA gerrit users using a go routine (concurrently)
- Resolved lint errors
=> Removed Duplicate CCLA Get Signature API Call

cla-backend-go/v2/cla_groups/handlers.go
we already set log events for unenrolled project there's no need to do it for cla group since it's confusing on the UI
addresses ~[#2872]
=> [#2872] removing extra cla_group.updated event which is confusing for UI

cla-backend-go/config/config.go, cla-backend-go/config/ssm.go, cla-backend-go/signatures/repository.go, cla-backend-go/utils/constants.go
- Added cla-signature-query-default parameter - A flag to indicate how
a default signature query should return data - show only 'active'
signatures or 'all' signatures when no other query signed/approved
params are provided
=> Added cla-signature-query-default Feature Flag

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/cla_groups/handlers.go
- Updated swagger spec to include 409 conflict response error
- Added logic to trap for conflict specific error and return 409
=> Resolved PCC-968 - Return 409 Conflict when Duplicate CLA Name Occurs

cla-backend/requirements.txt
Reverts communitybridge/easycla#2972 - this change breaks the python build due to incompatible urllib3 versions.
=> Revert "Bump urllib3 from 1.25.9 to 1.26.5 in /cla-backend"

contributing.md
Signed-off-by: Steve Winslow <steve@swinslow.net>
=> Fix typo in description of licenses

cla-backend-go/events/service.go, cla-backend-go/tests/project_helpers_test.go, cla-backend-go/utils/conversion.go, cla-backend-go/utils/project_helpers.go, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/helpers.go, cla-backend-go/v2/cla_groups/service.go, cla-backend-go/v2/github_organizations/service.go, cla-backend-go/v2/project-service/client.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/repositories/service.go, cla-backend-go/v2/sign/service.go
- project.Parent and project.EntityName was changed to optional, making
the generated type to change from string to *string. Updated logic that
reviews this field and dereferences the value as needed.
=> Resolved Issues Raised by Project Service Swagger Model Updates

cla-backend-go/events/service.go, cla-backend-go/tests/project_helpers_test.go, cla-backend-go/utils/project_helpers.go, cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/helpers.go, cla-backend-go/v2/cla_groups/service.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/github_organizations/service.go, cla-backend-go/v2/project-service/client.go, cla-backend-go/v2/project/handlers.go, cla-backend-go/v2/repositories/service.go, cla-backend-go/v2/sign/service.go
- Updated logic to use/leverage the project model foundation ID for the
parent ID rather than using the Parent attribute. Added additional
defensive logic to projects with no parents. Resolved null pointer error
when no parent is present.
=> Project Service - Use Foundation ID for Parent

cla-backend-go/events/service.go, cla-backend-go/package.json, cla-backend-go/yarn.lock, cla-backend/package.json, cla-backend/yarn.lock, cla-frontend-contributor-console/src/package.json, cla-frontend-contributor-console/src/yarn.lock
- Cleaned up event log parent project lookup logic
- Updated backend node lib vulnerability - xmlhttprequest-ssl
- CVE-2021-31597 critical severity Vulnerable versions: < 1.6.1
Patched version: 1.6.1 The xmlhttprequest-ssl package before 1.6.1
for Node.js disables SSL certificate validation by default, because
rejectUnauthorized (when the property exists but is undefined) is
considered to be false within the https.request function of Node.js.
In other words, no certificate is ever rejected.
- CVE-2020-28502 high severity Vulnerable versions: < 1.6.2 Patched
version: 1.6.2 This affects the package xmlhttprequest before 1.7.0;
all versions of package xmlhttprequest-ssl. Provided requests are
sent synchronously (async=False on xhr.open), malicious user input
flowing into xhr.send could …
=> Cleaned up Event Log Parent Project Lookup

cla-backend-go/go.mod, cla-backend-go/go.sum, cla-backend-go/users/repository.go, cla-backend-go/users/service.go, cla-backend/cla/models/dynamo_models.py
- cast github ID to an integer value for the index query call -
previously, string was accepted, but after the index update it now only
accepts an integer value
=> Forced GitHub ID to be Int

cla-backend-go/emails/v2_cla_manager_templates.go, cla-backend-go/tests/v2_cla_manager_templates_test.go
The link to the EasyCLA portal is generic and misleading. When a user clicks it, there is no obvious path to signing the CLA. I've removed that link and added a bold emphasis on the link a user receiving this email should click.
Signed-off-by: Mike Dolan <mikedolan@gmail.com>
=> Prioritize link visually in email to CLA Managers

cla-backend-go/github_organizations/handlers.go, cla-backend-go/gitlab_api/client_groups.go, cla-backend-go/go.mod, cla-backend-go/go.sum, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/gitlab-group-member.yaml, cla-backend-go/swagger/common/gitlab-group-members-list.yaml, cla-backend-go/v2/gitlab_organizations/handlers.go, cla-backend-go/v2/gitlab_organizations/service.go, cla-backend/cla/controllers/signing.py, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/utils.py
- Added v2 endpoint that fetches members of a given group id
- Updated controller for employee ack with right return_url_types(gitlab/github)
- check for gitlab group approval list criteria
=> [#3239,#3244] Bug/GitLab ECLA (#3238)

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/utils.py
- Refactored gitlab org id finding that previously returned easycla ID rather than gitlab
=> Bug/ Gitlan Org search

cla-backend-go/v2/gitlab-activity/service.go
- Depracated missingID badge on gitlab status update
=> Feature/GitLab Badge

cla-backend/cla/utils.py
- Resolved creating gh comment for invalid author details
Signed-off-by: Harold Wanyama <wanyaland+nickmango+foo@gmail.com>
=> Bug/Get Author details

cla-backend-go/swagger/cla.v2.yaml
- Removed valid characters restriction for authority_name. Resolves
issue of users with special characters in their name.
=> [3356] Resolves Authority Name Invalid Username Issue

cla-backend-go/swagger/common/add-gerrit-input.yaml
- Updated gerrit url to allow any URL (rather than a fixed list)
=> Updated Gerrit URL Swagger Input Constraints

cla-backend-go/github/github_installation.go, cla-backend-go/github_organizations/helpers.go, cla-backend-go/github_organizations/service.go, cla-backend-go/utils/project_helpers.go, cla-backend-go/v2/cla_groups/service.go, cla-backend-go/v2/github_organizations/service.go, cla-backend-go/v2/project-service/client.go, cla-backend/cla/models/github_models.py
- Added logic to identify and skip GitHub organization repositories that
are invalid or empty/nil.  This was causing an API error for the CFF
project.
- Added some additional defensive code when querying for projects in the
project service - trap for empty/nil fields.
=> Added Defensive Checks When Processing GitHub Organization Repositories

cla-backend/cla/models/github_models.py, cla-backend/cla/utils.py
- Updated filter to identify missing IDs from the commit list
- Updated logic that checks for previous missing IDs
- Added logic to stop processing GitHub PR when the repository is
disabled
=> Resolved 3378 - Duplicate Missing ID Issue

cla-backend-go/swagger/common/add-gerrit-input.yaml, cla-backend-go/swagger/common/gerrit.yaml
- Updated add/get gerrit API to allow LDAP values/ranges to support
single digit ID values, added regex to support positive integer values,
updated description
=> Updated Gerrit Swagger Spec

cla-backend/cla/models/github_models.py, cla-backend/cla/user.py, cla-backend/cla/utils.py
- Added additional logic to tag users in additional GitHub gating
failure use cases
=> Added Additional User Tagging Logic for CLA Gating Failures

cla-backend/cla/utils.py
- Resolved issue when categorizing missing affiliations
=> [3481] Updated Missing Affiliations Logic

.circleci/config.yml
- resolves issue with incompatiable node versions when deploying the landing page
=> Updated Node Version for Landing Page Deployment

cla-backend-go/signatures/projections.go, cla-backend-go/signatures/repository.go
- added function to fetch the project company employee signature count
based on the specified filter criteria. Leveraged a go routine and a
separate query via channel response.
=> Updated Total Count Logic

cla-backend/cla/utils.py
- Added date/time string format to handle legacy records: '%Y-%m-%dT%H:%M:%S.%f'
=> Added Additional Date/Time String Format for Python

cla-backend/cla/models/dynamo_models.py
- removed trailing comma on __str__ tuple
=> Resolved Python Typo in Signature Class

cla-backend/cla/models/dynamo_models.py
- updated store table TTL from 1 day to 1 week - this will allow us to update PR's that have been opened in the past week after the CLA manager adds the user to one of the approval lists
=> Updated Store Table TTL to 1 Week

cla-backend-go/github_organizations/service.go
- Refactored gh orgs query for a given project's parent orgs quering the parents orgs instea of fetching child orgs
=> [#3604] Bug/Project GH orgs

cla-backend-go/v2/cla_groups/handlers.go, cla-backend-go/v2/cla_groups/helpers.go, cla-backend-go/v2/cla_groups/service.go
- Fixed bug caused by unenrolling error halting unassociation of CLA and a given project
=> [#3603] Unenrolling Clagroup

cla-backend-go/signatures/repository.go, cla-backend-go/v2/signatures/handlers.go
- Resolved company contributors query , caused by duplicate ecla entries, using project-signature-index & related filters
=> [#PCC-2489] Bug/ Company Contributors

cla-backend-go/github_organizations/service.go
- Refactored gh org query by parent returning all child orgs under a given parent
=> [#3605] Feature/Get GH Orgs by Parent

cla-backend-go/repositories/models.go
- Resolved response showcasing wrong projectsfid for a given repository
=> [#PCC-2543] Bug/Fetching Projects repositories

cla-backend-go/Makefile, cla-backend-go/swagger/common/properties/email.yaml
- Updated the regex to support longer email suffix (from 5 to 10 characters)
Resolves: #3649
=> Updated Swagger API - User Email Regex

cla-backend-go/v2/sign/service.go
- Filtered multiple CLAs returned at foundation Level to offset error caused by multiple CLAs returned
=> Bug/Foundation Level Corporate Signature

cla-backend-go/emails/params.go, cla-backend-go/tests/v2_cla_manager_templates_test.go
- Removed queryescape on project name for the hyperlink to the project console.
=> [#3689] Feature/ Request CLA Manager Email

cla-backend-go/Makefile, cla-backend/cla/tests/unit/test_github_models.py
- disabled CI/CD unit tests that use the remote GitHub service. We need
to mock this interface as it breaks the CI/CD process for forked
repos.
=> CI/CD - Disabled GitHub Unit Tests

cla-backend-go/emails/v2_cla_manager_templates.go
The link to the EasyCLA portal is generic and misleading. When a user clicks it, there is no obvious path to signing the CLA. I've removed that link and added a bold emphasis on the link a user receiving this email should click.
=> Revise the action for CLA signatories.

cla-backend-go/cmd/gitlab_repository_check/handler/handler.go, cla-backend-go/swagger/common/gitlab-organization.yaml, cla-backend-go/v2/common/models.go, cla-backend-go/v2/dynamo_events/gitlab_branch_protection.go, cla-backend-go/v2/dynamo_events/gitlab_webhooks.go, cla-backend-go/v2/gitlab-activity/handlers.go, cla-backend-go/v2/gitlab-activity/service.go, cla-backend-go/v2/gitlab_organizations/constants.go, cla-backend-go/v2/gitlab_organizations/handlers.go, cla-backend-go/v2/gitlab_organizations/repository.go, cla-backend-go/v2/gitlab_organizations/service.go, cla-backend-go/v2/gitlab_sign/service.go, cla-backend-go/v2/repositories/service.go
- Updated logic to check expiry
- Added expiry column in the gitlab org table attributes
- Refactored update of gitlaborg record with repository call other than service call
=> [#3537] Bug/GitLab Refresh

cla-backend/cla/tests/unit/test_github_models.py, cla-backend/cla/tests/unit/test_user_service.py
- commented out unit tests that connect to and use external AWS, GitHub,  GitLab, and LFX User Service. These need to be properly stubbed out or mocked.  Currently, these tests break the CI/CD PR pipeline due to needed additional tokens and AWS access. 
=> CI/CD - Commented Out Unit Tests That Use External Services

cla-backend-go/v2/gitlab-activity/service.go
- Updated auth details to include gitlabid for gitlab author
=> Bug/GitLab MR

cla-backend-go/repositories/repository.go
- Removed repository_project_id attribute upon disabling of github repository
=> [#3762]Bug/Disable GitHub Repository

cla-backend-go/cmd/zipbuilder_lambda/main.go, cla-backend-go/cmd/zipbuilder_scheduler_lambda/main.go, cla-backend-go/utils/constants.go, cla-backend-go/v2/signatures/service.go, cla-backend-go/v2/signatures/zip_builder.go
- refactored/updated logic to support CSV Zip file downloads from AWS
S3. Since some projects have 10k+ ICLAs signed, it is impractical to
wait while the backend processes all the signature files and streams
the results back to the client. This can sometimes take >5 minutes for
large CLA groups.  Instead, we want to periodically (daily?)
pre-process and generate the CSV download and store the results. Then,
users can quickly download the CSV as a zip file when the navigate to
the UI. This PR stages the logic to accomplish this. The lambda
processing is in place and the methods are there. The remaining piece
is to query the DB, package, zip and upload.
=> CSV Download - Added Placeholder for CSV Zip File

cla-backend-go/v2/gitlab-activity/service.go
- Updated user details with login and name labels
=> [#3769] GitLab Auth Info

cla-backend-go/repositories/repository.go
- Added repository_project_id attribute for re-enabling github repository given a different salesforce project
=> [#3762] Bug/GitHub repository switch

cla-backend-go/gitlab_api/mr.go, cla-backend-go/users/repository.go, cla-backend-go/v2/gitlab-activity/service.go, cla-backend-go/v2/gitlab_sign/service.go
- don't always create a new user when processing MR requests
- only search for active and non-blocked GitLab users
- adjusted user table search critiera
=> GitLab - expanded search scope when processing MR events

cla-backend/cla/models/docusign_models.py
- added sign_optional support to handle situations where users can sign one of two signing areas on the form. Docusign doesn't seem to support if this or that construct, so we needed to have a way to allow the users to sign one of two areas on the form to indidicate which option they chose.
=> Added Support for Optional Signing of DocuSign

cla-backend/cla/utils.py
The current error message is not very clear and we've had multiple users in the PyTorch repo having problems with resolving this.
=> Explain missing email issue in error message

cla-backend-go/signatures/repository.go
- Due to duplicate records returned resolved duplicate records by fetching latest signature
=> [#3920] Feature/Get Latest Signatures

.github/workflows/build-pr.yml
GitHub no longer requires the use of a username in the clone URL when authenticating with a PAT
=> Chore: Use just PAT for build-pr

cla-backend/package.json, cla-backend/yarn.lock
This reverts commit 6f93cbb0948794876e03e8d0bdbd2f30cd121230.
=> Revert "Bump serverless from 3.32.2 to 3.33.0 in /cla-backend"

cla-backend/cla/models/github_models.py
- Check for previously failed comment for missing ID use case which factors comment edits
=> [#4011] Feature/ Missing ID comment

.github/workflows/build-pr.yml, .github/workflows/deploy-dev.yml, cla-backend-go/serverless.yml, cla-backend/Makefile, cla-backend/cla/models/docusign_models.py, cla-backend/cla/utils.py, cla-backend/requirements.txt, cla-backend/serverless.yml
This reverts commit 2d864232a698e1c73edfb15088c212478c422662.
=> Revert "Update platform for cryptography"

cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/github_models.py
- Used threading to handle commits
=> Bug/Thread Pool commit

tests/functional/cypress.env.json, tests/functional/cypress/e2e/cla-group.spec.ts, tests/functional/cypress/e2e/events.spec.ts, tests/functional/cypress/e2e/foundation.spec.ts, tests/functional/cypress/e2e/github-organizations.spec.ts, tests/functional/cypress/e2e/github-repositories.spec.ts, tests/functional/cypress/fixtures/events/getCompanyProjectEvents.json, tests/functional/cypress/fixtures/events/getFoundationEvents.json, tests/functional/cypress/fixtures/events/getProjectEvents.json, tests/functional/cypress/support/commands.js
added common method for cypress-schemaValidate
=> Cypress schema validate

cla-backend/cla/docusign_auth.py
- Added module to handle docusign authentication
=> [#3970]Feature/Docusign Auth Module

.github/workflows/deploy-dev.yml, cla-backend/serverless.yml
- Added lambda layer to support cryptography integration for docusign oauth flow
=> [#3970,4002] Bug/Cryptography Integration

tests/functional/cypress/e2e/health.cy.ts, tests/functional/cypress/fixtures/health/healthCheck.json
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/health/operation/healthCheck
=> Added cypress test case for cypress-health API

cla-backend-go/go.mod, cla-backend-go/go.sum, cla-backend-go/serverless.yml, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/docusign_auth/auth.go, cla-backend-go/v2/main/main.go, cla-backend-go/v2/sign/docusign.go, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/jwt.go, cla-backend-go/v2/sign/service.go
- Ported python flow for icla and ccla sign to golang
- Handled the new docusign auth flow
=> [$4002] Feature/doc sign go

cla-backend-go/utils/constants.go, cla-backend-go/v2/sign/docusign.go, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/service.go
- Fixed lint issues for golang docusign integration
=> Lint Issues

cla-backend-go/v2/sign/service.go
- Resolved complexity issue for the populateSignURL function
=> [#4002]Feature/Docsign intgeration Lint

cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/v2/sign/service.go
- Created signature for icla and ccla signflows
=> Bug/Docusign Integration

cla-backend-go/cmd/server.go, cla-backend-go/v2/sign/service.go
=> Bug/Docsign return URL

cla-backend/cla/models/github_models.py
- Resolved workers that handle user commits for a PR
=> Bug/Sign Process

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/sign/handlers.go, cla-backend-go/v2/sign/service.go
- Resolved issue on fetching Gitlab org using external ID
- Updated Gitlab callback endpoint
=> Bug/Gitlab Sign Flow

cla-backend-go/v2/sign/service.go
- Resolved ccla request via email use case
=> [#4247] Bug/Selecting Signatory

cla-backend-go/cmd/migrate_approval_list/main.go, cla-backend-go/events/repository.go, cla-backend-go/signatures/repository.go, cla-backend-go/v2/approvals/models.go, cla-backend-go/v2/approvals/repository.go, cla-backend-go/v2/signatures/converters.go
- Updated migration of approval list items
=> [#3750] Migrate Approval List

cla-backend/cla/models/github_models.py, cla-backend/cla/tests/unit/conftest.py, cla-backend/cla/tests/unit/test_company_event.py, cla-backend/cla/tests/unit/test_docusign_models.py, cla-backend/cla/tests/unit/test_dynamo_models.py, cla-backend/cla/tests/unit/test_email_approval_list.py, cla-backend/cla/tests/unit/test_event.py, cla-backend/cla/tests/unit/test_gh_org_models.py, cla-backend/cla/tests/unit/test_github.py, cla-backend/cla/tests/unit/test_github_controller.py, cla-backend/cla/tests/unit/test_github_models.py, cla-backend/cla/tests/unit/test_model.py, cla-backend/cla/tests/unit/test_project_event.py, cla-backend/cla/tests/unit/test_salesforce_projects.py, cla-backend/cla/tests/unit/test_signature_controller.py, cla-backend/cla/tests/unit/test_user_event.py, cla-backend/cla/tests/unit/test_utils.py, cla-backend/cla/utils.py
- Updated aggregated co-authors fetched in the processing list
=> [#3884] Feature/Co-Author Process

cla-backend/cla/models/github_models.py, cla-backend/cla/tests/unit/test_github_models.py
- Disabled co-auth feature due to privacy limitations
=> Feature/Co Auth disabled

.github/workflows/build-pr.yml, .github/workflows/deploy-dev.yml
- Using upgraded serverless version deploy command
=> Bug/CD Dev

cla-backend-go/v2/signatures/service.go, cla-backend-go/v2/signatures/service_test.go
- Resolved failed test cases for the lfid authorization service
=> Bug/Authorized API tests

cla-backend-go/users/models.go, cla-backend-go/users/repository.go, cla-backend-go/v2/signatures/service.go, cla-backend-go/v2/signatures/service_test.go
- Resolved authorization cla endpoint with users on a non existant company
=> [#4348] Bug Icla and Company check

cla-backend-go/v2/user-service/client.go
- Resolved the swagger client issue that cropped up in a recent change on the user-service
=> [#4373] Bug/User Service update

cla-backend-go/signatures/mocks/mock_service.go, cla-backend-go/signatures/repository.go, cla-backend-go/signatures/service.go, cla-backend-go/signatures/service_test.go, cla-backend-go/v2/signatures/service.go, cla-backend-go/v2/signatures/service_test.go
- Resolved bug for ecla checks against emails in the email approval list
=> [#4348] Bug/Ecla Check

cla-backend-go/v2/cla_manager/service.go, cla-backend-go/v2/company/service.go, cla-backend-go/v2/dynamo_events/cla_manager.go, cla-backend-go/v2/sign/service.go, cla-backend-go/v2/user-service/client.go
- Updated function using the restful Api method
=> [#4404] Bug/LF Search by Email

cla-backend-go/cmd/ldap_gerrit_check/main.go
- Resolved lint issues in the ldap_gerrit cli tool
=> Bug/Lint Issues

.github/workflows/build-pr.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/tests/unit/test_gh_org_models.py
- Resolved Github Org installation event issue
=> [#4433] Bug/Adding GH Org

.github/workflows/build-pr.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/yarn-scan-backend-go-pr.yml, .github/workflows/yarn-scan-backend-pr.yml, cla-backend-go/Makefile
=> Feature/Go Version

cla-backend/cla/models/docusign_models.py, cla-backend/cla/tests/unit/test_ecla.py
- Resolved missing datestamp values for new ecla records
=> [#4264] Bug/Ecla Acknowledged timestamp

cla-backend-go/signatures/repository.go
- Fixed issue with pagesize greater than the total
=> [#4460] Bug/Corporate Contributors API pagination

cla-backend-go/signatures/repository.go
- Removed duplicates for corporate contributors
=> [#4460] Feature/Corporate contributors dups

.github/workflows/deploy-dev.yml
Updates the Deploy DEV workflow to create the python virtual environment
in '.venv', and not 'venv', as '.venv' is explicitly excluded from
serverless while the other is not.
Signed-off-by: Trevor Bramwell <tbramwell@linuxfoundation.org>
=> Create Python venv in '.venv' for Builds

cla-backend-go/project/common/helpers.go, cla-backend-go/tests/project_test.go, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/tests/unit/test_dynamo_models.py, utils/get_all_current_documents_sf.sh, utils/get_projects_corporate_documents_sf.sh, utils/get_projects_individual_documents_sf.sh
- Add utils to get (latest/newest or all) ICLA/CCLA templates for given project.
- Fix get latest document functions in `python` and `golang` (some edge cases).
- Add test coverage for those function (including those edge cases too).
The issue was subtle, could happen when minor version is >= 10:
```
I think I’ve found some subtle bug in golang function to get the latest document (when minor is > 9) - this is not affecting our case, but I will fix to avoid issues in the past.
golang parses versions as float major.minor - parsing from string made of two integers. But when minor becomes 10 then 2.10 is NOT > than 2.9 because 2.10 as float is the same as 2.1.
actually python version also has possible subtle bug, I’ll fix it as well - detected this while adding the test coverage - it wasn't …
```
=> Add utils to get (latest) ICLA/CCLA templates and fix get latest document functions in py and go + add test coverage

cla-backend-go/cmd/server.go, cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/v2/current_user/handlers.go, cla-backend-go/v2/current_user/service.go, cla-backend/cla/controllers/repository_service.py, cla-backend/cla/models/github_models.py, cla-backend/cla/routes.py, utils/active_signature_py.sh, utils/check_prepare_employee_signature_py.sh, utils/get_user_from_session_py.sh, utils/get_user_from_token_go.sh, utils/lookup_store_ddb.sh, utils/lookup_store_sf.sh
1) Added V2 (`python`) API to get user from `GitHub session`:
- `/v2/user-from-session`.
Tested with Mock classes so it should work when deployed. Call it via: `/v2/user-from-session` and if there is an active `OAuth2` session then you will get user details like:
```
{
"date_created": "2025-05-21T08:05:19.221609+0000",
"date_modified": "2025-05-21T08:09:19.943455+0000",
"lf_email": null,
"lf_sub": null,
"lf_username": null,
"note": null,
"user_company_id": null,
"user_emails": [
"test@user.com"
],
"user_external_id": null,
"user_github_id": "123",
"user_github_username": "testuser",
"user_gitlab_id": null,
"user_gitlab_username": null,
"user_id": "78bb15eb-8cbf-44e6-8b64-c713db6ee51b",
"user_ldap_id": null,
"user_name": "Test User",
"version": "v1"
}
```
If there is no active session it …
=> Adding APIs: /v2/user-from-session, /v4/user-from-token

cla-backend-go/v2/company/service.go, utils/get_company_project_cla_managers.sh
Use data that was already loaded in `SignatureACL` as `name` & `email` prior to calling `user-svc` API, so if any of signature's ACL user is not found in user-service (by using LF username) then return data that was already found in DynamoDB.
cc @thakurveerendras @mlehotskylf
=> Fix #4666 - use DynamoDB name & email prior to calling user-svc API as a fallback

cla-backend-go/swagger/cla.v2.yaml, cla-backend-go/swagger/common/project-compat.yaml, cla-backend-go/swagger/common/properties/uuid.yaml, cla-backend-go/swagger/common/user-active-signature.yaml, cla-backend-go/v2/sign/handlers.go, tests/py2go/README.md, tests/py2go/api_test.go
Refactored UUID validation to use reusable, general UUID patterns (not v4-only) across Swagger definitions.
Added tests for invalid and non-v4 UUIDs with exact response checks.
Simplified test config and improved debug output.
cc @mlehotskylf - this fixes the issue that we've seen yesterday during KT call.
=> Add test coverage for non-v4 and invalid UUIDs and fix v4 APIs to behave as V2 APIs - accept non-v4 UUIDs

README.md, WHITELISTING_BOTS.md, cla-backend-go/events/event_data.go, cla-backend-go/events/event_types.go, cla-backend-go/github/bots.go, cla-backend-go/github_organizations/models.go, cla-backend-go/signatures/service.go, cla-backend-go/swagger/common/github-organization.yaml, cla-backend-go/v2/sign/helpers.go, cla-backend/cla/models/dynamo_models.py, cla-backend/cla/models/event_types.py, cla-backend/cla/models/github_models.py, utils/describe_all.sh, utils/describe_table.sh, utils/list_tables.sh, utils/skip_cla_entry.sh
This PR implements feature requested in https://github.com/linuxfoundation/easycla/issues/4701.
cc @mlehotskylf @thakurveerendras @amolsontakke3576 @ahmedomosanya @jarias-lfx @dealako
=> Add support for skipping CLA requirement for bots

BOT_ALLOWLIST.md, cla-backend-go/github/bots.go, cla-backend-go/swagger/common/github-organization.yaml, cla-backend/cla/models/github_models.py, utils/skip_cla_entry.sh
Adds support for skipping login or email or name on additional condition - `""` (empty) - that means that pattern matches when given property is not set, is null of is empty string.
Why? Because GitHub bots have no login (they only have email like `<num>+Copilot@users.noreply.github.com` and name `copilot-swe-agent[bot]`.
To deal with that we had to set login pattern to `*` (meaning allow all) which theoretically allows any Github login with email like one I’ve described and name = `'copilot-swe-agent[bot]'` to skip CLA.
If GitHub is not sending login for those bots then there must be a pattern that matches EXACTLY that.
I'm using `""` (empty string), so the pattern would be `;email_pattern;name_pattern` - that way it is more secure.
cc @mlehotskylf @ahmedomosanya
=> Add support for patterns matching empty or missing properties: login, email, name

BOT_ALLOWLIST.md, cla-backend-go/github/bots.go, cla-backend-go/swagger/common/github-organization.yaml, cla-backend/cla/models/github_models.py, utils/skip_cla_entry.sh
Adds support for skipping login or email or name on additional condition - `""` (empty) - that means that pattern matches when given property is not set, is null of is empty string.
Why? Because GitHub bots have no login (they only have email like `<num>+Copilot@users.noreply.github.com` and name `copilot-swe-agent[bot]`.
To deal with that we had to set login pattern to `*` (meaning allow all) which theoretically allows any Github login with email like one I’ve described and name = `'copilot-swe-agent[bot]'` to skip CLA.
If GitHub is not sending login for those bots then there must be a pattern that matches EXACTLY that.
I'm using `""` (empty string), so the pattern would be `;email_pattern;name_pattern` - that way it is more secure.
cc @mlehotskylf @ahmedomosanya
=> Add support for patterns matching empty or missing properties: login, email, name [prod]

.gitignore, cla-backend/cla/controllers/github.py, cla-backend/cla/models/dynamo_models.py, utils/count_apis.sh, utils/search_aws_log_group.sh
Fixes https://github.com/linuxfoundation/easycla/issues/4759 cc @mlehotskylf @jarias-lfx @ahmedomosanya 
=> Unicron 4759 fix missing installation id prod

tests/functional/cypress/e2e/v4/signatures.cy.ts
This is a pure AI fix - I was testing Copilot CLI to fix intermittent issues on cypress E2E test coverage.
Then I checked this myself and all fixes look reasonable, hence this PR...
=> Fix the test coverage with Copilot CLI
